### ISSUE TITLE
[Bug] Some logs not being done with our custom logger

### ISSUE THREAD

**Issue by jcm300** [temporalio/sdk-typescript#1006]
### What are you really trying to do?

We want all Temporal logs to be done with our custom logger.

### Describe the bug

We are using a custom logger with Temporal. It works great, however there are some logs that don't seem to be done with our custom logger.
These logs happen at the start and shutdown of a worker. For example, while running tests (our logger doesn't log while running tests, so these that show up is because they were not done with our logger):

<img width="809" alt="Screenshot 2022-12-26 at 10 08 31" src="https://user-images.githubusercontent.com/23564120/209536473-9a280244-4168-4023-b4de-ecc585d511dc.png">

### Minimal Reproduction

```
import { Runtime, Worker } from '@temporalio/worker';
import type { Logger, LogLevel, LogMetadata } from '@temporalio/worker';

// Logger that doesn't log, only to show the logs not used by it
class DebugLogger implements Logger {

    log(level: LogLevel, message: string, meta?: LogMetadata | undefined) {
      return
    }

    trace(message: string, meta?: LogMetadata | undefined) {
      return
    }

    info(message: string, meta?: LogMetadata | undefined) {
      return
    }

    debug(message: string, meta?: LogMetadata | undefined) {
      return
    }

    error(message: string, meta?: LogMetadata | undefined) {
      return
    }

    warn(message: string, meta?: LogMetadata | undefined) {
      return
    }
}

const logger = new DebugLogger();

Runtime.install({ logger });

async function run() {
  const worker = await Worker.create({
    taskQueue: 'pull-deposits',
  });

  await worker.run();
}

run().catch((err) => {
  logger.error(err);
  process.exit(1);
});
```

Then you should run this worker and see the following logs for it:
<img width="878" alt="Screenshot 2022-12-26 at 10 20 13" src="https://user-images.githubusercontent.com/23564120/209537619-d696aa3d-803a-4c6b-bdec-7a7601eaea35.png">

And without this logger,
```
import { Worker } from '@temporalio/worker';

async function run() {
  const worker = await Worker.create({
    taskQueue: 'pull-deposits',
  });

  await worker.run();
}

run().catch((err) => {
  process.exit(1);
});
```

We see the following at the terminal:
<img width="878" alt="Screenshot 2022-12-26 at 10 25 20" src="https://user-images.githubusercontent.com/23564120/209538140-34d47a28-4225-4b82-8e5f-18ee0bfb1509.png">

Is this suppose to happen? Are we missing something from the logging steps in the guides?

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: Temporal Server -> 1.19.0, Temporal Typescript SDK -> 1.5.2
- Are you using Docker or Kubernetes or building Temporal from source? Docker

### Additional context
N/A

**Comment by bergundy** [comment]
Those logs are emitted from Rust core.
You'll need to set up log forwarding in the runtime options:

```ts
Runtime.install({
  logger,
  telemetryOptions: {
    logging: {
      filter: makeTelemetryFilterString({ core: logLevel, other: logLevel }),
      forward: {},
    },
  },
})
```

**Comment by jcm300** [comment]
Yup, we were missing that part.
Thank you!
