### ISSUE TITLE
[Bug] ScheduleClient.list() fails to return any schedules

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/sdk-typescript#1013]
### What are you really trying to do?

List schedules with the `ScheduleClient.list()` API

### Describe the bug

No schedules are returned when I can verify there are schedules through `tctl`, the UI and go-sdk.

### Minimal Reproduction

See the `basic` typescript test here https://github.com/temporalio/sdk-features/pull/192

### Environment/Versions

- OS and processor:M1 Mac
- Temporal Version: tried temporalite 1.17 and 1.19
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by bergundy** [comment]
Is there any chance that the spec is falsy in those schedules?

https://github.com/temporalio/sdk-typescript/blob/f16d1dac5176c3a695e3332de0b420bad07bbf5b/packages/client/src/schedule-client.ts#L373

**Comment by igorsechyn** [comment]
I am hitting the same issue in our setup. What I noticed is that `workflowService.listSchedules` does not always return the full response. In most cases it just returns an array of schedule ids and thats it. However sometimes i saw responses containing the full information.

This is how I create schedules 
```
await temporalClient.schedule.create({
        scheduleId,
        action: {
          taskQueue: Config.TEMPORAL_LINEAR_TASK_QUEUE,
          type: "startWorkflow",
          workflowType: workflow,
          args: [anonymousWorkflowContext],
          workflowId: workflow,
        },
        spec: {
          cronExpressions: [cronConfig.schedule],
        },
        policies: {
          overlap: ScheduleOverlapPolicy.SKIP,
        },
      });
```

So the spec should not be falsy

**Comment by bergundy** [comment]
@igorsechyn The schedules list response is eventually consistent, you may have to wait for your schedule to appear in the response.

**Comment by Quinn-With-Two-Ns** [comment]
@bergundy the schedule spec is not falsy.  The issue I saw only happens in the typescript sdk not the go sdk.

**Comment by mjameswh** [comment]
>The issue I saw only happens in the typescript sdk not the go sdk.

@igorsechyn is reporting this issue using raw GRPC calls... The SDK is essentially not involved there. I personally think this is an eventual consistency issue, but then... how come we never observe this using the Go SDK?!?

**Comment by igorsechyn** [comment]
> The schedules list response is eventually consistent, you may have to wait for your schedule to appear in the response.

I dont think this is the case. Our use case:
- on app startup we check, if there are any cron jobs we need to run, if there are we create temporal schedule objects. 
- if we remove a cron from our codebase, we also want to delete corresponding schedule in temporal, so on each startup we fetch the list of schedules

I have been testing it locally and although schedules were running for some time now, on app restart we only get a list with schedule's id, i.e. when using `workspaceService`. So it's not that we do not see any schedules, we see them, but the response only contains an id.

**Comment by igorsechyn** [comment]
Just tested again, and after a schedule running for multiple hours querying the list on our app restart, temporal still returns just schedule ids.

**Comment by mjameswh** [comment]
@igorsechyn Which "deployment type" of Temporal server are you using exactly (ie. Docker, temporalite, temporal-cli, etc) and which persistence backends?

**Comment by igorsechyn** [comment]
> @igorsechyn Which "deployment type" of Temporal server are you using exactly (ie. Docker, temporalite, temporal-cli, etc) and which persistence backends?

We are running temporal on kubernetes using docker images. We currently use postgres as a persistence backend.
