### ISSUE TITLE
[Bug] node takes 10 seconds to exit since @grpc/grpc-js 1.8.0

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-typescript#1023]
### Describe the bug

Running a very simple program using `Client` or `Connection`. At the end, `node` wait 10 seconds before exiting, unless we add an explicit `process.exit(0)` in the code.

This was reproduced using @grpc/grpc-js 1.8.0 and 1.8.3, but does not happens on 1.7.3.

**Example:**

<img width="769" alt="image (1)" src="https://user-images.githubusercontent.com/6412169/211933605-2dc29c08-9ab7-43b7-8168-b49f4a2c3a10.png">

### Minimal Reproduction

```
import { Connection } from '@temporalio/client';

Connection.connect()
  .then(() => console.log('Connected'))
  .catch((e) => console.log(e));
```

**Comment by mjameswh** [comment]
Seems to be related to the recent addition of _retries_ directly in the library. For some reason, the [deadline timer](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/resolving-call.ts#L95) does not cleared on some successful calls.

**Comment by bergundy** [comment]
Good catch, do you think this could be related to the jest hang we're seeing?
Does it help if the grpc client is closed?

**Comment by lorensr** [comment]
No change when I add this line:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/251288/211937928-e0560a6f-ff61-432c-b405-1de46fc7a1bf.png">


<img width="208" alt="image" src="https://user-images.githubusercontent.com/251288/211937943-0074efd5-a4af-4b2f-91a4-c75e242ea6c3.png">

**Comment by mjameswh** [comment]
>Good catch, do you think this could be related to the jest hang we're seeing?

No, 1.8.0 was released December 7th, the Jest issue existed well before that. It could however possibly explain some issues observed in `features` tests, but it is too early to make statement here.

Anyway, I personally think that 1.8.0 should have been a major. They introduced a new retry mechanism, which make it breaking for any software that already implemented retries at another level. We'll have to put a quite a lot of thinking and testing before we move to 1.8+.

So for now, I think the only reasonable solution is to change dependency to ~1.7.3.

**Comment by bergundy** [comment]
I'd be fine with pinning the minor version and keeping an open issue to upgrade to >=1.8 when were ready to invest more into this.
