### ISSUE TITLE
[Bug] cannot spawn test-server

### ISSUE THREAD

**Issue by MrMaximus** [temporalio/sdk-typescript#1024]
### Describe the bug

I'm trying to execute workflow tests using @temporalio/testing with jest in docker.  Creating a TestWorkflowEnvironment with `TestWorkflowEnvironment.create()` fails with the below error

```bash
  ● Console
    console.error
      2023-01-11T13:27:32.036Z [ERROR] Failed to kill test server child process {
        error: Error: kill ESRCH
            at process.kill (node:internal/process/per_thread:220:13)
            at kill (/builds/my-service/node_modules/@temporalio/testing/src/child-process.ts:33:11)
            at Function.create (/builds/my-service/node_modules/@temporalio/testing/src/index.ts:226:19)
            at processTicksAndRejections (node:internal/process/task_queues:96:5)
            at /builds/my-service/src/worker/workflows/my-workflow.test.ts:28:13 {
          errno: -3,
          code: 'ESRCH',
          syscall: 'kill'
        }
      }
      26 |
      27 | beforeAll(async () => {
    > 28 |   testEnv = await TestWorkflowEnvironment.create();
         |             ^
      29 | });
      30 |
      at DefaultLogger.defaultLogFunction [as logFunction] (node_modules/@temporalio/worker/src/logger.ts:41:13)
      at DefaultLogger.log (node_modules/@temporalio/worker/src/logger.ts:67:12)
      at DefaultLogger.error (node_modules/@temporalio/worker/src/logger.ts:93:10)
      at Function.create (node_modules/@temporalio/testing/src/index.ts:228:16)
      at src/worker/workflows/my-workflow.test.ts:28:13
```

The error is because its trying to kill a child process that didn't start. The child process being referenced is from spawning the `test-server`.

I tried to start the `test-server` myself and the error is
```bash
./test-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./test-server)
./test-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./test-server)
```

There is a npm install script in the `@temporalio/testing@v1.1.0` library which pulls the latest release of the test server from `https://api.github.com/repos/temporalio/sdk-java/releases/latest`, and a new release was published two days ago. I expect this new release is causing the bug

### Minimal Reproduction

Temporal testing library: `@temporalio/testing@v1.1.0`
Docker image: `node:16-slim`

```javascript
import { TestWorkflowEnvironment } from '@temporalio/testing';

let testEnv;

beforeAll(async () => {
  testEnv = await TestWorkflowEnvironment.create();
});

afterAll(async () => {
  await testEnv.teardown();
});

describe('Test workflow', () => {
  test('test', async () => {
    expect(testEnv).toBeInstanceOf(TestWorkflowEnvironment);
  });
});

```

### Additional context
Works on macOS

### EDIT

This setup did work previously so I believe the issue stems from the fact there have been a new test-server release and it is not pinned in the testing lib

**Comment by bergundy** [comment]
Looks like you're using an old version of the SDK, this shouldn't happen since 1.3.0: https://github.com/temporalio/sdk-typescript/blob/main/CHANGELOG.md#130---2022-09-20.

I'm closing this issue.
If you encounter it after upgrading, please reopen.
