### ISSUE TITLE
[Bug] Silent crashes when awaiting promises returned from `Client` (using `hello-world` sample)

### ISSUE THREAD

**Issue by yamen** [temporalio/sdk-typescript#1033]
### What are you really trying to do?

Trying to run `npm run workflow` inside the `hello-world` app created using `npx @temporalio/create@latest`.

Also found this issue at other times, but this was the simplest way of replicating it.

### Describe the bug

All examples use the `hello-world` project as a baseline.

In a client side script that gets a workflow handle, awaiting on operations that return a Promise can silently crash the script:

``` javascript
  // console.log is never run, process just silently exits
  const handle = await client.workflow.start(example, {
    args: ['Temporal'],
    taskQueue: 'hello-world',
    workflowId: 'workflow-' + nanoid(),
  });

  console.log(Date.now());
```

Removing the `await` on the Promise (and sleeping to allow the relevant calls to finish without exiting the script) works just fine.

```javascript
    // console.log runs now
   const handle = client.workflow.start(example, {
    args: ['Temporal'],
    taskQueue: 'hello-world',
    workflowId: 'workflow-' + nanoid(),
  });

  await new Promise((resolve) => setTimeout(resolve, 100));

  console.log(Date.now());
```

Awaiting on the returned Promise _indirectly_ (via say a `Promise.all`) also works:

```javascript
  // console.log runs here too
  const handle = client.workflow.start(example, {
    args: ['Temporal'],
    taskQueue: 'hello-world',
    workflowId: 'workflow-' + nanoid(),
  });

  await Promise.all([handle, new Promise((resolve) => setTimeout(resolve, 100))]);

  console.log(Date.now());
```

### Minimal Reproduction

As per above, the current `hello-world` example should fail 'as is'. See above steps for 'fixing' it by awaiting indirectly with a sleep (or other promise).

### Environment/Versions

This has been validated in at least two very different environments (Windows WSL and Mac):

- Both Windows WSL2 running Ubuntu 22.04 and an M1 Mac
- SDK 1.5.2
- Both Temporalite and Docker Compose tried
- Both Node 16.x and Node 18.x

### Additional context

* When stepping through with a debugger, it seems a different code path is executed based on whether `await` is called directly on the Promise or not.
* Attaching some process exit hooks and debug logging will show that the process will hard exit as soon as the `Client` call is made and returns. Adding a delay to this exit will allow it to complete running.

```javascript
process.on('beforeExit', (code) => {
  console.log(`Process will exit in 1 second with code: ${code}`);
  setTimeout(() => {
    process.exit(code);
  }, 1000);
});

process.on('exit', (code) => {
  // Only synchronous calls
  console.log(`Process exited with code: ${code}`);
});
```

**Comment by bergundy** [comment]
I experienced the same issue with grpc-js 1.8.x, we're going to release a version that fixes `@grpc/grpc-js` to `~1.7.3`.
For now I recommend using that workaround.

**Comment by yamen** [comment]
I can confirm that this fixes the issue!

**Comment by yamen** [comment]
Seems related to this issue: https://github.com/grpc/grpc-node/issues/2318

* v1.7.3 works
* v1.8.4 works (but seems to hold a ref open)
* Any version works as long as there is some ref open in the script (eg calling `setInterval(() => {}, 1_000_000_000)` somewhere in the code)

**Comment by chadobado** [comment]
For those unfamiliar, you can work around this by adding an override to package.json:

```json
"overrides": {
    "@temporalio/client": {
      "@grpc/grpc-js": "1.7.3"
    }
  }
  ```

**Comment by yamen** [comment]
Seems to be fixed properly in 1.8.7 now.

**Comment by bergundy** [comment]
Thanks for pointing this out @yamen.
CC @mjameswh.

**Comment by mjameswh** [comment]
Closing as there is nothing more to be done on this ticket. Updating `@grpc/grpc-js` to 1.8.x is already tracked in #1023.
