### ISSUE TITLE
How to add module to disallowedModules?

### ISSUE THREAD

**Issue by gajus** [temporalio/sdk-typescript#1036]
We need to exclude a module from being bundled.

Contrary to the documentation, `ignoreModules` does not achieve that.

**Comment by bergundy** [comment]
Can you please provide more information why ignoreModules doesn't achieve what you want?
Here's what the bundler does internally FTR: https://github.com/temporalio/sdk-typescript/blob/31c8cc27287ec91e495397e85cd52a30c0d1236a/packages/worker/src/workflow/bundler.ts#L180.
Here's a test that successfully ignores `dns` https://github.com/temporalio/sdk-typescript/blob/31c8cc27287ec91e495397e85cd52a30c0d1236a/packages/test/src/test-bundler.ts#L60.

**Comment by gajus** [comment]
I've added `['slonik', 'node:crypto']` and still getting error:

```
2023-01-26T16:23:52.171Z [ERROR] ERROR in node:crypto
2023-01-26T16:23:52.171Z [ERROR] Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
2023-01-26T16:23:52.171Z [ERROR] Webpack supports "data:" and "file:" URIs by default.
2023-01-26T16:23:52.171Z [ERROR] You may need an additional plugin to handle "node:" URIs.
```

so it seems at least one of them is still being included

**Comment by gajus** [comment]
Actually, now that I look at the Temporal source code, there is no logic there to actually exclude module. It only adds a warning if it is not already excluded.

**Comment by gajus** [comment]
It seems that it attempts to exclude it using `alias`, which unfortunately does not work for modules such as `node:`

https://github.com/webpack/webpack/issues/14166

**Comment by bergundy** [comment]
LMK if removing the `node:` prefix solves your issue for now.

**Comment by gajus** [comment]
> LMK if removing the node: prefix solves your issue for now.

It does not, as explained in that webpack issue.

**Comment by gajus** [comment]
I have no control over `node:` referenced in code, as it is coming from dependencies.

**Comment by mjameswh** [comment]
The issue you are facing is not directly about ignoreModules. It is that the workflow bundler is not compiling for the node target, and therefore, webpack does not even know how to process dependencies in the node namespace.

Would it be possible for you to ignore the module that does import that node: dependency?

**Comment by gajus** [comment]
That's what I am trying to do with `externals`.

Anyway, overriding externals does the job.

```ts
// @see https://github.com/temporalio/sdk-typescript/issues/1036#issuecomment-1405322953
config.externals = {
  "node:crypto": "{}"
};
```

**Comment by gajus** [comment]
A backwards compatible way is:

```ts
const temporalExternals = config.externals;

config.externals = async (context, callback) => {
  if (context.request === 'node:crypto') {
    return 'var {}';
  }

  return temporalExternals(context, callback);
};

config.resolve.alias = {
  ...config.resolve.alias,
  '@': path.resolve(__dirname, '../..'),
  slonik: false,
};
```
