### ISSUE TITLE
[Bug] `sleep('1 month')` results in UnhandledCommand WFT failure

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#1046]
### What are you really trying to do?

Start and cancel a workflow that just calls an activity that sleeps.

### Describe the bug

WorkflowTaskFailed with message `UnhandledCommand`

### Minimal Reproduction

https://github.com/lorensr/workflow-statuses/blob/3b1d476fca708a8e1e98a711c9caa94e3da064cc/src/client.ts#L29-L35

![image](https://user-images.githubusercontent.com/251288/216097924-7fc2cb89-5d3b-4c39-a173-bd3f0637ec12.png)

**Comment by lorensr** [comment]
Issue was `ms('1 month')` returns `undefined`. Maybe we guard at runtime against undefined any place we support `ms` strings?

**Comment by bergundy** [comment]
Can you provide more info?
How do we reproduce this step by step?

**Comment by lorensr** [comment]
```
git clone https://github.com/lorensr/workflow-statuses.git
git checkout 3b1d476fca708a8e1e98a711c9caa94e3da064cc
npm i
npm start
npm run workflow
```

**Comment by mjameswh** [comment]
> Maybe we guard at runtime against undefined any place we support ms strings?

I'm very surprised that `ms` doesn't throw exception on strings that don't match expected pattern.

We can certainly ensure on our side that if someone actually passes a value that we then pass that value to `ms`, and `ms` return `undefined`, then we explicitly throw an error on this. We can also be more defensive in places where a value is mandatory, such as `sleep(x)`.

However, in most places where we expect `ms`-like values, that value is optional, so it is impossible for us to catch cases where a user did something like `condition(fn, ms('2 months'))`.
