### ISSUE TITLE
[Feature Request] Retain type information regarding signal/query `name`

### ISSUE THREAD

**Issue by josiah-roberts** [temporalio/sdk-typescript#1052]
### Is your feature request related to a problem? Please describe.

Everything here also applies to `QueryDefinition`, but I'll use `SignalDefinition` in these examples.

Because `SignalDefinition<Args>` does not retain the type of its `name`, it can be difficult to create broader systems that keep track of the legal signals and queries that can be sent to a workflow. 

For example:
```typescript
const signalA = defineSignal<[string]>('a');
const signalB = defineSignal<[string]>('b');

export function myWorkflow() {
  ... use these signals
}

// This doesn't work: these are just SignalDefinition<[string]>
// it matches *any* SignalDefinition<[string]>, not just 'a' and 'b'
export type SupportedSignals = typeof signalA | typeof signalB;

// This also doesn't work: SignalDefinition<_Args>['name'] is typed as string
export type SupportedSignalNames = typeof signalA.name | typeof signalB.name;
```

As a result, there is no straightforward way to define within the type system what the legal queries/signals to send to a workflow are. We can use proximity ("this signal was exported by the same module as the workflow, it probably makes sense to send it"), but we can't create structures that have `tsc` enforce this for us.

### Describe the solution you'd like

This issue can be fixed by varying the type of `name` with the type of the passed in string.

`SignalDefinition` becomes:
```typescript
export interface SignalDefinition<Args extends any[] = [], Name extends string = string> {
  type: 'signal';
  name: Name;
}
```

This presents some challenges for the definition of `defineSignal` though. You can't have partially-inferred generics in typescript, so we are forced to specify the name on both a type and a value level
```typescript
export function defineSignal<Name extends string, Args extends any[] = []>(name: Name): SignalDefinition<Args, Name> {
  return {
    type: 'signal',
    name,
  };
}

// Annoying to have to specify 'some name' twice
const stringSignal = defineSignal<'some-name', [string]>('some-name');
```

A curried alternative removes the duplication, though with a slightly unfamiliar style. This would be my preference.
```typescript
function defineNamedSignal<Name extends string>(name: Name): <Args extends any[]>() => SignalDefinition<Args, Name> {
  return () => ({
    type: 'signal',
    name,
  })
}

defineNamedSignal('some-name')<[string]>();
```

Finally, we could also make this level of specificity opt-in, so that only consumers who care to reason about names on a type-level pay the cost for it:

```typescript
export function defineSignal<Args extends any[] = [], Name extends string = string>(name: Name): SignalDefinition<Args, Name> {
  return {
    type: 'signal',
    name,
  };
}

// Retains old behavior where the resulting name is of type string
const stringSignal = defineSignal<[string]>('some-name');

// Allows being more specific
const stringSignal = defineSignal<[string], 'some-name'>('some-name');
```

Either way, after this change it becomes possible to reason about the names of signals on a type level, tell them apart, and apply logic to them.

**Comment by mjameswh** [comment]
Fixed in #1056.
