### ISSUE TITLE
[Feature Request] Propagate opentelemetry context to local activities

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#1057]
Currently missing, only non-local activities and child workflows traces are attached to the workflow's span.

**Comment by mjameswh** [comment]
This is no longer pertinent, since SDK tracing support is being removed.

**Comment by bergundy** [comment]
> This is no longer pertinent, since SDK tracing support is being removed.

Note this is true for internal SDK traces, not user traces. I reopened this issue.
