### ISSUE TITLE
[Bug] Temporal does not use standard AbortController/AbortSignal typings

### ISSUE THREAD

**Issue by knpwrs** [temporalio/sdk-typescript#1063]
### What are you really trying to do?

I am trying to pass `Context.current().cancellationSignal` to [`execa`](https://github.com/sindresorhus/execa) so child processes can be automatically killed when a workflow is cancelled.

### Describe the bug

TypeScript is not happy:

```
Argument of type 'import("/.../node_modules/abort-controller/dist/abort-controller").AbortSignal' is not assignable to parameter of type 'AbortSignal'.
Type 'AbortSignal' is missing the following properties from type 'AbortSignal': reason, throwIfAborted
```

Execa expects a standard library `AbortSignal` and Temporal is using a third-party `AbortSignal`.

### Additional context

I saw that ceab74d9d608a0f808cd2a9f63012064800f5044 introduced the `abort-controller` dependency for compatibility with Node 14 as `AbortController` was introduced in Node 15. Does the SDK have any official support policy? There have been two LTS releases since Node 14 (Node 16 and Node 18), both of which support AbortController. Can we just drop the `abort-controller` dependency and use the standard library?

**Comment by bergundy** [comment]
Thanks for reporting, I wasn't aware of the type incompatibility.

I'd have to think about this a bit more and test it out, but my current inclination is to keep the dependency as a polyfill for Node 14 and rely on the Node 16 types when exporting. We may have to manually add the `throwIfAborted` method to the objects we create.

**Comment by mjameswh** [comment]
It seems like we can import `abort-controller/polyfill` instead, which will return the native implementation if there is one. I'll do some experiment with this.
