### ISSUE TITLE
[Feature Request] Support countWorkflowExecutions

### ISSUE THREAD

**Issue by jdnichollsc** [temporalio/sdk-typescript#1069]
### Is your feature request related to a problem? Please describe.

I'm trying to check if a workflow execution exists by using the workflowId.

### Describe the solution you'd like

I was checking the types from the TypeScript packages and I was trying to implement the below solution:
```ts
async checkWorkflowExecutionExists(workflowId: string): Promise<boolean> {
  const request = new temporal.api.workflowservice.v1.DescribeWorkflowExecutionRequest({
    execution: new temporal.api.common.v1.WorkflowExecution({ workflowId }),
    namespace: 'default',
  });
  const { count } = await this.client.workflowService.countWorkflowExecutions(request);
  return count.greaterThan(0);
}
```

### Additional context

But I'm getting this error:
```
│ [Nest] 40  - 03/02/2023, 10:15:15 PM   ERROR [ExceptionsHandler] proto_1.temporal.api.workflowservice.v1.D │
│ TypeError: proto_1.temporal.api.workflowservice.v1.DescribeWorkflowExecutionRequest is not a constructor   │
│     at CheckoutService.checkWorkflowExecutionExists (/baxus-services/dist/apps/api/main.js:2066:25)        │
│     at CheckoutController.checkWorkflowExecutionExists (/baxus-services/dist/apps/api/main.js:1889:37)     │
│     at /baxus-services/node_modules/@nestjs/core/router/router-execution-context.js:38:29                  │
│     at processTicksAndRejections (node:internal/process/task_queues:96:5)                                  │
│     at /baxus-services/node_modules/@nestjs/core/router/router-execution-context.js:46:28                  │
│     at /baxus-services/node_modules/@nestjs/core/router/router-proxy.js:9:17  
```

I was inspecting the code of the '@temporalio/proto' package but I don't see any reference to that `DescribeWorkflowExecutionRequest` constructor, so why the types are wrong?

Thanks for your support! <3

**Comment by mjameswh** [comment]
`countWorkflowExecutions` is an operation against the visiblity API (ie. going to your ElasticSearch server, and it might possibly take to time to reflect a result). A better way to test for the existence of a specific workflow would be `client.getHandle(workflowId).describe()`.

**Comment by mjameswh** [comment]
Also, we do not yet provide a high level API for the `countWorkflowExecutions` operation, but we do for the `listWorkflowExecutions`:

```
  for await (const workflowInfo of client.workflow.list({ query: 'WorkflowId="MyWorkflowId"' })) {
    console.log(`${workflowInfo.workflowId} ${workflowInfo.runId}`);
  }
```

Note that both `listWorkflowExecutions` and `countWorkflowExecutions` are based on search queries. They are generally meant to find a list of workflows, not a single workflow.

If you still want to use the `countWorkflowExecutions` operation, you can do so through the raw gRPC API. The syntax for this would be:

```ts
    const response = await client.workflow.workflowService.countWorkflowExecutions({
      namespace: this.options.namespace,
      query: "WorkflowId = 'test'",
    });
    const count = response.count;
```

**Comment by bergundy** [comment]
We could add an abstraction for this, couldn't hurt.

**Comment by jdnichollsc** [comment]
> client.workflow.

I was checking the types and I don't see any workflow object from the client:
![workflow client](https://user-images.githubusercontent.com/2154886/222584041-94841bd8-dc82-4814-80d8-baa9a2d5a0ee.png)

Let me try that gRPC API, is that a good solution or do you recommend any other alternative? <3

Thanks for your amazing support folks!

**Comment by mjameswh** [comment]
From your screenshot, it looks like you already have a `WorkflowClient`, so that would be `this.client.getHandle(workflowId).describe()` or `this.client.workflowService.countWorkflowExecutions`.

**Comment by jdnichollsc** [comment]
> Also, we do not yet provide a high level API for the `countWorkflowExecutions` operation, but we do for the `listWorkflowExecutions`:
> 
> ```
>   for await (const workflowInfo of client.workflow.list({ query: 'WorkflowId="MyWorkflowId"' })) {
>     console.log(`${workflowInfo.workflowId} ${workflowInfo.runId}`);
>   }
> ```
> 
> Note that both `listWorkflowExecutions` and `countWorkflowExecutions` are based on search queries. They are generally meant to find a list of workflows, not a single workflow.
> 
> If you still want to use the `countWorkflowExecutions` operation, you can do so through the raw gRPC API. The syntax for this would be:
> 
> ```ts
>     const response = await client.workflow.workflowService.countWorkflowExecutions({
>       namespace: this.options.namespace,
>       query: "WorkflowId = 'test'",
>     });
>     const count = response.count;
> ```

Oh I'm getting this other error:
```sh
> │ [Nest] 60  - 03/02/2023, 11:19:44 PM   ERROR [ExceptionsHandler] 3 INVALID_ARGUMENT: Operation not support │
│ Error: 3 INVALID_ARGUMENT: Operation not supported. Please use on Elasticsearch                            │
│     at Object.callErrorFromStatus (/baxus-services/node_modules/@grpc/grpc-js/src/call.ts:81:17)           │
│     at Object.onReceiveStatus (/baxus-services/node_modules/@grpc/grpc-js/src/client.ts:358:36)            │
│     at /baxus-services/node_modules/@grpc/grpc-js/src/call-stream.ts:210:27                                │
│     at onReceiveStatus (/baxus-services/node_modules/@temporalio/client/src/grpc-retry.ts:176:17)          │
│     at Object.onReceiveStatus (/baxus-services/node_modules/@temporalio/client/src/grpc-retry.ts:180:13)   │
│     at InterceptingListenerImpl.onReceiveStatus (/baxus-services/node_modules/@grpc/grpc-js/src/call-strea │
│     at Object.onReceiveStatus (/baxus-services/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:3 │
│     at Object.onReceiveStatus (/baxus-services/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:4 │
│     at /baxus-services/node_modules/@grpc/grpc-js/src/call-stream.ts:334:24                                │
│     at processTicksAndRejections (node:internal/process/task_queues:78:11)                                 │
│ for call at                                                                                                │
│     at ServiceClientImpl.makeUnaryRequest (/baxus-services/node_modules/@grpc/grpc-js/src/client.ts:328:30 │
│     at Service.rpcImpl (/baxus-services/node_modules/@temporalio/client/src/connection.ts:340:21)          │
│     at Service.rpcCall (/baxus-services/node_modules/protobufjs/src/rpc/service.js:94:21)                  │
│     at executor (/baxus-services/node_modules/@protobufjs/aspromise/index.js:44:16)                        │
│     at new Promise (<anonymous>)                                                                           │
│     at Object.asPromise (/baxus-services/node_modules/@protobufjs/aspromise/index.js:28:12)                │
│     at Service.rpcCall (/baxus-services/node_modules/protobufjs/src/rpc/service.js:86:21)                  │
│     at Service.countWorkflowExecutions (eval at Codegen (/baxus-services/node_modules/@protobufjs/codegen/ │
│     at CheckoutService.checkWorkflowExecutionExists (/baxus-services/dist/apps/api/main.js:2065:61)        │
│     at CheckoutController.checkWorkflowExecutionExists (/baxus-services/dist/apps/api/main.js:1889:37)  
```

Let me try the other alternatives!

**Comment by jdnichollsc** [comment]
> * this.client.getHandle(workflowId).describe()

This is working great, thanks for your help! :tada: 

About the implementation to validate if a workflow is running with this SDK, is this Ok?

```ts
async checkIfWorkflowExecutionIsRunning(workflowId: string): Promise<boolean> {
  try {
    const { status } = await this.client.getHandle(workflowId).describe();
    return (
      status.code === temporal.api.enums.v1.WorkflowExecutionStatus.WORKFLOW_EXECUTION_STATUS_RUNNING ||
      status.code === temporal.api.enums.v1.WorkflowExecutionStatus.WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW
    );
  } catch (error) {
    this.logger.error(`checkIfWorkflowExecutionIsRunning(${workflowId})`, error);
    if (error instanceof WorkflowNotFoundError) {
      return false;
    }
    throw error;
  }
}

```

Thanks folks!

**Comment by mjameswh** [comment]
Checking for status code `WORKFLOW_EXECUTION_STATUS_RUNNING` should be enough.

If the workflow continued as new, then `getHandle(workflowId)` (without a `runId`) should have returned the continuation workflow, which will be "running", rather than the original workflow, which will have status "continued as new".

**Comment by jdnichollsc** [comment]
@mjameswh Beautiful, thanks James for your amazing feedback! <3

You save my day, have a great day folks :+1:

**Comment by nikhilbhatia08** [comment]
@mjameswh I would like to give this a try.
