### ISSUE TITLE
instanceof not working

### ISSUE THREAD

**Issue by leran500** [temporalio/sdk-typescript#1083]
HI
 i am using javascript/typedscript instanceof inside a workflow, and its fail everytime.
my workflow code:

const fileEntity: FileEntity | ActivityError = await getFileData(fileId);
if (fileEntity instanceof ActivityError) {
  return fileEntity;
}

the if statment fails, but if I apply the condition  inside the activity (getFileData) before returning the result it won't fail,
I checked the type of the activity result using typeof and it returned object every time.
i cant understand what I am doing wrong.

**Comment by bergundy** [comment]
Activity errors are wrapped on the workflow side.
You should be able to catch an ActivityFailure with cause set to ApplicationFailure with the type of the original exception thrown in the activity.

See this doc for more info https://legacy-documentation-sdks.temporal.io/typescript/handling-failure#activityfailure
