### ISSUE TITLE
[Bug] `.cancel()` does not exists on child workflow handles

### ISSUE THREAD

**Issue by laura-turner-divvy** [temporalio/sdk-typescript#1114]
### What are you really trying to do?

I am creating a child workflow as part of my workflow. In certain situations, I need to cancel the child workflow.

### Describe the bug

Creating a child workflow using `startChild` yields a `ChildWorkflowHandle<T>`, which says in the JSDoc "can be used to signal, wait for completion, and cancel a Workflow execution." However, there is no `cancel()` method on the `ChildWorkflowHandle` like there is for a `WorkflowHandle<T>` created via `client.workflow.getHandle(workflowId)`.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/114932945/235768266-ba61bb63-89f2-409b-9928-4911e12d04ae.png">

### Minimal Reproduction

Create a child workflow via `await startChild(...)`. Attempt to cancel the workflow via `.cancel()`.

### Environment/Versions

- Temporal Version: `@temporalio/workflow` `1.7.2`

### Additional context

[Relevant Slack conversation](https://temporalio.slack.com/archives/C01DKSMU94L/p1683053747688419)

**Comment by lorensr** [comment]
Agree that would be nice! Tracking here: #740
