### ISSUE TITLE
[Bug] @temporalio/create produces unbuildable hello-world project

### ISSUE THREAD

**Issue by cameronpickham** [temporalio/sdk-typescript#1116]
### What are you really trying to do?

I would like to set up a hello-world application following the instructions [here](https://learn.temporal.io/getting_started/typescript/dev_environment/)

### Describe the bug

Project fails to build. The created hello-world project is configured to use TypeScript `^4.4.2` but this is incompatible with the supplied version of `tsconfig/node20` due to its usage of `es2023` in the `lib` configuration. I believe this requires TypeScript >= 5.

### Minimal Reproduction

Create the hello-world application with `npx @temporalio/create@latest ./my-app` and then attempt to run using `npm run start.watch`

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: temporal version 0.8.0 (server 1.20.1) (ui 2.13.3)
- Are you using Docker or Kubernetes or building Temporal from source? Temporal installed via Homebrew

- Node: v20.0.0

**Comment by bergundy** [comment]
Thanks for reporting, we're still working on officially supporting node 20.
CC @mjameswh

**Comment by bergundy** [comment]
Closing in favor of https://github.com/temporalio/sdk-typescript/issues/1125
