### ISSUE TITLE
[Bug] tsc in a project created with `npx @temporalio/create` fails on Node 20

### ISSUE THREAD

**Issue by josh-berry** [temporalio/sdk-typescript#1125]
### What are you really trying to do?

Trying to create a new project based on the `child-workflow` sample, following the directions at: https://docs.temporal.io/dev-guide/typescript/foundations#install-a-temporal-sdk

### Describe the bug

TypeScript compilation fails in an unmodified new project, based on the `child-workflow` sample, because the `es2023` library definitions are not included with the version of TypeScript used in the sample project:

```
❯ npm run start.watch
...
TSError: ⨯ Unable to compile TypeScript:
node_modules/@tsconfig/node20/tsconfig.json:6:13 - error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', [...]

6     "lib": ["es2023"],
              ~~~~~~~~
...
[nodemon] app crashed - waiting for file changes before starting...
```

### Minimal Reproduction

1. `npx @temporalio/create@latest sample-tsc-fail-repro`
2. Choose the `child-workflows` sample and accept the defaults for the rest of the prompts
3. In a new terminal, `temporal server start-dev`
4. `cd sample-tsc-fail-repro`
5. `npm run start.watch`
6. Observe the crash above

### Environment/Versions

- OS and processor: M1 Mac, macOS 13.4
- Temporal Version: `temporal version 0.9.0 (server 1.20.2) (ui 2.15.0)`
- Are you using Docker or Kubernetes or building Temporal from source? No
- Node Version: `v20.2.0`

### Additional context

I doubt this is specific to the `child-workflows` sample; I suspect the others suffer from the same issue (though I haven't tried).

I notice the `es2023` lib reference comes from the `tsconfig.json` included in `@tsconfig/node20`. If I look at the sample itself, I see that its `package.json` uses `@tsconfig/node16` (which presumably does not have the `es2023` lib reference). So it seems `@temporalio/create` is tweaking the `package.json` to use `node20` (which is the version I have installed). And indeed I can see this in the code: https://github.com/temporalio/sdk-typescript/blob/1709d45c5e649fd6b233243b7a80c49be5e706bd/packages/create-project/src/helpers/install.ts#L33

Also, the sample's `package.json` pins TypeScript to a 4.x release, and I don't think `es2023` is defined until 5.0.

I think there might be two ways of fixing this:
1. Bump the TypeScript version (and related dependencies) to TypeScript 5.x in all the samples
2. Stop messing with the `@tsconfig/nodeXX` version when creating the new package

It might be a good idea to do both, in any case. Staying up to date (i.e. (1)) is always good, and my thinking re. (2) is that people may be developing on the latest version of Node (currently, v20), but may want to use an LTS release (currently, v18) when deploying. So it may not necessarily make sense to depend on the current Node version in a new project.

**Comment by bergundy** [comment]
Thanks @josh-berry for the report.
This was already reported but your issue contains more info so I'll close the original.

**Comment by mjameswh** [comment]
Lol! I already have a fix for this on my local branch, together with a few other minor fixes 😄 Pushing in a few minutes.
