### ISSUE TITLE
Temporal SDK Changes how javascript is being executed

### ISSUE THREAD

**Issue by tareksalem** [temporalio/sdk-typescript#1127]
### What are you really trying to do?
This is not an actual bug

I am using a simple activity like this:

```typescript
export async function greet(name: string): Promise<string> {
  return Promise.reject('www')
}
```

and this is the workflow

```typescript

/** A workflow that simply calls an activity */
export async function example(name: string): Promise<string> {
  try {
    console.log("============= entered try")
    return await greet(name);
  } catch (err) {
    console.log('============= entered the failure catch');
    throw ApplicationFailure.nonRetryable("====================== failed to get name");
  }
}
```
I want to throw the application failure from the workflow itself if the activity failed, not from the activity function

### Describe the bug
In normal javascript code, when I return a rejection from a promise function and call that function in a try-catch block, its expected to catch the error and do whatever logic should be done inside that catch block, but this is not the case with temporal SDK, if I return a rejection from the promise and call it inside try-catch block inside the workflow it doesn't call the catch block and it causes the workflow to be retried which is not the wanted behavior.

#### Why do I want to do that?
for me activities are functions and I want  to make them pure functions for testability and extendability, so I don't want the activities function to know anything about the temporal application failure and not take the decision regarding to which error should be thrown
I think the workflow itself should have that logic so I want to put the activities that might return a failure to put them inside a try catch block inside the workflow and in the catch block decide which type of failure should be thrown

Is something like this doable?

Also, I didn't find something in the documentation explaining this, is there a resource that explains this in detail?

Thanks.

**Comment by bergundy** [comment]
Activities are retired indefinitely by default unless they throw an error that's specified in the non retryable types in the retry policy or they throw a non retryable application failure.
This is typically what you want because activities interact with unreliable systems and Temporal ensures they run to completion.
Retrying from the workflow is far more expensive in terms of compute and storage operations so we generally do not recommend that approach.

This page covers what you need to know about activities conceptually: https://docs.temporal.io/activities

**Comment by tareksalem** [comment]
@bergundy why throwing errors from the workflow is more expensive?

what If I want to make the decision of retrying or not from outside the activity?

**Comment by lorensr** [comment]
If you need to decide whether to retry from the workflow, you can throw a
non-retryable error from the Activity:

`throw ApplicationFailure.create({ message: 'foo', nonRetryable: true })`

More info:

https://docs.temporal.io/kb/failures
