### ISSUE TITLE
[Bug] Client.schedule.create is giving "Schedule not found" error if namespace is incorrect

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-typescript#1145]
### Describe the bug

Using a schedule client configured with a namespace that doesn't exist, trying to create a new schedule results in a "Schedule not found" exception, rather than something like "Namespace not found".

Very similar errors probably exists elsewhere on ScheduleClient and WorkflowClient.

**Comment by bergundy** [comment]
See also https://github.com/temporalio/sdk-typescript/issues/976 and the comment suggesting how it should be fixed.
