### ISSUE TITLE
[Support] How to cache data between different interceptors

### ISSUE THREAD

**Issue by YufeeXing** [temporalio/sdk-typescript#1149]
The situation is: We want to authenticate the values in the grpc header. The local activity is used here in the interceptor to get env variables like authentication URL and send the values in the header to the URL to authenticate. 
But how to cache these user headers if there are more than one interceptors and we want to get the cache in other interceptors. Like something in Java is thread local storage.

**Comment by YufeeXing** [comment]
In summary, Is there any way to store data in workflow execution context? Then the data can be used in different child workflows, activities.

**Comment by bergundy** [comment]
You can store data either in the global scope, which is *not* shared between workflow instances. Or using the workflow's `AsyncLocalStorage`, or just in the closure where you instantiate the interceptors.
Note that you should avoid storing sensitive information in headers as they are not encrypted by default (yet).

**Comment by bergundy** [comment]
Here's how we use AsyncLocalStorage for implementing the opentelemetry interceptors: https://github.com/temporalio/sdk-typescript/blob/aec754c1d81520752d0c86d6a025348835c77959/packages/interceptors-opentelemetry/src/workflow/context-manager.ts#L2

**Comment by YufeeXing** [comment]
> Here's how we use AsyncLocalStorage for implementing the opentelemetry interceptors:
> 
> https://github.com/temporalio/sdk-typescript/blob/aec754c1d81520752d0c86d6a025348835c77959/packages/interceptors-opentelemetry/src/workflow/context-manager.ts#L2

Thanks for your help, @bergundy. Your reply is very helpful.
I am using https://www.npmjs.com/package/continuation-local-storage to act as a storage like AsyncLocalStorage.
Hope this can work, too.

**Comment by bergundy** [comment]
continuation-local-storage is outdated so I would not use it at all and in any case it will not work from the workflow context.

**Comment by YufeeXing** [comment]
> continuation-local-storage is outdated so I would not use it at all and in any case it will not work from the workflow context.

I copied the context-manager.ts and export a new ContextManager() to get a instance
`export default new ContextManager();`
But got a strange error:
![image](https://github.com/temporalio/sdk-typescript/assets/42690790/fd662bc5-8c7a-4564-ab43-2869564d8b4d)

**Comment by bergundy** [comment]
Can you post a full reproduction?

**Comment by bergundy** [comment]
Are you using this in workflow context?

**Comment by YufeeXing** [comment]
> Are you using this in workflow context?

Yes, in workflow context. I used it like this:
1. Just copy the context-manager.ts, but export a default instance of it
```
import * as otel from '@opentelemetry/api';
import { AsyncLocalStorage } from '@temporalio/workflow';

export class ContextManager implements otel.ContextManager {
  protected storage = new AsyncLocalStorage<otel.Context>();

  active(): otel.Context {
    return this.storage.getStore() || otel.ROOT_CONTEXT;
  }

  bind<T>(context: otel.Context, target: T): T {
    if (typeof target !== 'function') {
      throw new TypeError(`Only function binding is supported, got ${typeof target}`);
    }

    // Stolen from https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-context-async-hooks/src/AbstractAsyncHooksContextManager.ts
    const contextWrapper = (...args: unknown[]) => {
      return this.with(context, () => target.apply(this, args));
    };
    Object.defineProperty(contextWrapper, 'length', {
      enumerable: false,
      configurable: true,
      writable: false,
      value: target.length,
    });
    /**
     * It isn't possible to tell Typescript that contextWrapper is the same as T
     * so we forced to cast as any here.
     */
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return contextWrapper as any;
  }

  enable(): this {
    return this;
  }

  disable(): this {
    this.storage.disable();
    return this;
  }

  with<A extends unknown[], F extends (...args: A) => ReturnType<F>>(
    context: otel.Context,
    fn: F,
    thisArg?: ThisParameterType<F>,
    ...args: A
  ): ReturnType<F> {
    const cb = thisArg == null ? fn : fn.bind(thisArg);
    return this.storage.run(context, cb, ...args);
  }
}
export default new ContextManager()
```

Then in a workflow activity file, the instance is imported and used like this:
```
import contextmanager from './contextmanager';

async function _activity1(headers: Headers): Promise<string> {
}

async function _activity2(headers: Headers): Promise<string> {
}

const localContext = contextmanager.active || {};
const activity1= contextmanager.bind(localContext, _activity1);
const activity2 = contextmanager.bind(localContext, _activity2);

export { activity1, activity2 }
```
Then got the error.
