### ISSUE TITLE
[Support] Activating a workflow causes "Automatic publicPath is not supported in this browser" (error when using node but not node-ts)

### ISSUE THREAD

**Issue by doodledood** [temporalio/sdk-typescript#1175]
### What are you really trying to do?

Trying to execute a workflow from a client (worked in the past).

### Describe the bug

The worker is set up this way:
`
    const worker = await Worker.create({
        connection,
        workflowsPath: require.resolve('./workflows'),
        activities: createActivities(someDep),
        taskQueue: 'test-queue',
        bundlerOptions: {
            ignoreModules: ['./logger'],
        },
        // Inject sinks
        sinks: defaultSinks(workflowLogger)
    });
`

The client launches the workflow. The worker picks it up, but then immediately fails with this error: 

`
[ERROR] Failed to activate workflow {
[worker]   runId: 'e0a7da3f-dde2-4d20-9b79-0d5eefbfc137',
[worker]   error: /usr/src/app/workflow-bundle-e081d7d12c0bb7760cad.js:27106
[worker]   /******/             if (!scriptUrl) throw new Error("Automatic publicPath is not supported in this browser");
[worker]                                        ^
[worker]
[worker]   Error: Automatic publicPath is not supported in this browser
[worker]       at webpack/runtime/publicPath:17:0
[worker]       at null:null:null
[worker]       at null:null:null
[worker]       at Script.runInContext (node:vm:141:12)
[worker]       at VMWorkflowCreator.getContext (/usr/src/app/node_modules/@temporalio/worker/lib/workflow/vm.js:63:21)
[worker]       at VMWorkflowCreator.createWorkflow (/usr/src/app/node_modules/@temporalio/worker/lib/workflow/vm.js:32:36)
[worker]       at handleRequest (/usr/src/app/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:42:35)
[worker]       at MessagePort.<anonymous> (/usr/src/app/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:83:38)
[worker]       at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
[worker]       at exports.emitMessage (node:internal/per_context/messageport:23:28),
[worker]   workflowExists: false
[worker] }
`

I noticed this happens when I try to run the `worker.js` using `node dist/worker.js` after building the typescript files. However, it does work correctly when using `ts-node` like `ts-node src/worker.ts`

### Minimal Reproduction

Launch a Kubernetes cluster with Temporal set up and a worker.
Start a workflow with `await client.workflow.start(` from a client.
Watch the worker; it raises the previous error.

### Environment/Versions

- Windows 10 x86
- Docker Desktop + Minikube (Kubernetes setup)
- Temporal version 1.21.1 (auto-setup) docker image

**Comment by mjameswh** [comment]
Your Workflow code is somehow importing an NPM package that uses Webpack's automatic `publicPath` feature. That feature only makes sense in a web app (ie. that package should be imported from web UI code, not from backend code). The error message is produced by the imported library itself, not by the Temporal SDK.

Review your Workflow's imports for anything that should not be there. You may also try to inspect your generated workflow bundle (`/usr/src/app/workflow-bundle-e081d7d12c0bb7760cad.js`, at line 27106) to find out exactly which package is causing that error, then try to figure out why is that library getting imported from your workflow code.

**Comment by mjameswh** [comment]
@doodledood I'm closing this ticket, as there is nothing to do on our side.

Feel free to continue the discussion if you still need help. You may also get help through our [Slack community](https://t.mp/slack) or our [community forum](https://community.temporal.io/).

**Comment by 0xBigBoss** [comment]
Just came to say for others encountering this. I am running my workers using `ts-node` for now, this was due to `@supabase/supabase-js` importing `@supabase/node-fetch/browser`. The fix for me at least was to pass a custom bundle option to ignore the troublesome package. YMMV

```ts
  const worker = await Worker.create({
    workflowsPath: fileURLToPath(workflowsPathUrl),
    activities,
    taskQueue: 'dev',
    bundlerOptions: {
      ignoreModules: ['@supabase/supabase-js'],
    },
  })
```
