### ISSUE TITLE
[Feature Request] Workflow rollback

### ISSUE THREAD

**Issue by burakakca** [temporalio/sdk-typescript#1197]
### Describe the solution you'd like

We can persist the workflow events and also there an event history, How about rollback the history of a given step?

When we do that, the workflow gonna act like undo event

**Comment by lorensr** [comment]
Normally rollback is done via try/catch in your workflow code. Does that meet your use case? 

If you're talking about [reset](https://docs.temporal.io/workflows#reset), you can do that via the CLI:

https://docs.temporal.io/cli/workflow#reset

Are you wanting a programmatic way to do it, like `workflowHandle.reset(eventId)`?

**Comment by burakakca** [comment]
It could be good use a programmatic way but I'm not sure what you're talking about, this is like start from beginning right? all you do is erased and you go back to the beginning.

What I'm talking about is getting back to the previous history state so that history can be reverted step by step.

**Comment by bergundy** [comment]
@burakakca from our docs:

> A Reset terminates a [Workflow Execution](https://docs.temporal.io/workflows#workflow-execution), removes the progress in the [Event History](https://docs.temporal.io/workflows#event-history) up to the reset point, and then creates a new Workflow Execution with the same [Workflow Type](https://docs.temporal.io/workflows#workflow-type) and [Id](https://docs.temporal.io/workflows#workflow-id) to continue.

We generally recommend using it as a last resort to recover from specific situations.
It is much more preferable coding and handling rollback in workflow code where you have access to the full execution context.

**Comment by bergundy** [comment]
Closing as there are a couple of existing suggested approaches. Please reopen if you feel like this is unresolved.
