### ISSUE TITLE
TransportError: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })))

### ISSUE THREAD

**Issue by xencodes** [temporalio/sdk-typescript#1273]
## Expected Behavior
It should be able to run the worker within a docker container.

## Actual Behavior
It's always throwing the following error when I try to start workers within a Docker container. It works when I manually shell into the container and manually run `node worker.js`.

```js
❯ docker run my-app
TransportError: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })))
    at NativeConnection.connect (/app/node_modules/.pnpm/@temporalio+worker@1.8.4_esbuild@0.19.5/node_modules/@temporalio/worker/lib/connection.js:55:23)
```

## Steps to Reproduce the Problem

  1. Create a worker
  2. Start the worker

## Specifications

  - Version: Latest
  - Platform: Mac M1 Pro

**Comment by mjameswh** [comment]
@xencodes Can you please share all of the following:
- Your `NativeConnection`'s options;
- Your `Worker`'s options;
- The Dockerfile of that container.

**Comment by mjameswh** [comment]
Closing due to OP inactivity. Please reopen if this is still pertinent, or consider other support channel, such as [our community forum](https://community.temporal.io/) or [Slack workspace](https://t.mp/slack).
