### ISSUE TITLE
[Feature Request] Add NativeClient keep alive support

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-typescript#1275]
### Describe the solution you'd like

Already enabled by default in latest SDK core, just need to expose the options from https://github.com/temporalio/sdk-core/issues/585

**Comment by bergundy** [comment]
This doesn’t apply to the worker imho as the long polls are a replacement for keep alive.

I would close and not implement this for NativeConnection.

**Comment by mjameswh** [comment]
> I would close and not implement this for NativeConnection.

Closing.
