### ISSUE TITLE
[Bug] Custom payload converter not being passed to "Activator"

### ISSUE THREAD

**Issue by nohehf** [temporalio/sdk-typescript#1291]
### What are you really trying to do?

Using a custom payload converter in a temporal typescript worker.

### Describe the bug

After implementing and loading a custom payload converter in a typescript worker, it is being used as expected to start my workflow (I get logs and I can confirm it's working as expected). Still, when the activity resolves I get a `Failed to activate workflow` error.
The error being:
```
2023-11-14T12:50:06.988Z [ERROR] Failed to activate workflow {
  namespace: 'default',
  taskQueue: 'my-task-queue',
  workflowId: 'worflowId',
  runId: '8c924e14-1c20-4c38-a490-50e4f1c6ac6d',
  workflowType: 'MyWorkflowType',
  error: **************/workflow-bundle-66b7a6885e00fd3df11b.js:438
              throw new errors_1.ValueError(`Unknown encoding: ${encoding}`);
              ^

  ValueError: Unknown encoding: custom/encoding
      at DefaultPayloadConverter.fromPayload (*******/node_modules/@temporalio/common/src/converter/payload-converter.ts:163:12)
      at Activator.resolveActivity (*******/node_modules/@temporalio/workflow/src/internals.ts:411:62)
      at *******/node_modules/@temporalio/workflow/src/worker-interface.ts:215:29
      at Object.activate (*******/node_modules/@temporalio/workflow/src/worker-interface.ts:221:2)
      at evalmachine.<anonymous>:1:18
      at Script.runInContext (node:vm:134:12)
      at Object.runInContext (node:vm:282:6)
      at Proxy.<anonymous> (*******/node_modules/@temporalio/worker/lib/workflow/vm.js:40:46)
      at VMWorkflow.activate (*******/node_modules/@temporalio/worker/lib/workflow/vm-shared.js:313:33)
      at handleRequest (*******/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:50:47),
  workflowExists: true
}
```

After digging into the `sdk-typescript` code to check what would cause this error I noticed that in https://github.com/temporalio/sdk-typescript/blob/3088f86ce6fe0c7072ba55c4db901a70b631f87e/packages/workflow/src/internals.ts#L263 the payload converter being used is always the default one. Whereas in other files, the custom payload converter is being used if passed, eg: https://github.com/temporalio/sdk-typescript/blob/3088f86ce6fe0c7072ba55c4db901a70b631f87e/packages/workflow/src/worker-interface.ts#L110

I guess the payloadConverter should be passed here: https://github.com/temporalio/sdk-typescript/blob/3088f86ce6fe0c7072ba55c4db901a70b631f87e/packages/workflow/src/worker-interface.ts#L96

If I'm mistaken could you clarify why the defaultPayloadConverter has to be used here? Also, I must say that It has been it hard and painful to work with custom payload converters.

### Environment/Versions

Machine:
```
OS: macOS 13.4.1 22F82 arm64
Host: MacBookPro18,3
Kernel: 22.5.0
CPU: Apple M1 Pro
GPU: Apple M1 Pro
```

- Temporal Version: `@temporalio/worker@npm:1.8.4 (via npm:^1.8.2)`
- Are you using Docker or Kubernetes or building Temporal from source: Docker for local development

### Additional context

I might try to open a PR for a fix if you confirm that this is indeed a bug :))

### Edit 1
It seems I was mistaken, and the payload converter is indeed passed to the activator here: https://github.com/temporalio/sdk-typescript/blob/3088f86ce6fe0c7072ba55c4db901a70b631f87e/packages/workflow/src/worker-interface.ts#L113

I managed to make it work by passing a TS file directly to `payloadConverterPath`. The issue might happen when the payload converter is bundled / from what it is bundled. Any advice on how to bundle it and pass it to the worker? I've had a lot of issues with this (not able to load an ESM payload converter, so I have to bundle it to esm).

I still wonder how the custom converter could work for the `toPayload` but not `fromPayload`. I will try to provide a minimum reproduction.

**Comment by bergundy** [comment]
The custom payload converter is passed to the activator and should be loaded properly if you pass the `payloadConveterPath` worker option.

I think we may have an issue with custom converters and ESM. I'll open an issue to track that separately.

**Comment by bergundy** [comment]
https://github.com/temporalio/sdk-typescript/issues/1292

**Comment by nohehf** [comment]
Thanks @bergundy for opening the issue, I'll report my findings here asap. I'm currently trying to find a way around this.

**Comment by nohehf** [comment]
I think it is indeed an issue with how I transformed my ESM ts into a commonjs bundle, but it is weird that it works to create the payload and start the activity, but not when the activity completes. I added some of my research to #1292. I'll close this issue and I hope that we will be able to fix this or provide guidelines to bundle payload converters (both would be the best actually). Ty!
