### ISSUE TITLE
Missing test coverage for Prometheus server

### ISSUE THREAD

**Issue by dandavison** [temporalio/sdk-typescript#1323]
A worker started with
```typescript
Runtime.install({ telemetryOptions: { metrics: { prometheus: { bindAddress: '0.0.0.0:9090' } } } });
```
should bring up a server listening for metrics requests on 9090. This works on `v1.8.6` but is broken in `v1.9.0-rc.0`.

Add tests to catch this.

**Comment by mjameswh** [comment]
Fixed by #1324.
