### ISSUE TITLE
[Feature Request] Validate input

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#1327]
### Is your feature request related to a problem? Please describe.

`client.workflow.start(type, { args: {} })` results in an opaque error message:

![image](https://github.com/temporalio/sdk-typescript/assets/251288/0958b186-fbf0-49d0-9c21-839c2b84a8fa)

### Describe the solution you'd like

Throw an error like `args must be an array`

**Comment by mjameswh** [comment]
No longer pertinent.
