### ISSUE TITLE
[Feature Request] Support weighted random polling multiple task queues

### ISSUE THREAD

**Issue by knpwrs** [temporalio/sdk-typescript#1366]
### Is your feature request related to a problem? Please describe.

Temporal does not have any mechanism to implement priority queues.

### Describe the solution you'd like

https://github.com/contribsys/faktory implements priority-like functionality on the worker side by implementing the ability to poll multiple queues for tasks, either in strict order, or by weighted random (to prevent starvation).

Consider the official https://github.com/contribsys/faktory_worker_go library:

```go
// pull jobs from these queues, in this order of precedence
mgr.ProcessStrictPriorityQueues("critical", "default", "bulk")

// alternatively you can use weights to avoid starvation
mgr.ProcessWeightedPriorityQueues(map[string]int{"critical":3, "default":2, "bulk":1})
```

The unofficial https://github.com/jbielick/faktory_worker_node likewise implements this:

```ts
faktory.work({ queues: ["immediately", "afterwards"] });
faktory.work({ queues: { critical: 10, default: 1 } });
```

### Additional context

I would imagine the API would look like this in the Temporal TypeScript SDK:

```ts
const worker = await Worker.create({
  // ...
  taskQueue: 'hello-world',
  // or...
  taskQueue: ['immediately', 'afterwards'],
  // or...
  taskQueue: { critical: 10, default: 1 },
});
```

The `taskQueue` property could also be named `taskQueues` and then something like https://github.com/sindresorhus/type-fest/blob/3ef12b0bdc7c29321daa304abf7a70ed49b9aa7d/source/require-one-or-none.d.ts can ensure that only one of either `taskQueue` or `taskQueues` can be passed to `Worker.create`.

**Comment by bergundy** [comment]
Priority queues is a platform level feature that is not currently supported.

Once Temporal server adds support for this, we can add it to the SDK.

Making a task queue a getter won't work, it's only evaluated once on creation, not on every poll request.

You can create multiple workers in the meantime with different options such as https://typescript.temporal.io/api/interfaces/worker.WorkerOptions#maxconcurrentactivitytaskpolls

Follow this issue for platform level support:
https://github.com/temporalio/temporal/issues/1507
