### ISSUE TITLE
[Bug] Page size filter in @temporalio/client list method doesn't seem to be working properly

### ISSUE THREAD

**Issue by Thexumaker** [temporalio/sdk-typescript#1382]
### What are you really trying to do?
I'm trying to query for some workflow data via the temporal client list method.

### Describe the bug

I'm calling temporalClient.list({pageSize: 1, query: 'randomQuery'}) but it seems to just returns thousands of results

The result should've returned just 1 item but I get back a thousand results.

### Minimal Reproduction

```
const iterable = temporalClient.list({
      pageSize: 1,
      query: `userId = '123'`,
    });

    const results = [];
    for await (const item of iterable) {
      results.push(item);
    }

    logger.info(`length of results: ${results.length}` );
 ```
    
    It should return 1 result based on the docs, but I also couldn't find too much documentation for this

### Environment/Versions

- OS and processor: M1 mac
- Temporal Version: 1.19 SDK
- Are you using Docker or Kubernetes or building Temporal from source?
Docker

### Additional context

I'm not too concerned by this issue but reading the docs(https://docs.temporal.io/visibility#efficient-api-usage) I'm not really able to test pagination which will become a blocker in the future

**Comment by jpalof** [comment]
@Thexumaker , I am having a similar problem (https://community.temporal.io/t/problem-limiting-results-of-workflowclient-list-pagesize-1/15725).  I noticed that you marked this bug as `completed`.  I don't see a fix associated with this bug.  Did you discover a mis-conception on your usage or a workaround that resulted you in closing this bug?

Thanks
