### ISSUE TITLE
[Feature Request] HTTP CONNECT proxy support

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-typescript#1387]
### Describe the solution you'd like

* Support HTTP connect proxy options for workers added in https://github.com/temporalio/sdk-core/pull/714. See how Python did it at https://github.com/temporalio/sdk-python/pull/501
* Investigate and try to add HTTP connect proxy options for JS gRPC client
* Add test in features repo

**Comment by brendan-myers** [comment]
+1 

Client/grpc-js supports HTTP CONNECT through setting the `http_proxy` environment variable.
