### ISSUE TITLE
Support for WorkflowIdConflictPolicy

### ISSUE THREAD

**Issue by josh-berry** [temporalio/sdk-typescript#1392]
See https://github.com/temporalio/features/issues/437

**Comment by stephanos** [comment]
NOTE: Please don't forget SignalWithStart API.

**Comment by hugo082** [comment]
Hi there, any updates on this feature? I see the PR is inactive since several month.
AFAIK TS sdk is the only one missing this feature

**Comment by stephanos** [comment]
Good question; the [PR seems to still be blocked](https://github.com/temporalio/sdk-typescript/pull/1490); I'll ask again.
