### ISSUE TITLE
[Feature Request] Better error details on why ephemeral test server didn't start

### ISSUE THREAD

**Issue by mikeroelens** [temporalio/sdk-typescript#1396]
### Is your feature request related to a problem? Please describe.
Right now in CI we're randomly getting `Failed to start ephemeral server: Failed connecting to test server after 5 seconds` errors when calling `TestWorkflowEnvironment.createLocal`.  But there's no indication as to why the test server couldn't be started.

The relevant code in sdk-core is [here](https://github.com/temporalio/sdk-core/blob/409e74ec8e80ae4c1f9043e8b413b1371b65f946/core/src/ephemeral_server/mod.rs#L314). Looks like an attempt is made to start the ephemeral test server, then connect attempts every 100ms for 5s, if not connected at that point throw an error. 

**Key Problem:** No idea why the test server didn't start

### Describe the solution you'd like

A clear error reason logged as to why the test server didn't start. Right now it's also impossible to tell if there was an error or if the server was just slow to startup (e.g. maybe it would've started fine after 6s).

**Comment by mjameswh** [comment]
@mikeroelens Thanks for reporting. This has just been fixed.

> On posix platforms, stdout and stderr were not properly inherited by ephemeral servers, which meant that users would get no detail of why the server failed to start.
>
> For details: NodeJS is setting FD_CLOEXEC on all of its standard file descriptors (stdin, stdout, stderr), which means that these file descriptors are not inherited by child processes… Now, the child_process module emulates the inheritance behavior by explicitly passing the file descriptor to new processes by default, so that’s not a problem when spawn is called from JS code. But it will bite you when you spawn from native code, for example when starting an ephemeral server through Core SDK…
