### ISSUE TITLE
[Bug] Latest update to v1.10.0 makes build fail

### ISSUE THREAD

**Issue by johnrjj** [temporalio/sdk-typescript#1427]
### What are you really trying to do?

Build started failing after updating latest 1.1.0. Also repro'd in Render environment:

`Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/render/project/src/node_modules/.pnpm/@temporalio+core-bridge@1.10.0/node_modules/@temporalio/core-bridge/releases/x86_64-unknown-linux-gnu/index.node)`

### Describe the bug

Update @temporalio packages to v^1.10.0. Build in remote CI, build fails.

Bun had a similar issue it appears -- https://github.com/oven-sh/bun/issues/255

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by johnrjj** [comment]
Will try to create a repro over weekend -- just wanted to post issue here for visibility in case others encounter same problem. In the meantime I downgraded back to 1.9.0 without any issue.

**Comment by mjameswh** [comment]
@johnrjj What's the [version of Node.js](https://docs.render.com/node-version) in your Render environment?

As mentioned in [v1.10.0's release notes](https://github.com/temporalio/sdk-typescript/releases/tag/v1.10.0), Node 14.x is no longer supported. Also note that Node 16 will no longer be supported starting with v1.11.

See this annoucement from our [v1.9.0 release notes](https://github.com/temporalio/sdk-typescript/releases/tag/v1.9.0):

> Support for Node.js 14 and Node.js 16 will soon be dropped. Node.js 14 officially reached end-of-life on April 30th, 2023, and Node.js 16 reached end-of-life on September 11th, 2023 (see [Node.js release schedule](https://nodejs.org/en/about/previous-releases#release-schedule)).
>
> This has since then caused a rippling effect, as more and more libraries in the NPM ecosystem are progressively dropping support for both of those older targets. Given that challenges to maintaining compatibility with these outdated Node.js releases will only continue to grow, it is evident that we will soon need to follow suit in discontinuing support for Node.js 14 and 16 in the Temporal TypeScript SDK.
>
> For those reasons:
>
>    TS SDK v1.9 will be the last minor release to support Node.js 14.
>    TS SDK v1.10 could possibly be the last minor release to support Node.js 16. Note that this also implies that GLIBC 2.27 will no longer be supported from that point on, since Node.js 18+ won’t compile on GLIBC older than 2.28.
>
> We strongly encourage everyone to take immediate action in updating their deployments to supported versions of Node.js to ensure continued compatibility and receive the latest features and security updates.

**Comment by johnrjj** [comment]
Using latest/default. Will try for a repro. Will also try debugging a bit more deeply.

```
INFO==> Requesting node version >=18
INFO==> Using Node version 22.2.0 via /opt/render/project/src/package.json
INFO@repo/temporal:build: > @repo/temporal@0.1.0 build:workflow /opt/render/project/src/apps/temporal
INFO@repo/temporal:build: > ts-node src/scripts/build-workflow-bundle.ts
INFO@repo/temporal:build: 
ERROR@repo/temporal:build: Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/render/project/src/node_modules/.pnpm/@temporalio+core-bridge@1.10.0/node_modules/@temporalio/core-bridge/releases/x86_64-unknown-linux-gnu/index.node)
INFO@repo/temporal:build:     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1544:18)
INFO@repo/temporal:build:     at Module.load (node:internal/modules/cjs/loader:1249:32)
INFO@repo/temporal:build:     at Function.Module._load (node:internal/modules/cjs/loader:1065:12)
INFO@repo/temporal:build:     at Module.require (node:internal/modules/cjs/loader:1271:19)
INFO@repo/temporal:build:     at require (node:internal/modules/helpers:123:16)
INFO@repo/temporal:build:     at Object.<anonymous> (/opt/render/project/src/node_modules/.pnpm/@temporalio+core-bridge@1.10.0/node_modules/@temporalio/core-bridge/index.js:26:20)
INFO@repo/temporal:build:     at Module._compile (node:internal/modules/cjs/loader:1434:14)
INFO@repo/temporal:build:     at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
INFO@repo/temporal:build:     at Object.require.extensions.<computed> [as .js] (/opt/render/project/src/node_modules/.pnpm/ts-node@10.9.2_@swc+core@1.5.7_@swc+helpers@0.5.11__@types+node@16.11.43_typescript@5.4.5/node_modules/ts-node/src/index.ts:1608:43)
INFO@repo/temporal:build:     at Module.load (node:internal/modules/cjs/loader:1249:32) {
INFO@repo/temporal:build:   code: 'ERR_DLOPEN_FAILED'
INFO@repo/temporal:build: }
INFO@repo/temporal:build:  ELIFECYCLE  Command failed with exit code 1.
INFO@repo/temporal:build:  ELIFECYCLE  Command failed with exit code 1.
ERROR@repo/temporal:build: ERROR: command finished with error: command (/opt/render/project/src/apps/temporal) /usr/bin/pnpm run build exited (1)
INFO@repo/temporal#build: command (/opt/render/project/src/apps/temporal) /usr/bin/pnpm run build exited (1)
INFO
```

**Comment by mjameswh** [comment]
I see. That means Render is using glibc 2.28 based image for their containers. Node 18 requires at least glibc 2.28, but 1.10.0 requires glibc 2.29 (or 2.35 on linux-arm64).

We're already working on a solution to [build TS SDK 1.10 on an older glibc](https://github.com/temporalio/sdk-typescript/pull/1428). Unfortunately, some recent/upcoming changes in GitHub Actions are making this harder than it should be, but I have good hope that making it work on glibc 2.28 is possible.
