### ISSUE TITLE
[Feature Request] Support "query" when listing schedules

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-typescript#1457]
### Describe the solution you'd like

Need to support the query option when listing schedules same as we do when listing workflows.

**Comment by nikhilbhatia08** [comment]
@cretz I would like to work on this issue.
What I would be doing: As we have ListOptions for workflows which gives us the number of results based on the query similarly, I would do it to list schedules with query which will match with the existsing schedules and order the results, pageSize which would set max number of results to fetch per page. Please can I work on it.

**Comment by antlai-temporal** [comment]
Hi Nikhil, I was about to start on this, but if you are interested, give it a try, and I'll help with the reviews instead...

**Comment by mjameswh** [comment]
Fix by #1535.
