### ISSUE TITLE
[Feature Request] Allow dev server version to be explicitly provided and mark some options as unstable

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-typescript#1464]
### Describe the solution you'd like

Users should be able to put a specific version in for downloading dev server. Also, we should make it clear (as we do in Python) that besides the obvious arguments, other arguments may not be stable and could change when the underlying implementation is swapped out. This is especially true for "extra args".

**Comment by josh-berry** [comment]
@cretz Should we not do this in all languages? Or is it just missing in TypeScript?

**Comment by mjameswh** [comment]
> Users should be able to put a specific version in for downloading dev server.

That's already supported:

```
TestWorkflowEnvironment.createLocal({
  server: {
    executable: {
      type: 'cached-download',
      version: 'v0.13.2',
    },
  },
}
```
… and similar for time skipping server.

> Also, we should make it clear that besides the obvious arguments, other arguments may not be stable and could change when the underlying implementation is swapped out. This is especially true for "extra args".

Good point. I'll review the docstrings.

**Comment by cretz** [comment]
> @cretz Should we not do this in all languages? Or is it just missing in TypeScript?

Sorry, missed this (I get notified for every TS thing and ignore usually and GH notifications doesn't differentiate mentions from every other notification). It is in other languages already (though the statement on instability of advanced arguments only in Python and .NET, not Go that I see).
