### ISSUE TITLE
[Bug] Interceptors Don't Seem to Support Module Alias

### ISSUE THREAD

**Issue by ccravens** [temporalio/sdk-typescript#1468]
### What are you really trying to do?
I'm trying to be able to use my module-alias imports with worker interceptors.

### Describe the bug

I use `"module-alias": "2.2.2"` in my project to create a root path for all of my imports. So instead of doing:

```typescript
import { X } from '../../../../../very/long/path';
```

I can just do:

```typescript
import { X } from '~/very/long/path';
```

However when creating a worker with interceptors:

```typescript
const worker = await Worker.create({
      connection: await NativeConnection.connect({
        address: `${process.env.TEMPORAL_HOST}:${process.env.TEMPORAL_PORT}`,
      }),
      namespace: 'ns',
      taskQueue: 'queue',
      identity: `worker-${Utils.node._id}`,
      ...(Utils.production && {
        workflowBundle: {
          codePath: require.resolve('../temporal/workflow-bundle.js'),
        },
      }),
      ...(!Utils.production && { workflowsPath: require.resolve('../temporal/workflows') }),
      activities,
      interceptors: {
        workflowModules: [require.resolve('../temporal/interceptors/temporal.interceptor')], // <<< Import Interceptor here <<<
      },
    });
```

and my Interceptor:
```typescript
import { TemporalWorkflowsService } from '~/services/models/temporal-workflows.service'; // <<< THIS BREAKS

class InboundInterceptor implements WorkflowInboundCallsInterceptor {
  constructor(
    public readonly workflowId: string,
    public readonly workflowType: string,
    temporalWorkflowsService: TemporalWorkflowsService
  ) {}

  async execute(
    input: WorkflowExecuteInput,
    next: Next<WorkflowInboundCallsInterceptor, 'execute'>
  ): Promise<unknown> {
    console.log(`>>> INBOUND: execute(): ${this.workflowType}[${this.workflowId}]`);
    try {
      return await next(input);
    } finally {
      console.log(`>>> INBOUND: Finished execute(): ${this.workflowType}[${this.workflowId}]`);
    }
  }
  ...
  }
```
It does not seem to recognize the module alias.

What's worse is not only do I now have to convert my imports from `~` to `../../../..` for the import in the interceptor but also recursively ALL other dependencies. Is there a better way to address this?

### Environment/Versions
Apple M2 Max Sonoma 14.5
```
    "@temporalio/activity": "1.10.1",
    "@temporalio/client": "1.10.1",
    "@temporalio/worker": "1.10.1",
    "@temporalio/workflow": "1.10.1",
    ```
Using the docker-compose on my local dev machine

**Comment by mjameswh** [comment]
> It does not seem to recognize the module alias.

What's the symptom. Do you get an error message, or is this silently failing?

**Comment by mjameswh** [comment]
Two things:

1. Your worker uses prebundled Workflows in production environment. Workflow Interceptors passed directly through `WorkerOptions` will be silently ignored in that case. You need to pass the list of Workflow Interceptors, together with your Workflow Code, to the `bundleWorkflowCode()` function. See [`BundleOptions.workflowInterceptorModules`](https://typescript.temporal.io/api/interfaces/worker.BundleOptions#workflowinterceptormodules).

2. `module-alias`'s magic doesn't automatically extend to bundlers. You will therefore need to provide specific configuration to the Workflow Bundler to apply your aliases. Based on [module-alias example for Webpack](https://github.com/ilearnio/module-alias?tab=readme-ov-file#usage-with-webpack), that should look something like:

```
const npm_package = require('./package.json');
const myAliases = npm_package._moduleAliases;

webpackConfigHook: (config) => {
  if (config.resolve) {
    config.resolve.alias = {
      ...config.resolve.alias,
      ...myAliases,
    };
  }
  return config;
}
```

Make sure to include this `webpackConfigHook` function in both your Worker's options (for dev usage) and `bundleWorkflowCode()`'s options (for production builds).

**Comment by ccravens** [comment]
Hello @mjameswh!

Thank you very much for getting back to me on this. I've really been working on this the past couple of days and I was able to find a reference to the webpackConfigHook in another issue and was able to update to this:

```typescript
const { code } = await bundleWorkflowCode({
      workflowsPath: require.resolve('~/temporal/workflows'),
      workflowInterceptorModules: [require.resolve('~/temporal/interceptors/temporal.interceptor')],
      logger: new TemporalLogger(),
      webpackConfigHook: (config: Configuration) => {
        if (config.resolve) {
          config.resolve.plugins = [
            ...(config.resolve.plugins ?? []),
            new TsconfigPathsPlugin({
              configFile: path.resolve(__dirname, '../../tsconfig.json'),
            }),
          ];
        }

        return config;
      },
      ignoreModules: [],
    });
```

I learned more about webpack the past couple of days than I have ever wanted to lol

I meant to update this issue, I appreciate your response on this and it is the correct solution. I'll close now, thanks again!
