### ISSUE TITLE
[Feature Request] Allow passing `pageSize` to `WorkflowHandle.fetchHistory`

### ISSUE THREAD

**Issue by CiaranMn** [temporalio/sdk-typescript#1469]
### Is your feature request related to a problem? Please describe.

Event histories larger than the gRPC limit of 4MB are not fetchable via `handle.fetchHistory()`.

As a workaround, they can be retrieved by using `getWorkflowExecutionHistory` directly on `workflowService` and paginating manually.

### Describe the solution you'd like

The ability to pass `pageSize` to `fetchHistory` and receiving an iterable, similar to how `workflow.list` works.

An alternative solution to the problem described would be to allow configuration of the message size limit, but I understand this is not desired – https://github.com/temporalio/temporal/issues/2786

### Additional context

In implementing the workaround of paginating through `getWorkflowExecutionHistory` I noticed that the docs on the returned `nextPageToken` are arguably inaccurate in that they describe it as "set if there are more history events than were included in this response", but it is always set (it is an empty `Array` if there are no more events).

**Comment by cretz** [comment]
> Event histories larger than the gRPC limit of 4MB are not fetchable via `handle.fetchHistory()`.

This is a bug, I have opened #1470.
