### ISSUE TITLE
Workflow-init support docs

### ISSUE THREAD

**Issue by drewhoskins-temporal** [temporalio/sdk-typescript#1483]
We should have a method that's guaranteed to initialize before signals and updates come in so handlers can use initialized values.

**Comment by drewhoskins-temporal** [comment]
For typescript, this appears to be a question of documenting that signals can happen before the workflow method runs and proposing the workaround in the docs here: https://docs.temporal.io/develop/typescript/message-passing

**Comment by antlai-temporal** [comment]
This will be resolved when PR https://github.com/temporalio/documentation/pull/3107/files merges
