### ISSUE TITLE
[Bug] @temporalio/worker with subdependency @opentelemetry/api version higher than 1.6.0 breaks

### ISSUE THREAD

**Issue by bert-bae** [temporalio/sdk-typescript#1502]
### What are you really trying to do?

Package update for latest on @temporalio/worker has an issue with a sub-dependency update for @opentelemetry/api. The version restriction listed for temporalio/worker is for opentelemetry/api to be ^1.3.0. We previously had 1.6.0 which does not have this issue, but updating our packages to have the latest 1.9.0 causes this problem.

### Describe the bug

Cannot run when `@temporalio/worker` uses `@opentelemetry/api` version `1.9.0` with the following error encountered:

```sh
Error: Package subpath './build/src/trace/NoopTracer' is not defined by "exports" in /opt/atlassian/pipelines/agent/build/node_modules/.pnpm/@temporalio+worker@1.8.6/node_modules/@opentelemetry/api/package.json
 ❯ Object.<anonymous> ../../node_modules/.pnpm/@temporalio+worker@1.8.6/node_modules/@temporalio/worker/src/tracing.ts:2:1

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_PACKAGE_PATH_NOT_EXPORTED' }
```

Locking @opentelemetry/api version between 1.3.0 to 1.6.0 is a workaround.

### Minimal Reproduction

Installing `@temporalio/worker` which currently has a minimum version marked for `@opentelemetry/api^1.3.0` downloads the latest of version 1.9.0 which breaks the import. It appears since temporalio/worker package is doing a deep import directly from the build directory, it is not an issue that opentelemetry will fix.

### Environment/Versions

Node Version 18.17.1
MacOS Sonoma

### Additional context

[Opentelemetry's github issue related to this problem](https://github.com/open-telemetry/opentelemetry-js/issues/4518)

**Comment by mjameswh** [comment]
The import on `NoopTracer` was removed in #1269. Please update all @temporalio to >1.9.0.
