### ISSUE TITLE
[Bug] All log related to the same trace_id 

### ISSUE THREAD

**Issue by baptou12** [temporalio/sdk-typescript#1556]
(This is probably more of a question than a bug)

### What are you really trying to do?

I am using temporal with Opentelemetry, and all logs in activities (using log from "@temporalio/acitivity") are related to the same trace_id which is the one of the startup of my app

### Describe the bug

I configured opentelemetry with temporal, using the 4 interceptors, but when I see logs they are all related to the same traceId. I don't know if my config is wrong or if there is a bug which do not create root span for my workflows.

**Comment by mjameswh** [comment]
See https://github.com/temporalio/sdk-typescript/issues/1425#issuecomment-2133992183.

Closing as duplicate.
