### ISSUE TITLE
[Bug] Payload Converter doesn't work when running as ESM

### ISSUE THREAD

**Issue by freshollie** [temporalio/sdk-typescript#1558]
### What are you really trying to do?

Provide a payload converter when my workers are running as ESM

### Describe the bug

https://github.com/temporalio/sdk-typescript/blob/5c3955fea45599d56312490f9a9957b6e70c6825/packages/common/src/internal-non-workflow/data-converter-helpers.ts#L40

The main code path which to import the data converter always uses `require` which means the format has to be CJS to be imported. Our current workaround is to write our `payload-converter` as `.cjs`.

### Minimal Reproduction

- Just use `payloadConverterPath` in an ESM application which uses the temporal worker.

### Environment/Versions

N/A

**Comment by mjameswh** [comment]
Thanks for reporting.

This issue is already tracked in #1292. Closing as duplicate.
