### ISSUE TITLE
[Feature Request] Test support

### ISSUE THREAD

**Issue by joebowbeer** [temporalio/sdk-typescript#226]
### Is your feature request related to a problem? Please describe.

Testability is a major selling point of Temporal but the Node SDK and its docs are [currently lacking](https://docs.temporal.io/docs/node/hello-world#testing):

> There's no official support for testing Workflows and Activities.
> * Since Activities are async functions, they should be testable as long as you avoid using Context or are able to mock it.
> * You can test Workflows by running them with a WorkflowClient.

I added a basic ts-jest configuration in [one example](https://github.com/temporalio/temporal-pendulum/blob/main/position-node/jest.config.js), but I couldn't figure out how to write a workflow test.

### Describe the solution you'd like

I think I need something like the TestWorkflowEnvironment that Java and Go provide before I can easily test workflows.

It would be helpful if the create-project example included a basic jest (and eslint) configuration.

### Additional context

It would also be helpful if the create-project example included a basic eslint configuration. Something that was useful, but not too bloated, and easily swapped out if needed.

**Comment by bergundy** [comment]
This is a known issue, thanks for opening this so it can be tracked.

**Comment by vkarpov15** [comment]
@joebowbeer you can take a look at https://github.com/temporalio/samples-node/pull/11, I added a basic test case there.

The trick is that you can stub out activity dependencies using sinon. The big thing that's missing is being able to advance time programatically, which is something that the Go SDK has a neat API for.

**Comment by joebowbeer** [comment]
@vkarpov15 Thanks! I'm motivated to have another look at the pendulum test now.

I like sinon and occasionally will even use proxyquire for the most test-resistant cases.

At first glance, though, I like the readability of the golang tests better, but the http test reads pretty well once I dive in.

I'll try ts-jest in the pendulum sample and see how it goes.

**Comment by joebowbeer** [comment]
@vkarpov15 Following up, after looking at the http sample _integration_ test in more detail:

### Should TypeScript workflows be unit-testable?

The Go and Java SDKs have an in-memory runner to enable this. The http _integration_ test is doing something similar to what the Go and Java docs present as unit tests. I tried to run the http test, saw a transport error, and only then realized I needed to run a real local temporal server.

### ts-tester vs transpiled src

It surprised me that the test was importing from `../lib` which, e.g., the starter code does not do explicitly.

I'm bothered by the inconsistency of having ts-node load the test code, while the code under test is loaded from the transpiler's outDir: `../lib`.

Unless ts-node can run everything, I'd prefer to see the src and test code handled the same way: transpiled first and loaded from the outDir. This way, perhaps with some aliasing, the explicit `../lib` can be hidden from the test code.

### mocha vs jest

I think jest would make a better impression.

Jest is newer, simpler, more-opinionated mocha, and jest mocking should be able to replace sinon as well. I think most react programmers are using jest now.

### src vs test

I would prefer to have the test files beside their src counterpart.

For example:  https://github.com/temporalio/temporal-pendulum/blob/main/position-node/src/workflows/pendulum.test.ts

This simplifies adding a new test file. Not a big difference, but simpler is better when it comes to samples.

**Comment by bergundy** [comment]
@joebowbeer we have plans to support proper testing for Core based SDKs, it's quite an undertaking because we have to implement a mocked version of the server for time skipping support.

Some test runners ([jest included](https://www.npmjs.com/package/ts-jest)) support running TS directly ([alternative](https://github.com/facebook/jest#using-typescript)).
I've usually avoided that because I always have a terminal running the typescript compiler in watch mode which is significantly faster than recompiling from scratch (not sure if there's a test runner that can do that).

I don't have a test framework preference, both jest and mocha are okay IMO.

As for src vs. test, a lot of devs like to separate their test code.
We might want to use [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) to preserve the output directory structure (`src` -> `lib` instead of `src` -> `lib/src`).

**Comment by joebowbeer** [comment]
@bergundy Thanks for clarifying. To be clear, I'm pushing for a simple approach to make the samples easy to read and test, and to encourage testing from day -1. (What I would actually use in a commercial project might be different.)

What you are describing sounds good to me: Have both src and test code transpiled via watch and run from the outDir.

I wrote:

> I'd prefer to see the src and test code handled the same way: transpiled first and loaded from the outDir

By doing this, the explicit outDir path should not need to appear in the src or test code.

However, this is not how the http integration test is currently configured. Only its src is transpiled to outDir while its test code is transpiled by ts-mocha, and there are two references to outDir in the test code.

When transpiling both src and tests, I think it works best if the path relationships are maintained in the outDir. Then the relative paths and aliases will be preserved in the outDir.

Example: `src` -> `lib/src`, `test` -> `lib/test`

Another way to preserve this relationship is to have `.ts` and `.test.ts` as siblings in the same folder, as I prefer for unit tests, but neither way should be precluded.

Similarly, neither jest nor mocha+sinon should be precluded, but I think jest will make for better examples because it has fewer moving parts and is designed for ease of use.

**Comment by lorensr** [comment]
For Google, the error you get when you call an activity function directly (eg when unit testing) that uses `Context.current()`: `Activity context not initialized`. 

Current solution is to mock Context or use integration tests (have a Worker call activities, which will work because the Worker sets up Context)

**Comment by bergundy** [comment]
Test framework is coming, and it will support mocking the activity context.

**Comment by bergundy** [comment]
Closing this as part of issue cleanup.
