### ISSUE TITLE
[Feature Request] Match dev and CI linting

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#233]
I'd like if these types of linting errors:

![image](https://user-images.githubusercontent.com/251288/132934447-807640e3-d6a0-492f-a01d-202f26ddec9b.png)

showed up when I lint or commit locally:

```
$ npm run lint

> lint
> eslint packages/*/src --ext .ts --no-error-on-unmatched-pattern && prettier --check .

Checking formatting...
All matched files use Prettier code style!
```

**Comment by bergundy** [comment]
You can run commitlint yourself with: `npx commitlint --from origin/main`.
Let's add that to `CONTRIBUTING.md`.

**Comment by bergundy** [comment]
I kind of like that commitlint is a separate GH workflow but I'm open to merging it with the `lint` command.

**Comment by bergundy** [comment]
We removed commitlint from CI
