### ISSUE TITLE
[Feature Request] Change parameter order for injected functions?

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#242]
It feels weird to me that `workflowInfo` is the first parameter, followed by the parameters defined in the interface. Anyone else agree? 

A. `workflowInfo` reminds me of context/options/info args that I'm used to being passed as the last optional parameter.
B. Having it first clashes more in my mind with the interface than if it were last. In both cases, the signature doesn't match, but if it's last, at least my assumption that the first arg will be `message` holds.

![image](https://user-images.githubusercontent.com/251288/133369912-78bdf8c8-5638-4a6b-b94b-b71685a2ba54.png)

![image](https://user-images.githubusercontent.com/251288/133369827-f967a525-98bd-41e2-9e97-c2ed65cba1ab.png)

**Comment by mjameswh** [comment]
@lorensr It is probably too late for this change... WDYT?

**Comment by lorensr** [comment]
Yep
