### ISSUE TITLE
[Feature Request] Asynchronous Activity Completion

### ISSUE THREAD

**Issue by mikegai** [temporalio/sdk-typescript#243]
### Is your feature request related to a problem? Please describe.

We have a Node activity that makes a POST request to an existing (Node) AWS Lambda function, which in turn launches a process that can last over a minute.
The Lambda is behind an API gateway so has a maximum timeout of 30 seconds. So we can't wait for the lambda to return the final response.
Right now we have the lambda immediately returning a 200 upon start of the process, and then later signaling success/failure back to the workflow when done.
However that makes us add extra signal(s) (success/fail) just to complete a simple activity. It's just a few lines of code so is not onerous, but it does add some noise to an otherwise smooth flow.
In the Go SDK we see an incrementally more attractive approach.

### Describe the solution you'd like

In the Go SDK you can "asynchronously complete an activity":
https://docs.temporal.io/docs/go/activities#asynchronous-activity-completion
We would like the same in node.
That way we can preserve the separation of concerns between workflow and activities: workflows execute activities while activities take care of any internal execution complexity, saving signals for true inter-"actor" collaboration and external events.

**Comment by bergundy** [comment]
This is definitely something we want to support.
Technically this is already supported since you can complete the activity using the service client but you can’t make the worker “forget” about which will cause resource leak.

I’ll make sure to prioritize forgetting activities after we release beta.

cc @Sushisource

**Comment by bergundy** [comment]
Right now the worker takes ownership of an activity.
This means that when your activity function returns or throws it will report the result back to the server.
There's no way of letting the worker know that the activity will be resolved asynchronously.

If you were to never return from the activity function (assuming no timeout on the activity task) the worker would leak memory tracking all of the open activities.

**Comment by bergundy** [comment]
I plan on implementing the TypeScript side tomorrow or Wednesday, core support was already added.
