### ISSUE TITLE
[Feature Request] Support history replay as exported from tctl and Temporal web

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#255]
### Is your feature request related to a problem? Please describe.

Other SDKs have the ability to replay exported Workflow history, this is a critical feature for Workflow debuggability.

### Describe the solution you'd like

Add an easy way to replay Workflow history against a given Worker.

### Additional context

Related: https://github.com/temporalio/sdk-java/pull/729

**Comment by Sushisource** [comment]
We should probably do this in core, so we don't need to do it over and over. It should fit naturally into how I already do a lot of testing.

We'll just need to expose the mock poller API or something simpler that just constructs a core instance with a provided history, and uses the mock pollers under the hood.
