### ISSUE TITLE
Post-release: Update server version-feature mapping

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-typescript#261]
The fix we made to follow execution chains under the new model won't be used until we add node to the version mapping here:

https://github.com/temporalio/temporal/pull/1949/files#diff-b3797d690c398677a5a20c26925f78157dc5da1bf96316215d93ac26ecd7bd2bR59

Do that after our next release. We should also verify we are properly sending the SDK version info.

**Comment by bergundy** [comment]
@Sushisource I think we can update the mapping, right?

Also, as I've pointed out to @dnr [here](https://github.com/temporalio/temporal/pull/1949/files#r754761218) maybe we should send capabilities from the client instead.

**Comment by bergundy** [comment]
Closing this for now.

Opened this sdk-features issue to track SDKs sending client capabilities:
https://github.com/temporalio/sdk-features/issues/142
