### ISSUE TITLE
[Feature Request] Reconnecting to the server instead of crashing

### ISSUE THREAD

**Issue by emmanuelvlad** [temporalio/sdk-typescript#290]
### Is your feature request related to a problem? Please describe.

When the temporal server is or goes down, `Worker.Create()` / `worker.run()` throws and can't reconnect

### Describe the solution you'd like

I wish that it'll work like the Golang sdk, being able to create a worker even if the temporal server is down so I could have my other services running on parallel (an express app)

Automatically reconnecting to the temporal server when it goes back up

**Comment by Sushisource** [comment]
Well, it's not throwing, but the worker is stopping, which shouldn't happen. I'll fix.

**Comment by Sushisource** [comment]
Yeah, looks like this can happen:

```
2021-10-08T23:51:16.302Z [INFO] Worker state changed { state: 'RUNNING' }
2021-10-08T23:51:27.971Z [ERROR] Worker failed {
  error: [TransportError: Unhandled grpc error when workflow polling: Status { code: Unknown, message: "transport error", source: None }]
}
2021-10-08T23:51:27.971Z [INFO] Worker state changed { state: 'FAILED' }
```

Will fix. @emmanuelvlad If you would post the output, that'd help. I assume it was something like the above?

**Comment by emmanuelvlad** [comment]
Yep, I have the same as you

```
2021-10-09T08:49:53.470Z [INFO] Worker state changed { state: 'RUNNING' }
2021-10-09T08:49:53.474Z [INFO] [temporal_sdk_core] Registering worker task_queue="api" 
2021-10-09T08:50:10.283Z [ERROR] Worker failed {
  error: [TransportError: Unhandled grpc error when activity polling: Status { code: Unknown, message: "transport error", source: None }]
}
2021-10-09T08:50:10.284Z [INFO] Worker state changed { state: 'FAILED' }
[TransportError: Unhandled grpc error when activity polling: Status { code: Unknown, message: "transport error", source: None }]
```

**Comment by bergundy** [comment]
I’m leaving it closed but we still need to advance core for this to be resolved
