### ISSUE TITLE
Consider strict boolean check in `condition` function return value

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#291]
should we make sure this is `true`, not just truthy?

```ts
      if (cond.fn() === true) {
```

_Originally posted by @sw-yx in https://github.com/temporalio/sdk-node/pull/289#discussion_r725224409_

**Comment by bergundy** [comment]
Probably too late at this point.

**Comment by sw-yx** [comment]
sad day for footguns :)

**Comment by bergundy** [comment]
I think a lot of users would expect that condition behaves like an `if` statement.
For example, one might expect `condition(() => array.length)` to resolve when there are new elements added to the array.
