### ISSUE TITLE
[Feature Request] Support connecting to multiple server addresses from Core and optionally the Node gRPC client

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#294]
See original issue here: https://github.com/temporalio/sdk-go/issues/577

**Comment by bergundy** [comment]
Noting that custom gRPC resolvers can be used to achieve this.
Those are marked as experimental in grpc-js and not exposed in the Core API.

**Comment by mjameswh** [comment]
Closing. Lack of demand.
