### ISSUE TITLE
[Feature Request] Help users avoid old-worker-code bug

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#305]
### Is your feature request related to a problem? Please describe.

When devs have an old version of their code in a worker (in the background or another shell they forgot about), they can face an issue where they `npm run workflow`, and sometimes the tasks are picked up by the up-to-date worker, and sometimes they're picked up by an old worker, and they don't realize the latter is happening, so they don't know why sometimes things aren't working.

### Describe the solution you'd like

While we could add this to the [troubleshooting page](https://docs.temporal.io/docs/node/troubleshooting), I think a better solution would be to warn users—when the worker starts in development, can it search for other worker processes on the current machine and log a warning with the PID(s)?

```
⚠️ Warning: There is another worker process running on this machine. 
If it was started with an older version of your Worker and Activity code, 
we recommend stopping it to ensure that only your current code is being run. 
You can stop it by running this command in your shell:
kill 1234
```

### Additional context

While I've experienced this before, I didn't think about solving it for others until @schickling had the issue—thanks!

**Comment by bergundy** [comment]
@lorensr can you describe exactly how you think this will work?
By development do you mean that the worker connects to localhost or to check `NODE_ENV`?

`tctl` has a feature to describe the task queue and list connected workers which we may be able to use (by calling the server API not invoking `tctl`)

```shellsession
$ tctl tq desc --tq test
  WORKFLOW POLLER IDENTITY |   LAST ACCESS TIME
  27354@macbearpig.lan     | 2021-10-15T17:37:02Z
```

Maybe this could be done by `nodemon` when running `start.watch`? It doesn't cover all of the cases though.

**Comment by mjameswh** [comment]
Should probably be resolved using worker versioning instead.

**Comment by lorensr** [comment]
@Sushisource does versioning solve this development use case, or is it just for deployment?
