### ISSUE TITLE
[Request] split `createWorkflowHandle` into `getExistingWorkflowHandle`?

### ISSUE THREAD

**Issue by sw-yx** [temporalio/sdk-typescript#309]
### Describe the bug

currently createWorkflowHandle has overloaded behavior:

```ts
// create new workflow
client.createWorkflowHandle(workflowDef, wfOptions)

// retrieve existing workflow
client.createWorkflowHandle({ workflowId })
```

but when I pass in `client.createWorkflowHandle(workflowId)` by accident (instead of `client.createWorkflowHandle({workflowId})`, it gives confusing error `MissingWorkflowOptions.taskQueue` rather than guiding me towards the right answer.

suggest to 

1. split the second behavior to another function, `getExistingWorkflowHandle` 
2. in dev, run validation against the `workflowDef` and warn if it looks like a workflowId

**Comment by bergundy** [comment]
Closed by #324
