### ISSUE TITLE
Expose health check on WorkflowClient

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-typescript#312]
Temporal SDK should expose a method like WorkflowServiceStubs#healthCheck or WorkflowServiceStubs#isHealthy that allows users to check if the WorkflowClient/WorkflowServiceStubs underlying channel / connection to Temporal server is healthy.
There were quite a bit of user requests for such a method from users for all SDKs.
Having this method on Stubs is preferable over WorkflowClient, because it's the lowest level abstraction on top of the channel and WorkflowClient can just fall back on the WorkflowServiceStubs method. But if the language doesn't have a wrapper for stubs (like Java does), this method may be on WorkflowClient.

Issues for other SDKs:
https://github.com/temporalio/sdk-java/issues/828
https://github.com/temporalio/sdk-go/issues/595

**Comment by bergundy** [comment]
We probably won't expose this on `WorkflowClient`, there's a plan to add a "meta" `Client` that will contain the more specific clients.

**Comment by bergundy** [comment]
This is now exposed via the raw gRPC client.

**Comment by clintonb** [comment]
@bergundy can you provide an example of how to use this, please?

**Comment by bergundy** [comment]
See https://typescript.temporal.io/api/classes/client.Connection#healthservice.
If you can’t make sense out of that I can post the example

**Comment by AlexHayton** [comment]
I have tried to implement it based on the docs but getting stuck at `grpc.health.v1.Health.create()` - @burgundy if it's not too much trouble, please could you post your example?

**Comment by bergundy** [comment]
```ts
import { Connection } from '@temporalio/client';
import { grpc } from '@temporalio/proto';

const connection = await Connection.connect();
const health = await connection.healthService.check({});
console.log(grpc.health.v1.HealthCheckResponse['ServingStatus'][health.status]);
```
