### ISSUE TITLE
[Feature Request] Add missing continuedAsNewExecutionRunId to WorkflowInfo interface

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#314]

**Comment by sw-yx** [comment]
from: Tiho: 
Tihomir Surdilovic  3 minutes ago
@Roey Berman @Shawn Wang i think you can  add parentId and parentRunId as well which is useful for child workflows if its possible

**Comment by sw-yx** [comment]
to document https://github.com/temporalio/documentation/pull/696 on close
