### ISSUE TITLE
[Feature Request] Improve workflow id documentation

### ISSUE THREAD

**Issue by joebowbeer** [temporalio/sdk-typescript#318]
### Is your feature request related to a problem? Please describe.

I noticed that the node-sdk docs seem to encourage letting temporal generate the workflow id, but there are lots of cases where that leads to trouble. The Concepts docs recommends providing a business-meaningful workflow id, which I think is better advice.

https://docs.temporal.io/docs/node/client/#workflow-handle-options

> Most users should do just fine with the autogenerated workflowId.

The problem with that statement is that while it is statistically true, there are a class of use cases where it is not suitable (e.g., the cases where signalWithStart is useful).

### Describe the solution you'd like

@sw-yx I suggest hinting that there is more to workflow id than meets the eye, and linking to the full description:
[Workflows | Temporal documentation](https://docs.temporal.io/docs/concepts/workflows#workflow-id)

### Additional context

I also think the node-sdk docs blur the distinction between createHandle and creating a new workflow - which is once again an important one when dealing with signalWithStart.

**Comment by bergundy** [comment]
@joebowbeer Is this addressed now in your opinion?
`workflowId` is now required in all `WorkflowClient` methods.

**Comment by joebowbeer** [comment]
Addressed.
