### ISSUE TITLE
Guidance on connection and client instantiation pattern when long-lived connections will frequently drop

### ISSUE THREAD

**Issue by davidtheclark** [temporalio/sdk-typescript#325]
To use a client, we create a `Connection`, pass that into the `WorkflowClient` constructor to create a client instance, then use the client instance's methods to make requests.

In a situation where the server app may be redeployed at any moment — so clients will have outstanding connections dropped and they'll need to establish new connections — should we only need to create one `Connection` and `WorkflowClient` for the life of the client application? And we can trust that it will re-connect to the server whenever its TCP connection is dropped? Or should we instead create a new `Connection` and `WorkflowClient` for every request, so we don't have to worry about long-lasting connections getting dropped between requests?

We have been receiving some "connection dropped" errors, so before we proceed too far with debugging we wanted to make sure we're using the Temporal client as recommended. Thanks!

cc @mengyazhu96

**Comment by Sushisource** [comment]
Will look into this first thing next week

**Comment by Sushisource** [comment]
@davidtheclark Can you post the exact errors you're getting here? There's multiple ways a lost connection can surface.

For example:
```
Error {
    code: 14,
    details: 'No connection established',
    metadata: Metadata {
      internalRepr: Map {},
      options: {},
    },
    message: '14 UNAVAILABLE: No connection established',
  }
```

It'd be useful to know if you see that or something different. 

I was able to confirm that if the connection is lost, an individual call might fail after it hits the retry limit, but the connection itself still will work fine if you try to use the client again. So, yes, you can trust the `Connection` and `WorkflowClient` instance may be re-used (though, depending on your retry policy, in-progress calls may eventually fail if the connection is lost for long enough)

Also note https://github.com/temporalio/sdk-core/pull/213 which fixes an issue with workers possibly giving up if the server is down for a while
