### ISSUE TITLE
Speed up GitHub Action

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#339]
It would be nice if this workflow ran faster (with several PRs I've found myself waiting and checking back on the status and it's usually still in progress):

[.github/workflows/ci.yml](https://github.com/temporalio/sdk-typescript/blob/main/.github/workflows/ci.yml)

Not high priority, and I don't have much experience/ideas around this—from a brief search: maybe more things in parallel, more caching, prebuilt docker images?

**Comment by bergundy** [comment]
I have some ideas on how to speed this up.
I talked to the Temporal infra team about getting dedicated runners.
Apart from that I have some other ideas.
This is getting annoying to me too.

**Comment by mjameswh** [comment]
Completed in #1003
