### ISSUE TITLE
[Bug] Retry worker connection when temporal server is down

### ISSUE THREAD

**Issue by emmanuelvlad** [temporalio/sdk-typescript#344]
### Describe the bug

When running a worker while the temporal server is down, the worker throws a transport error and stops retrying to reconnect.
(#290 retries only if the temporal server was already up when running the worker)

### To Reproduce

Stop the temporal server
Run a worker

### Expected behavior

The worker should retry the connection to the temporal server without crashing

### Versions

- OS: Windows
- Temporal Version: 1.12.1
- Temporal SDK: 0.12.0
- Docker

### Additional context

Is there a way to disable the WARNs while the worker is retrying?
![](https://i.imgur.com/B8zhATq.png)

**Comment by bergundy** [comment]
We chose not to attempt to reconnect when worker starts to avoid a situation where workers are left idle in case of misconfiguration.

@Sushisource let's open this up and see if we want to change that.

@emmanuelvlad for now you can implement your own retry by wrapping `Worker.create` or `Core.install`.

**Comment by bergundy** [comment]
I'm closing for now because I feel like the current behavior is fine.
@emmanuelvlad we can keep discussing here if you'd like a different solution and can convince us.
