### ISSUE TITLE
[Bug] Patches should be applied to workflow before workflow code is required

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#362]
We should support patches at the top level of user code as shown here:
```ts
let runActivity = false;
if (patched('p1')) {
  runActivity = true;
}

export async function myWorkflow() {
  if (runActivity) {
    await myActivity();
  }
}
```

**Comment by Sushisource** [comment]
@bergundy Keep in mind this will only find patches in the 1st/2nd workflow task

**Comment by bergundy** [comment]
yup @Sushisource

**Comment by bergundy** [comment]
We decided to disallow this because patches at top level apply to all workflows and the experience is too confusing.
