### ISSUE TITLE
[Feature Request] Provide better errors when user passes a nameless function to infer workflow name

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#367]
See related discussion here: https://temporalio.slack.com/archives/C01DKSMU94L/p1636493017132500

**Comment by sw-yx** [comment]
more generally, i'd like to do an "error message review" after beta launch where we go thru stuff like this and add validation/nice errors

**Comment by lorensr** [comment]
Related: when workflow Foo is not exported from `workflowsPath`:
```
Child Workflow execution failed
Caused By: ReferenceError: 'Foo' is not a function 
ApplicationFailure: 'Foo' is not a function
```

**Comment by bergundy** [comment]
As for nameless function, I think the client should easily be able to check that at runtime.
We could also wrap the ReferenceError in a more informative error.
