### ISSUE TITLE
[Feature Request] Provide docker image(s) for compiling/running workers

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-typescript#368]
### Is your feature request related to a problem? Please describe.

Users are unsure about how to build & run our workers in containers

### Describe the solution you'd like

On our docker account we should provide a build image and a runtime image. We should update docs to include some info on how to properly use the images

**Comment by sw-yx** [comment]
ping me when you want me to come in but i'll assume youve got this

**Comment by bergundy** [comment]
Now that we have `vm` support and pre-built binaries for all major architectures and os targets, I don't see a good reason to do this.
@Sushisource feel free to re-open if you disagree.
