### ISSUE TITLE
Improve error message: 'foo' is not a function

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#375]
### Problem

When a Worker doesn't have the right Workflow code, it returns a result with an error message that says eg [`'progress' is not a function`](https://user-images.githubusercontent.com/251288/140634770-d4c6d5bc-adc2-4d5e-bdaa-9214231e3836.png) from https://github.com/temporalio/samples-typescript/issues/56.

### Solution

Instead, say something like:

```
The Worker process that picked up this task doesn't have a Workflow function named 'progress' in its bundle. For more information and possible causes, see: 

[docs URL]
```

so that in the future we can easily update the wiki page, and users of old versions of the SDK will see the updated page.

The docs page could say:

```
The Worker process that picked up this task doesn't have a Workflow function named 'foo' in its bundle. 
The issue might be:

- There's a typo in the Workflow function name.
- The Workflow function isn't exported.
- The entry point (`workflowsPath`) is incorrect.
- You have more Worker processes than you realize polling on the 'tutorial' queue. For instance, a process in another shell or in the background that has an old version of the Workflow code bundle or that's from a different Temporal project. You can check with `ps` or `tctl tq desc --tq tutorial`.
```

Migrated from #359

**Comment by bergundy** [comment]
Let's just list the functions that are exported
