### ISSUE TITLE
Improve error message: Workflow executionsRow not found

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#377]
### Is your feature request related to a problem? Please describe.

In [this scenario](https://github.com/temporalio/samples-typescript/issues/56), the error from the Worker that had the correct code was:

```
Task not found when completing: status: NotFound, message: "Workflow executionsRow not found."
```

### Describe the solution you'd like

 Say what's going wrong in the Worker at a higher level and suggest possible reasons.
 
 Migrated from #359

**Comment by bergundy** [comment]
This is a problem with the server AFAICT, I think you get a different error message if you use postgres instead of cassandra.
