### ISSUE TITLE
[Bug] "npm install" fails on windows, msvc 2017, ...

### ISSUE THREAD

**Issue by cons0l3** [temporalio/sdk-typescript#379]
Hi all,

I am coming from trying out the temporial samples for typescript and have filed a [bug](https://github.com/temporalio/samples-typescript/issues/61#issue-1050816961) over there.

After installing all dependencies as described in the readme of this project, running of `npm install` fails on windows 10, msvc 2017, node 16, rust 1.56.

I could identify three issues:
1) packages/core-bridge package.json build-rust script is not cross OS
2) core-bridge scripts/build.js calls a cargo-cp-artifact via OS spawn, which is not cross OS
3) packages/worker compile throws:
```
npm ERR! Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "-m" hinzufügen.
npm ERR!   workflow-isolate-extension.cc
npm ERR! ~\my-project-name\node_modules\isolated-vm\src\lib\thread_pool.h(17,55): warning C4003: Nicht genügend Argumente für den Aufruf des funktionsähnlichen Makros "max". [~\my-project-name\node_modules\@temporalio\worker\build\temporalio-workflow-isolate-extension.vcxproj]       
npm ERR! ~\my-project-name\node_modules\isolated-vm\src\lib\thread_pool.h(17,55): error C2589: "(": Ungültiges Token auf der rechten Seite von "::" [~\my-project-name\node_modules\@temporalio\worker\build\temporalio-workflow-isolate-extension.vcxproj]
npm ERR! ~\my-project-name\node_modules\isolated-vm\src\lib\thread_pool.h(17): error C2062: "unknown-type"-Typ unerwartet [~\my-project-name\node_modules\@temporalio\worker\build\temporalio-workflow-isolate-extension.vcxproj]
npm ERR! ~\my-project-name\node_modules\isolated-vm\src\lib\thread_pool.h(17,22): error C2059: Syntaxfehler: ")" [~\my-project-name\node_modules\@temporalio\worker\build\temporalio-workflow-isolate-extension.vcxproj]
```

### To Reproduce

setup Windows 10 (21H1), 
node 16 (via nvm install 16 && nvm use 16), 
rustup (cargo 1.56, rustc 1.56.1), 
vs 2017 (via choco visualstudio2017-workload-vctools visualstudio2017buildtools)

### Expected behavior

`npm install` and `npm test` run on Windows environment successfully (with the appropriate dependencies)

**Comment by cons0l3** [comment]
I have the required changes in [my fork](https://github.com/cons0l3/sdk-typescript) ready for a PR. Please advice, how to proceed.

**Comment by bergundy** [comment]
This is great, we've had an outstanding issue to support windows build for a while now #12.
PR will be very welcome.
