### ISSUE TITLE
[Bug] package initalizer errors on node 14

### ISSUE THREAD

**Issue by sw-yx** [temporalio/sdk-typescript#383]
### Describe the bug

as spoken with @lorensr https://temporaltechnologies.slack.com/archives/C01FT8U10GK/p1636621124237100

![image](https://user-images.githubusercontent.com/6764957/141377012-a4671ddd-94d4-43a4-902a-25b82416996c.png)

### To Reproduce

1. use node 14
2. `npx @temporalio/create@latest fooobar --sample nextjs-ecommerce-oneclick

**Comment by bergundy** [comment]
It's the tool replacing tsconfig in package json based on node version [here](https://github.com/temporalio/sdk-typescript/blob/409d015f6b674e84a5c0b8ee6ece151570afd8c3/packages/create-project/src/helpers/install.ts#L45).
We could just set the value to `^1.0.0`.

**Comment by lorensr** [comment]
Yeah, we could either make sure all the samples have `^1.0.0` in `package.json` or have `create` overwrite whatever's there with `[version]@^1.0.0`. latter more foolproof

**Comment by bergundy** [comment]
@lorensr I think this was fixed a while back, can you confirm?

**Comment by lorensr** [comment]
It works now. (samples have `^1.0.0` in `package.json`)
