### ISSUE TITLE
Fix broken init-from-verdaccio in node 14 and enable jobs in CI

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#393]
Disabled by @cretz in #385

**Comment by mjameswh** [comment]
Need to add node 14 and 18 to [the matrix for test-npm-init](https://github.com/temporalio/sdk-typescript/blob/main/.github/workflows/ci.yml#L196-L215).

**Comment by mjameswh** [comment]
WIP in #1003

**Comment by mjameswh** [comment]
Completed in #1003
