### ISSUE TITLE
[Feature Request] Update users on their Workflow Execution progress in the shell 

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#407]
### Is your feature request related to a problem? Please describe.

There are various types of issues that currently require viewing the web console to debug. For instance, as @JoshuaKGoldberg reported, an uncaught error in an Activity results in a hanging `npm run workflow` and no Worker output.

### Describe the solution you'd like

Give the user more information in the shell on what's happening.

During `worker.run()`, if `NODE_ENV` isn't `staging|production`, logging progress updates like:

```
Polling for tasks on queue "tutorial"
Starting execution of `example` workflow with:
  ID: 'my-business-id'
  Arguments:  ['Temporal']
Calling activity `greet` with args: 'Temporal'
Activity failed with:
  Error: test
  Error
    at Activity.greet [as fn] (/Users/me/gh/samples-typescript/hello-world/src/activities.ts:3:9)
Calling activity `greet` with args: 'Temporal' (attempt #2)
Activity failed with:
  Error: test
  Error
    at Activity.greet [as fn] (/Users/me/gh/samples-typescript/hello-world/src/activities.ts:3:9)
```

### Additional context

Related: https://github.com/temporalio/sdk-typescript/issues/305

**Comment by bergundy** [comment]
We recently added logging interceptors so the default SDK logs should be much more informative.
I think we can close this.
