### ISSUE TITLE
[Feature Request] Make binary the default protobuf data converter

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#435]
### Is your feature request related to a problem? Please describe.

Currently, we follow the Go SDK's default data converter encoding order, which puts JSON first.

https://github.com/temporalio/sdk-go/blob/5e5645f0c550dcf717c095ae32c76a7087d2e985/converter/default_data_converter.go#L28

### Describe the solution you'd like

Putting binary first would be more efficient.

### Additional context

Change should be made in all SDKs at the ~same time, so that users who use multiple SDKs and depend on the ordering matching can update all SDKs at the same time.

### Blocked by:

- Java SDK hasn't yet implemented a binary protobuf payload converter. https://github.com/temporalio/sdk-java/blob/0da3149c8eb16454c30fb7bda32d28f2539f3f3c/temporal-sdk/src/main/java/io/temporal/common/converter/DefaultDataConverter.java#L44-L49
- Temporal UI doesn't yet decode binary protobuf messages

**Comment by cretz** [comment]
I disagree with this change as I find that the clarity of JSON outweighs the slight efficiency of it. UI is not the only place payload bytes may be viewed. Is this solving an efficiency problem that exists? And by "efficiency" are you referring to storage size only or serialization speed as well? If storage size is the only concern, there are other potential options too.

**Comment by lorensr** [comment]
This is a suggestion from @bergundy. I know of no users with such an issue. I imagine it's not about a *problem* and more an impulse toward reducing resources used/load in the system—I think mainly lower storage space, but there might also be small improvements in network transfer time and serialization speed. 

I'm not familiar with the other places users view payloads, but if it's a common occurrence, I like JSON. My personal preference is usually DX over efficiency.
