### ISSUE TITLE
[Feature Request] Provide/use default retry policy 

### ISSUE THREAD

**Issue by zomble** [temporalio/sdk-typescript#440]
### Is your feature request related to a problem? Please describe.

When omitting a retry policy on an activity and the activity fails the workflow will fail with:

Activity task timed out and retryState: RetryPolicyNotSet

Which is correct if there isn't a retry policy. However ActivityOptions.retry comments talks about using server-defined default. Which is mentioned a lot through temporal docs, and other temporal SDK's.

### Describe the solution you'd like

Use the same default values the golang sdk does? Or what is described here: https://docs.temporal.io/docs/content/what-is-a-retry-policy/

**Comment by sw-yx** [comment]
this is either a temporary bug, or you are writing some funky code which you should add to your issue. many of our code samples, including hello world, do not specify retry policy, therefore relying on default retry policy. this is a very basic thing so if you found a bug we need a repro here. can you share some code, or a minimal repro?

**Comment by zomble** [comment]
Hey, after a sleep, and rereading the history, and playing around. A default policy is indeed being set, and it does match the default policy.
