### ISSUE TITLE
[Bug] Retry policy intervals get rounded down to the second

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#441]
Passing the following activity options:
```js
{
  retry: { initialInterval: "500ms" },
}
```

Produces the following result on the server:
```json
{
  "retryPolicy": {
    "nonRetryableErrorTypes": [],
    "initialInterval": {
      "duration": 0
    },
    "backoffCoefficient": 2,
    "maximumInterval": {
      "duration": 10
    },
    "maximumAttempts": 0
},
}
```

The SDK should probably round up the durations (first check what the other SDKs do here).

**Comment by mjameswh** [comment]
@bergundy I think this has been [resolved](https://github.com/temporalio/temporal/pull/1681) on server. Can we close?

**Comment by bergundy** [comment]
Not sure, can you please test?

**Comment by bergundy** [comment]
Need to verify that this is resolved

**Comment by mjameswh** [comment]
Validated in #1121.
