### ISSUE TITLE
[Feature Request] Improve default data converter

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#443]
### Is your feature request related to a problem? Please describe.

Users expect that when they return or pass a `Date`, they'll receive a `Date`. Instead, they receive an ISO string. 

[Repro](https://github.com/lorensr/samples-node/commit/8ec2ef538f276bd40d07fe021392865e20beb3bf)
[User feedback on slack](https://temporalio.slack.com/archives/C01DKSMU94L/p1641736724022000)

### Describe the solution you'd like

It would be helpful if they received `Date`s and other types lost during `JSON.parse`.

### Additional context

Slack discussions:
- https://temporalio.slack.com/archives/C01DKSMU94L/p1641779190022800?thread_ts=1641736724.022000&cid=C01DKSMU94L
- https://temporalio.slack.com/archives/C01DKSMU94L/p1645146054222929
- https://temporalio.slack.com/archives/C01DKSMU94L/p1648694634475969?thread_ts=1648684821.751929&cid=C01DKSMU94L

**Comment by bergundy** [comment]
I'm not convinced we should solve this issue.
Date isn't part of the JSON spec, there are of course ways to support it but we'd need a cross SDK solution.

**Comment by lorensr** [comment]
We could publish a custom data converter, and clearly in the docs say:

Note: the default Data Converter doesn't support Date, Y, Z, because it uses JSON for compatibility with the other SDKs. If you're only using the TS SDK (or can create equivalent custom data converters in your other SDK), you can use `MsgpackPayloadConverter`, which supports Date, Y, and Z:

```ts
import { MsgpackPayloadConverter } from `@temporalio/common/converter/msgpack`

...
```

**Comment by bergundy** [comment]
This is one (probably incomplete) approach where users can keep using JSON and have date serialization:

```js
// Unique prefix to add to date strings so they don't get mixed up with other ISO date strings
const prefix = "5062374f-3be6-4562-84f4-984a49678e13_date_";
function maybeSerializeDate(o) {
  if (o instanceof Date) {
    return `${prefix}${o.toJSON()}`;
  }
  return o;
}

function customJSONSerializer(o) {
  return JSON.stringify({ wrapped: o }, (k, v) => {
    if (Array.isArray(v)) {
      return v.map(maybeSerializeDate);
    }
    if (typeof v === "object" && v != null) {
      return Object.fromEntries(
        Object.entries(v).map(([e, vv]) => [e, maybeSerializeDate(vv)])
      );
    }
    return v;
  });
}

function customJSONDeserializer(s) {
  return JSON.parse(s, (k, v) => {
    if (typeof v === "string" && v.startsWith(prefix)) {
      return new Date(v.replace(prefix, ""));
    }
    return v;
  }).wrapped;
}

const s = customJSONSerializer({ d: new Date(), arr: [new Date()] });
console.log(s);
const revived = customJSONDeserializer(s);
console.log(revived);

```

**Comment by bergundy** [comment]
That would work, I'm wondering if it's even worth making it the default since this is proven to be a pain for users.
The caveat would be that it wouldn't be a polyglot solution.

**Comment by cretz** [comment]
> I'm wondering if it's even worth making it the default since this is proven to be a pain for users.

That pain exists in the JS JSON ecosystem as a whole. How would they send the JSON over `fetch` or use `Response.json()` to get JSON back if we were talking HTTP here? I vote we stick with the native JSON.stringify/JSON.parse by default and just make sure these other formats easily opt-in.

**Comment by lorensr** [comment]
I think the surprise comes from it not looking like you're making network requests, and the typing.

In workflow:

```ts
await activityFn(new Date())
```

Activity:

```ts
export activityFn(when: Date): number { 
  return when.getDate()
}
```

It compiles fine, but fails at runtime. 

Of course, they'll probably reach this point anyway, when trying to send instances of their own models: `activityFn(new User())` and calling User methods in the Activity. Wondering about a more general-purpose DC where the user registers all their classes, and it serializes and re-instantiates instances.

**Comment by cretz** [comment]
This is the cost of Temporal's abstractions. Just because we abstract that things need to be serialized doesn't mean we need to support all serializable things. What's next, `BigInt`? `RegExp`? I think default JSON w/ opt-in helpers is ideal.

> Wondering about a more general-purpose DC where the user registers all their classes, and it serializes and re-instantiates instances.

I think this is definitely reasonable for opt-in. `dataConverter = CustomClassDataConverter({ encoding: "my-encoding", classes: [MyClass1, MyClass2] })` where each class must have a no-arg constructor, static `deserialize`, and non-static `serialize`. But that isn't a default thing.

**Comment by bergundy** [comment]
I agree that we can't solve all of these cases, date is pretty standard so it might be worth an exception but, yeah, it's debatable if we should support it OOTB.

We can't take the class approach for serialization either BTW because we don't know have the function signature at runtime.
There was a proposal to add annotations to the SDK but it was rejected.

At some point we might want to add TS only features to get signatures at runtime.

**Comment by cretz** [comment]
> because we don't know have the function signature at runtime.

Why do you need the signatures in JS? On to-payload you check whether the object has `serialize` (or `temporalSerialize` or whatever), invoke it, and use the metadata to maintain the class type (`.constructor.name`). Then on from-payload, just to the lookup and invoke the matching `deserialize` static call on the class prototype. Yes it means JS users can pass something that doesn't have `serialize`, but such is life in untyped JS.

**Comment by lorensr** [comment]
Would like to say early on in docs:

When building a TypeScript-only project (one where all the Clients and Workers use the TS SDK, versus a mix of the different language SDKs), we recommend using `EjsonCompositePayloadConverter`, which supports:

- Dates (`Date`)
- Binary (`Uint8Array`)
- Special numbers (`NaN`, `Infinity`, and `-Infinity`)
- Regular expressions (`RegExp`)

as well as custom types.

```ts
// payload-converter.ts
import { EjsonCompositePayloadConverter } from '@temporalio/common/lib/ejson'
export const payloadConverter = new EjsonCompositePayloadConverter()

// data-converter.ts
export const dataConverter = { payloadConverterPath: require.resolve('./payload-converter') }

// worker.ts
import { dataConverter } from './data-converter.ts'
const worker = await Worker.create({
  dataConverter,
  ...
});

// client.ts
import { dataConverter } from './data-converter.ts'
const client = new WorkflowClient(new Connection().service, {
  dataConverter,
});
```

Or could simplify, for cases in which codecs aren't needed, with:

```ts
// data-converter.ts
import { EjsonDataConverter } from '@temporalio/common/lib/ejson'
export const dataConverter = new EjsonDataConverter()

// worker.ts
import { dataConverter } from './data-converter.ts'
const worker = await Worker.create({
  dataConverter,
  ...
});

// client.ts
import { dataConverter } from './data-converter.ts'
const client = new WorkflowClient(new Connection().service, {
  dataConverter,
});
```

---

This would involve adding the EJSON sample to `packages/common`: 

https://github.com/temporalio/samples-typescript/tree/main/ejson

and documenting how to use `addType`:

![image](https://user-images.githubusercontent.com/251288/163727292-aba140b3-b2dd-4910-966d-0df0560fb8d5.png)

**Comment by bergundy** [comment]
@lorensr that would be a good approach for TS only, I'm wondering if there's a better cross language solution or if we even need one if we have protobuf DCs.

**Comment by bergundy** [comment]
We're not doing this for now, let's close to avoid stacking up issues
