### ISSUE TITLE
[Bug] workflows wont launch on Windows if project folder starts with 'n'

### ISSUE THREAD

**Issue by yoDon** [temporalio/sdk-typescript#450]
### What are you really trying to do?

Renaming a project folder on Windows causes `npm run dev` to succeed or fail in the temporal worker launcher depending on whether the first letter of the directory name is an `n`. This issue prevents the nextjs-ecommerce-oneclick sample from running on Windows, but if you rename the folder to (for example) ecommerce-nextjs-oneclick the sample runs correctly under Windows.

### Describe the bug

When a project directory starts with an n, (like nextjs-ecommerce-oneclick in the samples-typescript repo), the code in [start:worker] on Windows incorrectly constructs the absolute path to workflows.js leaving out the slash between the project directory (nextjs-ecommerce-oneclick) and the parent of the project directory (samples-typescript) because it's treating the \ windows directory separator character and the n at the start of the project directory name as an offending \n to be stripped out (both the \ and the n are stripped from the constructed path).

### Minimal Reproduction

You can see this issue for example on a fresh clone of the samples-typescript repo when trying to run the nextjs-ecommerce-oneclick sample on Win11 running under Windows rather than under WSL. Renaming the nextjs-ecommerce-oneclick folder to ecommerce-nextjs-oneclick works around the issue and allows `npm run dev` to run without issue.

The error message is of the form:
```
[start:worker] 2022-01-24T00:52:35.620Z [ERROR] ERROR in ../../../../src/main.js
[start:worker] 2022-01-24T00:52:35.620Z [ERROR] Module not found: Error: Can't resolve 'C:\Path1\Path2\samples-typescriptextjs-ecommerce-oneclick\temporal\lib\workflows.js' in '/src'
```

If you look at the mangled path in the error message, you'll see something has incorrectly stripped the two characters `\n` from the desired `samples-typescript\nextjs-ecommerce-oneclick` leaving the malformed `samplestypescriptextjs-ecommerce-oneclick`.

### Environment/Versions

I'm seeing this issue under Windows 11 but I suspect it impacts all versions of Windows. WSL does not exhibit this issue because it does not use `\` as a path separator.

**Comment by yoDon** [comment]
As an additional, possibly related path-mangling issue, when I try to run under Windows a WIP sample from @lorensr at https://github.com/lorensr/next.js in the branch update-temporal and folder examples/with-temporal, I see an error message that looks like something is prepending a `/` in front of a path that starts with `C:`, resulting in an invalid `/C:` drive specifier.

For that repo, you need to `npm i` and then launch three terminals running

- `npm run dev`
- `npm run build:worker.watch` (there's a typo in the project readme, this is the correct command)
- `npm run start:worker` (again there's a typo in the project readme, the readme suggests `-`'s where there should be `:`'s)

**Comment by mjameswh** [comment]
This is an issue in [dedent](https://github.com/dmnd/dedent/issues/34). And according to [dedent's code](https://github.com/dmnd/dedent/blob/77673fef42c0374e744df868ba1b2829a5aa4781/dedent.js#L45-L49), the author sees this as a feature, not a bug.

I think the correct solution would be to replace `dedent` by some alternative (eg. [ts-dedent](https://www.npmjs.com/package/ts-dedent)).
