### ISSUE TITLE
[Bug] serverNameOverride in tlsConfig does not have expected effect on grpc request

### ISSUE THREAD

**Issue by jbreiding** [temporalio/sdk-typescript#455]
### What are you really trying to do?

Use SNI with nodejs sdk that sends the correct grpc authority header.

### Describe the bug

Understanding how the go-sdk allows for SNI to be configured for clients and following the similar documentation:

nodejs
https://nodejs.temporal.io/api/interfaces/common.tlsconfig/#servernameoverride

go
https://pkg.go.dev/go.temporal.io/sdk@v1.12.0/internal#ConnectionOptions

the go sdk correctly sets SNI and for grpc this means the authority header.

nodejs does not update the authority header when setting the serverNameOverride.
This is visible from grpc verbose logging.

### Minimal Reproduction

@bergundy has helped with reproducing and also identified a configuration that does work correctly.

```
  const connection = new Connection({
    address,
    tls: {
      clientCertPair: {
        crt: fs.readFileSync(clientCertPath),
        key: fs.readFileSync(clientKeyPath),
      },
    },
    channelArgs: { 'grpc.default_authority': serverNameOverride },
  });
  await connection.untilReady();
```
### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

nodejs client connecting to temporal-cloud hosted namespace.

### Additional context

Bringing this issue to attention to try and bring configuration consistent across sdk languages if possible.

**Comment by bergundy** [comment]
Apparently Rust Core needs extra parameters to add the authority header.
This functionality isn't exposed to TS.
