### ISSUE TITLE
[Feature Request] Add SAGA helpers?

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#456]
[SAGA](https://microservices.io/patterns/data/saga.html) helpers are included in [Java](https://github.com/temporalio/samples-java/blob/main/src/main/java/io/temporal/samples/bookingsaga/TripBookingWorkflowImpl.java) and [PHP](https://github.com/temporalio/samples-php/blob/master/app/src/BookingSaga/TripBookingWorkflow.php) SDKs.

More info: https://temporaltechnologies.slack.com/archives/C01FT8U10GK/p1641244942124700

**Comment by sw-yx** [comment]
i think worth it for parity and marketing

**Comment by cretz** [comment]
Can probably be done in samples instead of shipping the helpers

**Comment by sw-yx** [comment]
coinbase-ruby has them as well. ultimately just need to see how nontrivial a good implementation is. we're not above providing sugar api's if it is a pattern we want to encourage

**Comment by bergundy** [comment]
Decided not to do this for now, we'll reopen if we see demand.
