### ISSUE TITLE
[Bug] Fix & document which errors cause Workflow Execution failure

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#459]
Errors list: https://docs.temporal.io/docs/typescript/handling-failure#failure-classes-reference

Currently, throwing `TemporalFailure` or `ApplicationFailure` with `nonRetryable: true or false` inside a Workflow results in a `WorkflowExecutionFailed` event. I imagine at least in the `nonRetryable: false` case, and perhaps `TemporalFailure` and others, it should just be a `WorkflowTaskFailed` event. It's a `WorkflowTaskFailed` event when a plain object or `Error` instance is thrown.

**Comment by bergundy** [comment]
Throwing a TemporalFailure from workflow code should fail the workflow.
This is by design.

**Comment by lorensr** [comment]
Oh, retry policy is for `WorkflowExecutionFailed`s, not for `WorkflowTaskFailed`, got it. I misread TS docs.
