### ISSUE TITLE
[Feature Request] Log all errors in Worker

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#461]
If you `throw { }` or `throw new Error("error in workflow")` in a Workflow, the Worker outputs:

```
2022-02-02T17:41:23.579Z [WARN] [temporal_sdk_core::worker] Failing workflow activation run_id="c14a832e-ec8f-4d04-8019-013002e629da" failure=Failure { failure: Some(Failure { message: "Error: error in workflow", source: "TypeScriptSDK", stack_trace: "", cause: None, failure_info: None }) } 
```

But if you throw an instance of `TemporalFailure`, there's no output. 

Related:  https://github.com/temporalio/sdk-typescript/issues/407

**Comment by bergundy** [comment]
You're not supposed to directly throw `TemporalFailure`, it's up to the framework to do that.

I would add a logger for activity tasks and workflow activations.
We already have DEBUG logging, maybe we just need to increase the log level.

**Comment by lorensr** [comment]
> You're not supposed to directly throw TemporalFailure, it's up to the framework to do that.

I meant anything that has `TemporalFailure` as an ancestor.

![image](https://user-images.githubusercontent.com/251288/152223766-a8819ff6-2c31-4a7c-94bb-d3e4655910e3.png)

I took these docs to mean that I, as a user, should sometimes throw `ApplicationFailure`s and make my own errors by extending `TemporalFailure`. Also, I know that if I don't extend `TemporalFailure`, and just throw `new Error()`, I'll just fail the WorkflowTask, versus sometimes I might want to fail the WorkflowExecution.

**Comment by bergundy** [comment]
You're not supposed to subclass any of the failure classes, they have a one to one mapping with the proto definitions.
To fail the workflow execution you should throw an `ApplicationFailure`.

**Comment by sw-yx** [comment]
we should probably document that better

**Comment by lorensr** [comment]
Yep, will do
