### ISSUE TITLE
[Bug] Put more info into workflow activation failures

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#462]
## Problem

Currently, an Error thrown from a workflow results in this Worker output (& Web history):

```ts
throw new Error('error in workflow');
// Failing workflow activation...
// { message: "Error: error in workflow", source: "TypeScriptSDK", stack_trace: "", cause: None, failure_info: None }
```

And throwing an object results in:

```ts
throw { field: 'data' };
// Failing workflow activation...
// { message: "[object Object]", source: "TypeScriptSDK", stack_trace: "", cause: None, failure_info: None }
```

### Correct

- `failure_info`: Should be None in Error case. Use [subclass of `TemporalFailure`](https://docs.temporal.io/docs/typescript/handling-failure/#failure-classes-reference) to get this filled in.

### Change

- `message`: If thrown object isn't an Error, set `message = JSON.stringify(object)`. 
- `stack_trace`: Fill it in when Error is thrown (currently only filled in when `instanceof TemporalFailure`). When non-Error is thrown, log warning saying "we recommend throwing Errors so that you can see the stack trace".
- `cause`: When thrown error has a `cause` property, put a `Failure` here (currently only works when provided to constructor of `TemporalFailure` etc)
- `source`: Maybe be more specific, like `TypeScriptSDK > Worker > myWorkflowName`

## Related

@Sushisource We can't do anything about `throw new Error(object)`, since Node calls `toString()` on it before we get it:

![image](https://user-images.githubusercontent.com/251288/152221258-deac6db5-9ecf-4052-bf48-05a20b18ebba.png)

![image](https://user-images.githubusercontent.com/251288/152221306-24afdf58-b090-4100-a928-74d422eb3ac6.png)

**Comment by bergundy** [comment]
@lorensr is this still relevant?

**Comment by lorensr** [comment]
Yes. The first 3 bullets are fixed, but not the fourth:

- `source`: Maybe be more specific, like `TypeScriptSDK > Worker > myWorkflowName`

I guess if source is never Client, we can take out `Worker`. But could still differentiate between source being a Workflow, Activity, or other categories? Data converters?

--- 

Fixed: 

Now throwing an Error results in:

```
{
  "message": "error in workflow",
  "source": "TypeScriptSDK",
  "stackTrace": "Error: error in workflow\n    at example (/Users/me/gh/samples-typescript/hello-world/src/workflows.ts:12:8)\n    at Activator.startWorkflowNextHandler (/Users/me/gh/samples-typescript/src/internals.ts:88:16)\n    at Activator.startWorkflow (/Users/me/gh/samples-typescript/src/internals.ts:113:6)\n    at /Users/me/gh/samples-typescript/src/worker-interface.ts:219:35\n    at Object.activate (/Users/me/gh/samples-typescript/src/worker-interface.ts:223:2)\n    at evalmachine.<anonymous>:1:18",
  "cause": null
}
```

and throwing an object results in:

```
{
  "message": "{\"field\":\"data\"} [A non-Error value was thrown from your code. We recommend throwing Error objects so that we can provide a stack trace]",
  "source": "TypeScriptSDK",
  "stackTrace": "",
  "cause": null
}
```

and an Error with an Error `.cause`:

```
{
  "message": "error in workflow",
  "source": "TypeScriptSDK",
  "stackTrace": "Error: error in workflow\n    at example (/Users/me/gh/samples-typescript/hello-world/src/workflows.ts:12:17)\n    at Activator.startWorkflowNextHandler (/Users/me/gh/samples-typescript/src/internals.ts:88:16)\n    at Activator.startWorkflow (/Users/me/gh/samples-typescript/src/internals.ts:113:6)\n    at /Users/me/gh/samples-typescript/src/worker-interface.ts:219:35\n    at Object.activate (/Users/me/gh/samples-typescript/src/worker-interface.ts:223:2)\n    at evalmachine.<anonymous>:1:18",
  "cause": {
    "message": "cause error",
    "source": "TypeScriptSDK",
    "stackTrace": "Error: cause error\n    at example (/Users/me/gh/samples-typescript/hello-world/src/workflows.ts:13:12)\n    at Activator.startWorkflowNextHandler (/Users/me/gh/samples-typescript/src/internals.ts:88:16)\n    at Activator.startWorkflow (/Users/me/gh/samples-typescript/src/internals.ts:113:6)\n    at /Users/me/gh/samples-typescript/src/worker-interface.ts:219:35\n    at Object.activate (/Users/me/gh/samples-typescript/src/worker-interface.ts:223:2)\n    at evalmachine.<anonymous>:1:18",
    "cause": null
  }
}
```

**Comment by bergundy** [comment]
@lorensr I prefer closing this, at this point changing the source field would be a breaking change, since this field is checked when parsing stack traces, and I don't the proposed enhancement is significant.
