### ISSUE TITLE
[Bug] Allow registerErrors to be called multiple times

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#469]
### What are you really trying to do?

Support users who run TS SDK worker code multiple times.

### Describe the bug

When `native.registerErrors(errors)` is run a second time, you get this error:

```
thread '<unnamed>' panicked at 'Must call `into_inner` or `drop` on `Root` https://docs.rs/neon/latest/neon/sync/index.html#drop-safety', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-0.8.3/src/handle/root.rs:182:13
stack backtrace:
   0:        0x113d2bd14 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8483effd3e9ec544
   1:        0x113d45c0c - core::fmt::write::ha34752bcd39bca36
   2:        0x113d26304 - std::io::Write::write_fmt::hfc57a6e48a9ddae2
   3:        0x113d2d474 - std::panicking::default_hook::{{closure}}::he9aaba83dd453f35
   4:        0x113d2d054 - std::panicking::default_hook::hc87ff103cfd8260f
   5:        0x113d2dab4 - std::panicking::rust_panic_with_hook::hf890018b6cf19ef5
   6:        0x1135eb4bc - std::panicking::begin_panic::{{closure}}::hc28ceab4bf363482
   7:        0x1135eae34 - std::sys_common::backtrace::__rust_end_short_backtrace::h28965f507c5b3b3b
   8:        0x113d4df90 - std::panicking::begin_panic::hd003aa45410d163b
   9:        0x113666e88 - <neon::handle::root::Root<T> as core::ops::drop::Drop>::drop::h24d3c7b78d11aee1
  10:        0x11363f788 - temporal_sdk_typescript_bridge::errors::register_errors::h43400655bb40e232
  11:        0x1136d237c - neon::context::internal::Scope<R>::with::hf709c02593da6b84
  12:        0x11360845c - <neon::types::internal::FunctionCallback<T> as neon::types::internal::Callback<*mut neon_runtime::napi::bindings::types::Value__>>::invoke::he86aaaa185b14e07
Warning: neon::sync::Root leaked during a panic
 FAIL  tests/sequential/queues/addCronJob/producer.test.ts
  ● Test suite failed to run

    internal error in Neon module: Must call `into_inner` or `drop` on `Root` https://docs.rs/neon/latest/neon/sync/index.html#drop-safety

      at Object.<anonymous> (../../node_modules/@temporalio/worker/src/worker.ts:64:8)
      at Object.<anonymous> (../../node_modules/@temporalio/worker/src/index.ts:11:1)
```

Coming from: https://github.com/temporalio/sdk-typescript/blob/2232465a4f9b0cade28f0c21c2d7856053678728/packages/worker/src/worker.ts#L64

### Minimal Reproduction

Can make, lmk if helpful.

### Environment/Versions

`@temporalio/worker@0.17.2`

### Additional context

Reported by user: https://temporalio.slack.com/archives/C01DKSMU94L/p1644200062345539

**Comment by Sushisource** [comment]
Moved to TS SDK - this is a bug in the bridge (or higher, depending on your opinion), but not Core.

**Comment by lorensr** [comment]
Ah, I see, thanks. 

https://github.com/temporalio/sdk-typescript/blob/2232465a4f9b0cade28f0c21c2d7856053678728/packages/core-bridge/src/errors.rs#L64-L92

**Comment by Sushisource** [comment]
@lorensr Yup. That function should probably just use a `OnceCell<bool>` to lift the restriction it imposes on callers, and just do nothing if initialization has already occurred.

**Comment by SamSokolin** [comment]
Just want to leave a bit more detail on the specific use case triggering this issue. We have a "Module A" which depends on "@temporalio/worker" and a "Module B" which depends on "Module A". We have integration tests for "Module A" written using the Jest framework. In these integration tests, we would like to mock some (but not all) of the functions implemented in "Module B". Jest allows you to do this using the `requireActual` function:
https://jestjs.io/docs/jest-object#jestrequireactualmodulename

This function resolves the original module, and then also implements mocks for any specified functions. Since we want to mock "Module B"  differently for each suite of tests defined across our multiple Jest test files, we need to call `jest.mock` and `requireActual` multiple times.
