### ISSUE TITLE
[Feature Request] sleepUntil and UpdatableTimer utils

### ISSUE THREAD

**Issue by sw-yx** [temporalio/sdk-typescript#480]
### Is your feature request related to a problem? Please describe.

sleepuntil is needed because most users will probably have to write it themselves. especially when they try to do anything on a monthly basis https://github.com/temporalio/documentation/pull/902#pullrequestreview-883249803

updatabletimer is needed because the very next thing you want after setting a sleep is to change it midflight and right now its a pretty gnarly lift

perhaps we can modify the two apis so that they compose

### Describe the solution you'd like

already in the docs

**Comment by bergundy** [comment]
Leaving as samples for now, might make this an auxiliary lib eventually
