### ISSUE TITLE
[Feature Request] Wrap `WorkflowHandle.describe` output in a JS friendly object

### ISSUE THREAD

**Issue by sw-yx** [temporalio/sdk-typescript#482]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/6764957/154268047-326d3ca7-6afa-4975-84e2-aa3292c3605b.png)

![image](https://user-images.githubusercontent.com/6764957/154268147-37913d37-826e-4705-959c-4738f1ea4339.png)

![image](https://user-images.githubusercontent.com/6764957/154268222-1fe252f3-f37e-4b3f-acd0-dea6c9fb6e9f.png)

https://github.com/protobufjs/protobuf.js/pull/1258

**Comment by lorensr** [comment]
The toObject at bottom looks promising: https://github.com/protobufjs/protobuf.js/pull/1258#issuecomment-953476331

**Comment by bergundy** [comment]
We're going to wrap the output of `describe` in a JS friendly object instead of returning the raw grpc response.

**Comment by cretz** [comment]
Related: https://github.com/temporalio/sdk-features/issues/17
