### ISSUE TITLE
[Feature Request] Add all-method interceptors

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#488]
### Is your feature request related to a problem? Please describe.

The specific use case bringing this to mind is [handling all errors that flow through the client](https://github.com/temporalio/sdk-typescript/pull/484#issuecomment-1043352024).

### Describe the solution you'd like

The ability to define middleware for all communication with the client or worker. 

In Apollo Client, this is done with "Network Link"s, which makes it simple to write an `onError` handler:

https://www.apollographql.com/docs/react/api/link/apollo-link-error/

(Simpler than implementing all the methods in [WorkflowClientCallsInterceptor](https://typescript.temporal.io/api/interfaces/client.workflowclientcallsinterceptor/))

In Apollo Server, there's a dedicated middleware for errors: https://www.apollographql.com/docs/apollo-server/data/errors/#for-client-responses

**Comment by bergundy** [comment]
I don't think we've gotten any requests for this.
gRPC interceptors can achieve this IIUC.
Closing.
