### ISSUE TITLE
[Feature Request] Add WorkflowExecutionAlreadyTerminated

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#499]
For terminating an already-terminated workflow with the same ID

**Comment by lorensr** [comment]
Implemented similar to `WorkflowExecutionAlreadyStartedError`:

All references: https://github.com/temporalio/sdk-typescript/search?q=WorkflowExecutionAlreadyStartedError

Core logic: https://github.com/temporalio/sdk-typescript/blob/d54476f91493c4f33f1baedfedc77f69e9b8f829/packages/client/src/workflow-client.ts#L638-L650

Not sure what the status code or message will be for `AlreadyTerminated`, but we'll find out when we write a failing test.

**Comment by bergundy** [comment]
It'd just be not found and we already have that exception

**Comment by lorensr** [comment]
Thanks! @rupalivohra just wanted to make sure you saw ^
