### ISSUE TITLE
[Feature Request] Get proto comments in API docs

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#506]
### Is your feature request related to a problem? Please describe.

`protobufjs`-generated classes like:

https://typescript.temporal.io/api/classes/proto.temporal.api.workflowservice.v1.RecordActivityTaskHeartbeatByIdRequest

don't explain what the properties are beyond their types. 

### Describe the solution you'd like

It would be nice if the proto comments showed up:

https://github.com/temporalio/api/blob/eff34dc3a970cdbf3a10a7be827edf1b1528b125/temporal/api/workflowservice/v1/request_response.proto#L376

### Additional context

User question looking at current docs: https://temporalio.slack.com/archives/C01DKSMU94L/p1646242515967829

**Comment by Sushisource** [comment]
Protojs should do this translation properly. If we use `/** */` everywhere I'm worried that just breaks other languages. The Rust protobuf generator just turns `//` into `///` for example.

This should (in theory) be a fairly trivial contribution to make to `protobufjs` is we can do that and get it merged

**Comment by bergundy** [comment]
protobufjs isn't really maintained unfortunately, last commit was May 2021

**Comment by bergundy** [comment]
Also why would `/**` break other generators?

**Comment by Sushisource** [comment]
They may expect to see `//` or `/*` - assuming they support the latter, it may still work, but will add an extra `*` to every comment :)

**Comment by sw-yx** [comment]
alternative way to tackle this @lorensr  - can we make docusaurus link back to source code? kills a couple birds with one stone
