### ISSUE TITLE
[Bug] bundleWorkflowCode fails on "heavyweight" dependencies

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-typescript#516]
### Describe the bug

We have a workflow that depends on some interfaces/enums/basic utility functions in another module, which in turn depends on some "heavyweight" external package. That external package could actually be any package that depends on node's internal packages (such as filesystem, dns, buffer, url...), or any package that contains native code. When the workflow code gets bundled (either implicitly in `Worker.create(...)` or explicitly by calling `bundleWorkflowCode(...)`), **Webpack is sometime unable to determine that the external package is not actually required at runtime, and will therefore try to load it, causing a build failure.**

The error message looks something like the following (truncated to keep it readable; I actually get 46 errors). Note that in this case, the "external" package is `got` (an HTTP client, similar to `request`) and problematic dependencies are `process`, `util`, `url`, `dns` and others, which are all packages provided internally by node.

```
[ERROR] modules with errors 390 bytes [errors]
[ERROR]   node:process 39 bytes [built] [code generated] [1 error]
[ERROR]   node:util 39 bytes [built] [code generated] [1 error]
[ERROR]   node:url 39 bytes [built] [code generated] [1 error]
[ERROR]   + 7 modules
        ...
[ERROR] ERROR in ./node_modules/cacheable-lookup/source/index.js 10:4-18
[ERROR] Module not found: Error: Can't resolve 'dns' in '/Users/jwatkins/Development/temporal/bug-heavyweight-dependency-bundling/node_modules/cacheable-lookup/source'
[ERROR] resolve 'dns' in '/Users/jwatkins/Development/temporal/bug-heavyweight-dependency-bundling/node_modules/cacheable-lookup/source'
        ...
[ERROR]   Parsed request is a module
[ERROR]   using description file: /Users/jwatkins/Development/temporal/bug-heavyweight-dependency-bundling/node_modules/cacheable-lookup/package.json (relative path: ./source)
        ...
[ERROR]  @ ./node_modules/got/dist/source/core/options.js 10:0-47 28:25-40
[ERROR]  @ ./node_modules/got/dist/source/index.js 2:0-40 4:17-24 11:0-55 11:0-55 12:0-34 12:0-34
[ERROR]  @ ./src/api/client.ts 7:30-44
[ERROR]  @ ./src/api/index.ts 17:13-32
[ERROR]  @ ./src/temporal/myWorkflow.ts 4:16-39
[ERROR]  @ ./src/temporal/myWorkflow-entrypoint-caf2c449-bc91-46c7-9b6b-dc05043a9065.js
```

### Minimal Reproduction

See https://github.com/mjameswh/temporalio-sdk-typescript-issue-heavyweight-dependency-bundling for a workspace that demonstrate this issue.

Note that, in this specific case, the issue can easily be worked around by simply importing from `../api/models` instead of `../api/index` (in myWorkflow.ts). However, our actual use case spans multiple projects in a monorepo structure, and we have not yet found any simple, practical solution to this issue.

### Environment/Versions

- Temporal typescript-sdk version: 0.19.0-rc.1

### Solutions to be considered

- **Add [`target: 'node'`](https://webpack.js.org/configuration/target/) to bundleWorkflowCode's [webpack config](https://github.com/temporalio/sdk-typescript/blob/82351ccc69a5d3876e5b44d4860c20ec71cfca28/packages/worker/src/workflow/bundler.ts#L117).** Without this option, Webpack will simply not allow importing node's internal packages. In fact, by default, Webpack assume that you are bundling for a browser environment, which could cause some weird issues at some point in the future. Still, given that most of node's internal packages are unusable in isolated vm context, it is not clear if allowing these imports would actually help or just push issues a little bit father. It also does not resolve similar issues caused by packages that contains native code.

- **Allow users to specify a list of dependencies to be ignored.** For example, an optional property `ignoreModules` could be added to [`BundleOptions`](https://github.com/temporalio/sdk-typescript/blob/82351ccc69a5d3876e5b44d4860c20ec71cfca28/packages/worker/src/workflow/bundler.ts#L189). That list would be used to dynamically add values to Webpack's `resolve.alias` or `resolve.fallback` (ie. `{ "got": false }`). That would solve this specific issue and would be relatively easy to understand for most developers facing similar issues.

- **Allow users to apply more generic overrides to the Webpack config.** For example, an optional property `webpackConfigOverrides` could be added to `BundleOptions`. If it is there, that property would be merged with the default/calculated Webpack configuration. Alternatively, it could be an override function, which receive the default/calculated Webpack configuration, and returns the modified configuration (this is much more flexible, and easier from our point of view, more harder to work with for developers). This is for example [how Gatsby works](https://www.gatsbyjs.com/docs/how-to/custom-configuration/add-custom-webpack-config/). This approach would not only solve the current issue, but also provide a way to deal with many other very custom needs that developers may have (think of.. _Hey guys! We would like to use [`define`](https://webpack.js.org/plugins/define-plugin/) for our workflows_ 😄 ) However, this would be more complex for developers to use, and arguably, there are not that many things that can be customized in Temporal's Webpack build process without risking breaking things.

**Comment by bergundy** [comment]
Thanks for the detailed summary @mjameswh.

Have you tried any of the workarounds you've suggested successfully?
Seems like, as you're suggesting, `resolve.alias` and `resolve.fallback` would address this issue.

Up until now we've purposefully hidden any advanced webpack options because we consider webpack to be an implementation detail, for example, I know some user on our slack channel replaced webpack with esbuild and got dramatically faster builds.
I do understand that there are some advanced users that would like the extra power so we'd have to discuss how best to exposed this functionality.

**Comment by mjameswh** [comment]
Haven't started implementing any of this yet, though I have done something very similar to my second proposition on another project.

I'm highly confident that both propositions 2 and 3 can solve the issue we have right now. I just wanted to see first which (if any) would make sense to your team. I agree that this is somewhat lower level matters and I know that you want to avoid exposing developers to implementation details. That's exactly why I'm hesitating. But I also think that this issue will hurt more and more people as the typescript SDK get used in larger and larger projects, and that, in the end, developers might be exposed to even more complicated issues if there is no practical solution to this. 

Arguably, the `ignoreModules` approach would not be that much of an implementation detail... I think the very same option could also work in a esbuild bundling process (either using `--external` or an `onLoad` plugin). On a side note, I have to admit that I would be very interested in an esbuild bundler; our application have quite a few workflows already, and were planing to have many times more. I expect that bundling workflows could represent a significant time by the end of the project. I may give it a shot later on, but can't do this right now.

If that's good for you, I'll try to have something along the line of proposition number 2 tomorrow.

**Comment by sw-yx** [comment]
and you probably already saw this but just in case you havent, you can bundle code yourself and just specify `workflowBundle`: https://docs.temporal.io/docs/typescript/production-deploy#pre-build-code

**Comment by mjameswh** [comment]
@sw-yx Yes I know.

Actually, I was going to say to that I would add customization options only on the `bundleWorkflowCode()`/`BundleOptions` interface... That is, I think the `Worker.create(...)` function should _not_ include such feature, so most users would not even be exposed to this.

**Comment by lorensr** [comment]
Thanks James, I really appreciate the clarity and thoroughness of your issues & PRs 😊🙏

Personally in favor of the bundler-agnostic `ignoreModules`, although would like something more automatic / better DX, like ignoring all built-in Node modules by default. Issue with that is I'm not sure how to make clear what's happening when errors are thrown from the ignored modules actually being used (like `dns.resolve()` being run)? I guess we could replace `dns` with a file that had all the same exports but threw an informative error. But that only covers functions. Wonder if default-exporting a Proxy that errored on access to all properties would work? 😄

If we can't make that clear, then I think it would be nice if, instead of or in addition to this being logged:

`Module not found: Error: Can't resolve 'dns' in`

, we logged: 

```
Your Workflow code (or a library used by your Workflow code) is importing `dns`, a built-in Node module. Workflow code don't have access to built-in Node modules (in order to help enforce determinism). If your code just imports `dns` and doesn't use what it imports, you can add it to `BundleOptions.ignoreModules`. If your code uses what it imports, then you need to change the code or remove the library.

https://typescript.temporal.io/api/namespaces/worker/#bundleworkflowcode
```

>  I have to admit that I would be very interested in an esbuild bundler

Yay 😃💃

**Comment by mjameswh** [comment]
> I guess we could replace `dns` with a file that had all the same exports but threw an informative error. But that only covers functions. Wonder if default-exporting a Proxy that errored on access to all properties would work? 😄

Well... I don't think it would be that hard... Technically, we could add a stub module in modules-overrides that does exactly that, and then alias every node-internal packages to the path of that module. But I doubt this would really give the usability we're hopping for.

```
Your Workflow code (or a library used by your Workflow code) is importing `dns`, a built-in Node module. Workflow code don't have access to built-in Node modules (in order to help enforce determinism). If your code just imports `dns` and doesn't use what it imports, you can add it to `BundleOptions.ignoreModules`. If your code uses what it imports, then you need to change the code or remove the library.

https://typescript.temporal.io/api/namespaces/worker/#bundleworkflowcode
```

Now, that sounds like a great idea... IIRC, `resolve.fallback` can be a function, which is called with the name of the module being requested... I'll give it a try.

Still, let's not forget that it won't help with dependencies that contains native code...

**Comment by mjameswh** [comment]
After some research, I don't think it is desirable to ignore all Node built-in modules by default.

A few modules pose actually no issue at all (`util`, `punycode`, `path/posix`, `path/win32`, `buffer`...), or are very unlikely to pose actual issue in real life (`path` would pose an issue only if replaying a workflow on a different platform). For many others modules, only some functions are problematic, while other functions of the same package are not problematic AND could be arguably useful in workflows for some use cases; eg. `crypto` is likely to be non-deterministic when cyphering data (which might implies using a secure RNG), but should be deterministic in most other situations (including deciphering and validating hashes...)

I think we should allow node built-in modules, but report a warning indicating the list of found modules dependencies that are known to be potential issues. More over, that list could grow over time to include known popular external libraries that also pose issues (eg. native code) and/or that are probable marker of issues in how the workflow is designed (eg. `@temporalio/client`, `mysql`, `aws-sdk`, `axios`...).

**Comment by bergundy** [comment]
We will not allow node built-ins because we eventually want to support running untrusted workflow code.
That being said, we can allow injection of some of these node built-ins for users that don't want that feature.

There's more thought to be put in here though.

**Comment by mjameswh** [comment]
> We will not allow node built-ins because we eventually want to support running untrusted workflow code.

I totally agree.

Actually, forget about my previous comment, it was based on an incorrect understanding of my part.... I originally thought that `require` and node built-ins were accessible inside isolated environments, and that only a Webpack misconfiguration was preventing it from working. So my earlier argument was essentially that Webpack should not add _artificial_ restrictions, as this reduced usability without improving security and determinism (eg. one could do `eval('require(...)')` inside a workflow to work around a Webpack-level restriction). I backtracked on my previous opinion once I realized I had this fact wrong.
 
>That being said, we can allow injection of some of these node built-ins for users that don't want that feature.
>
>There's more thought to be put in here though.

I think there is a potential need here, but that's more hypothetical at this point. I can imagine that, at some point, one may report something like: "Can't bundle my workflow because it _legitimately_ needs access to the `foo` module". Think for example custom data converter that provides data encryption, using the `crypto` built-in module (haven't checked that, but I assume that custom data converters are loaded inside the workflows isolated environment...).

Still, there are very few node built-in modules that are likely to be used in such scenarios. `assert` is one of them, and it has already been handled using a stub module  [`assert` module](https://github.com/temporalio/sdk-typescript/blob/82351ccc69a5d3876e5b44d4860c20ec71cfca28/packages/worker/src/workflow/module-overrides/assert.ts). That seems like the way to go for such cases.

But that would be distinct issues...

**Comment by bergundy** [comment]
> I think there is a potential need here, but that's more hypothetical at this point. I can imagine that, at some point, one may report something like: "Can't bundle my workflow because it legitimately needs access to the foo module". Think for example custom data converter that provides data encryption, using the crypto built-in module (haven't checked that, but I assume that custom data converters are loaded inside the workflows isolated environment...).

So far I haven't seen a legitimate request to access node built-ins, we can offer that if needed.
As for custom data converters, encryption and compression should be done in `PayloadCodec`s which are run outside of the sandbox.
