### ISSUE TITLE
[Feature Request] Reduce size of aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#539]
### Is your feature request related to a problem? Please describe.

228 MB is too large:

```
cd packages/core-bridge/releases/
du -sh *
4.0K	__fig_post_prompt
 14M	aarch64-apple-darwin
228M	aarch64-unknown-linux-gnu
 15M	x86_64-apple-darwin
 13M	x86_64-pc-windows-msvc
 17M	x86_64-unknown-linux-gnu
```

### Describe the solution you'd like

Fix publish script

**Comment by bergundy** [comment]
Increased size was due to us building for this target on MacOS.
Need to automate this build.

**Comment by bergundy** [comment]
This was done already since we build for this target in GHA
