### ISSUE TITLE
[Feature Request] After `create`, give customized setup instructions

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#541]
With https://github.com/temporalio/samples-typescript/pull/107, the beginning of each `.post-install` message has:

![image](https://user-images.githubusercontent.com/251288/158491613-99a71a3a-56c9-43d2-b520-a4ffe112880a.png)

It would be nicer if we:

- Checked which platform, so we know which command to run to install
- Don't output part of the instructions if we:
  - See that `docker-compose` is already installed and docker daemon is running
  - See that Temporal Server is already running, or
  - See that Node version is already >= 14

**Comment by bergundy** [comment]
I think our package initializer is complex enough as is.
The custom template is more than enough imho.
Let’s close this.
