### ISSUE TITLE
[Bug] Windows test exists with code 1 without failures

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#552]
Sometimes on Windows this happens, where no tests fail, but exit code is 1:

[build-and-test (16, windows-latest)](https://github.com/temporalio/sdk-typescript/runs/5630121517?check_suite_focus=true#logs)

The only thing in the output that looks bad is this error, but it's intentional, and the test that causes it succeeds.

![image](https://user-images.githubusercontent.com/251288/159302964-781d3699-a27b-4442-b7fe-4d9cd803e5be.png)

**Comment by lorensr** [comment]
The next time it ran, it succeeded:

[build-and-test (16, windows-latest)](https://github.com/temporalio/sdk-typescript/runs/5630419601?check_suite_focus=true#logs)

but with 111 tests (vs the failing one had 110 tests). I sorted lines & diffed and the failing one is missing the line:

```
@temporalio/test:   √ replay » cancel-fake-progress-replay (3s)
```

![image](https://user-images.githubusercontent.com/251288/159334751-b08aa7b4-50cf-45bc-bb53-00594711d970.png)

**Comment by lorensr** [comment]
passing output:

```
@temporalio/test:   ✔ replay › cancel-fake-progress-replay-nondeterministic (2.2s)
@temporalio/test: 2022-03-21T18:47:44.678Z [WARN] [temporal_sdk_core::worker] Failing workflow activation run_id="a7e68cfc-0287-48dd-b86a-866caf5c9a73" failure=Failure { failure: Some(Failure { message: "WorkflowUpdateError { source: Nondeterminism(\"No command scheduled for event HistoryEvent(id: 10, Some(ActivityTaskCancelRequested))\"), run_id: \"a7e68cfc-0287-48dd-b86a-866caf5c9a73\" }", source: "", stack_trace: "", cause: None, failure_info: Some(ApplicationFailureInfo(ApplicationFailureInfo { r#type: "", non_retryable: false, details: None })) }) }
```

failing output:

```
@temporalio/test:   × Timed out while running tests
@temporalio/test:   1 tests were pending in lib\test-replay.js
@temporalio/test:   ( ) replay » cancel-fake-progress-replay-nondeterministic
```

**Comment by bergundy** [comment]
I haven't see this in a long time, I think it's fixed.
@lorensr?

**Comment by lorensr** [comment]
Haven't seen either
