### ISSUE TITLE
[Bug] WithWorkflowArgs is not exported

### ISSUE THREAD

**Issue by rupalivohra** [temporalio/sdk-typescript#557]
### What are you really trying to do?

I am using `WithWorkflowArgs` to get strong typing in a wrapper around the `SignalWithStart` client call.

### Describe the bug

This type used to be exported under @temporalio/common, but no longer is. It's also not available in @temporalio/client, which is the other place I'd expect it. Following the instructions from the [CHANGELOG](https://github.com/temporalio/sdk-typescript/blob/main/CHANGELOG.md#features-1), I'm opening this bug to track re-exporting the type.

![Screen Shot 2022-03-24 at 1 28 28 PM](https://user-images.githubusercontent.com/5040637/160004724-8d0ebc85-c98e-467e-9431-d942df7121c0.png)

### Environment/Versions

- OS and processor: MB Pro 2019, Monterey
- Temporal Version: 0.19.x
- Are you using Docker or Kubernetes or building Temporal from source? This fails during compilation

### Additional Context

For now, I'm doing: `import { WithWorkflowArgs } from '@temporalio/internal-workflow-common';`

**Comment by lorensr** [comment]
Thanks for reporting! ☺️
