### ISSUE TITLE
[Feature Request] Use options object for ApplicationFailure

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#562]
### Problem

Hard to know meaning of args when looking at call site, and you have to provide unnecessary ones to get to later ones you want to use:

![image](https://user-images.githubusercontent.com/251288/160212982-d291b1c2-6a79-4559-80c4-d65844173aef.png)

### Solution options

```ts
new ApplicationFailure('my message', {
  type: 'old-cookie', 
  nonRetryable: true, 
  cause: e
})
```

- Having `message` as first param matches `Error` constructor, but it's optional and sometimes I'd only use `type`. 
- `nonRetryable`: having a negated boolean name feels awk to me

So I'd prefer:

```ts
new ApplicationFailure({
  message: 'my message',
  type: 'old-cookie', 
  retryable: false, 
  cause: e
})
```

And:

```ts
ApplicationFailure.nonRetryable({
  message: 'my message',
  type: 'old-cookie', 
  cause: e
})
```

**Comment by bergundy** [comment]
It's way too late to change now IMO, can we close this?
