### ISSUE TITLE
[Bug] Process exits when calling client.start or client.execute

### ISSUE THREAD

**Issue by danielrearden** [temporalio/sdk-typescript#580]
### What are you really trying to do?

We're dealing with some DNS errors in our K8s cluster and wanted to understand how the client would behave if it couldn't resolve the provided address. From what we were seeing in our traces, it looked like errors encountered when calling `start` weren't actually causing the Promise to reject. So I went to test the behavior locally and encountered this issue.

### Describe the bug

Setting the `Connection` address to an address that won't resolve (for example `does-not-exist` or `does-not-exist:7233`) causes subsequent `start` and `execute` calls from the client to exit the process. The exit processes with a 0 status code.

In the reproduction below, you can see that no errors are thrown and no additional logs are generated after the initial "Starting workflow..." one. The process literally just exits.

### Minimal Reproduction

https://github.com/danielrearden/samples-typescript/blob/client-bug/hello-world/src/client.ts

### Environment/Versions

- OS and processor: macOS 12.3
- Temporal Version: @temporalio/client@0.20.0
- Are you using Docker or Kubernetes or building Temporal from source? Docker

### Additional context

If the host _can_ be resolved but a connection can't be established, eventually the call rejects with a `ServiceError`, which is the same behavior I would expect.

**Comment by danielrearden** [comment]
Update: settings `interceptors` to an empty array causes the call to immediately fail with a `ServiceError` as expected, so the issue appears to be specific to something inside `makeGrpcRetryInterceptor`.

**Comment by bergundy** [comment]
I see the problem and the fix is pretty trivial.
We’re changing the connection constructor to an async factory soon so this will be a non issue when that change lands.

**Comment by bergundy** [comment]
Looks like this doesn't happen anymore, probably solved by upgrading grpc-js
