### ISSUE TITLE
[Feature Request] Add more detailed error/stack to TransportError errors

### ISSUE THREAD

**Issue by rcarton** [temporalio/sdk-typescript#582]
It's hard to troubleshoot `TransportError`s because they can be associated with any kind of problems when establishing a connection to a Temporal cluster. 

Would it be possible to surface lower level information? To help the user troubleshoot what may have caused the error.

Eventually this was my problem: https://docs.temporal.io/docs/typescript/production-deploy/#install-ca-certificates-for-tls-transport

**Comment by lorensr** [comment]
Great idea, thanks!

**Comment by lorensr** [comment]
Hah, look what I just ran into 😆

<img width="583" alt="image" src="https://user-images.githubusercontent.com/251288/162887533-a1b4c5b7-6a4d-48b6-a32a-dda071acc65b.png">

**Comment by lorensr** [comment]
Error object wasn't very helpful!

<img width="431" alt="image" src="https://user-images.githubusercontent.com/251288/162888882-977c11ad-ed7d-4aec-b484-3b9a7257cdab.png">

<img width="584" alt="image" src="https://user-images.githubusercontent.com/251288/162888893-92b5a1a1-114b-4950-a1ff-f234b40686f7.png">

In addition to the slim ca-certificates issue linked in OP, I got TransportError in other circumstances. I think when I had the wrong remote Server address, wrong long Server address (default `localhost:7233` doesn't work—need `host.docker.internal:7233`) or when I had wrong or absent certs.
