### ISSUE TITLE
[Bug] Runtime logger isn't used by webpack bundler

### ISSUE THREAD

**Issue by airhorns** [temporalio/sdk-typescript#604]
### What are you really trying to do?

I'm trying to override the runtime logger to use existing logging infrastructure for formatting and structuring, and it works great for logs generated by the worker and sinks and whatnot, but the logs generated by webpack when building the workflow bundle do not flow through my logger. 

### Describe the bug

Logs are emitted using `console.error`, instead of the custom entry function passed to the `DefaultLogger` passed to `Runtime.install`

### Minimal Reproduction

```typescript
// install the runtime with a custom logger
Runtime.install({
  logger: new DefaultLogger("INFO", (entry) => {
    console.log("here's a prefix:", entry)
  })
});

// then boot a worker with workflowsPath so webpack builds the bundle
await Worker.create({
  workflowsPath: require.resolve(...)
});

// note how webpack logs are not prefixed
```

### Environment/Versions

- OS and processor: macOS 12.1.3
- Temporal Version: temporalite + `@temporalio/worker@0.20.2`
- No docker, no k8s

### Additional context

Thanks!

**Comment by bergundy** [comment]
Thanks for reporting, we'll look into it

**Comment by vkarpov15** [comment]
I took a look and I'm unable to repro this issue. Running the below code:

```ts
import { Runtime, DefaultLogger, Worker } from '@temporalio/worker';
import * as activities from './activities';

async function run() {
  // Step 1: Register Workflows and Activities with the Worker and connect to
  // the Temporal server.
  Runtime.install({
    logger: new DefaultLogger("INFO", (entry) => {
      console.log("here's a prefix:", entry)
    })
  });

  const worker = await Worker.create({
    workflowsPath: require.resolve('./workflows'),
    activities,
    taskQueue: 'hello-world',
  });
  // Worker connects to localhost by default and uses console.error for logging.
  // Customize the Worker by passing more options to create():
  // https://typescript.temporal.io/api/classes/worker.Worker
  // If you need to configure server connection parameters, see docs:
  // https://docs.temporal.io/docs/typescript/security#encryption-in-transit-with-mtls

  // Step 2: Start accepting tasks on the `tutorial` queue
  await worker.run();
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
```

gives me the below output:

```
$ npm start

> temporal-hello-world@0.1.0 start
> ts-node src/worker.ts

  2022-06-04T00:22:18.462740Z  INFO temporal_sdk_core::worker: Initializing worker, task_queue: hello-world

here's a prefix: {
  level: 'INFO',
  message: 'asset \x1B[1m\x1B[32mmain.js\x1B[39m\x1B[22m 518 KiB \x1B[1m\x1B[32m[emitted]\x1B[39m\x1B[22m (name: main)',
  meta: undefined,
  timestampNanos: 1654302138979125441n
}
here's a prefix: {
  level: 'INFO',
  message: 'runtime modules 937 bytes 4 modules',
  meta: undefined,
  timestampNanos: 1654302138980769534n
}
here's a prefix: {
  level: 'INFO',
  message: 'modules by path \x1B[1m./node_modules/@temporalio/\x1B[39m\x1B[22m 140 KiB',
  meta: undefined,
  timestampNanos: 1654302138980860746n
}
```

It looks like Webpack output is running through the logger. Am I missing something?

**Comment by bergundy** [comment]
Going over the code, it looks like we do pass the logger in (and confirmed by @vkarpov15 - thanks).
The only case where the runtime logger isn't used is if you manually call `bundleWorkflowCode` which I think is acceptable since it doesn't require instantiating the Rust Core runtime.

**Comment by airhorns** [comment]
Thanks folks! I think I did notice that this got fixed somewhere along the way as well -- forgot to come over here and close this, my bad!
