### ISSUE TITLE
[Bug] Heap out of memory on `setHandler(signal, undefined)`

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-typescript#612]
### What are you really trying to do?

In many of our workflows, we need to wait for a single occurrence of a given signal before execution before we continue with following steps, similar to the `workflow.GetSignalChannel(ctx, signalName).Receive(ctx, &args)` pattern in Go.

The TypeScript SDK does not yet offer an exact replacement for this idiom. It is obviously possible to register a signal handler, which sets a boolean value, and then `await condition(...that boolean variable...)`. However, this pattern results in consuming _all_ occurrences of the signal, where we would expect it to consume _only the first_ occurence of the signal.

For this reason, we constructed the function shown below. It has the particularity that, after receiving the expected signal, it clears up the signal handler, by calling `setHandler(signal, undefined)`. This is done from _inside_ the signal handler in order to ensure that only one "occurence" of the signal is consumed by the handler. It works great, except for the problem described in this ticket.

Here is the code:

```
export async function waitForSignal<T extends SignalDefinition>(
    signal: T,
    timeout?: number | string,
): Promise<ExtractSignalArgs<T> | false> {
    let signalReceived = false;
    let returnArgs: ExtractSignalArgs<T> | false = false;

    setHandler(signal, ((...inputArgs: ExtractSignalArgs<T>): void => {
        signalReceived = true;
        returnArgs = inputArgs;
        clearHandler(signal); // This one is required to ensure that we consume only one occurence of the signal
    }) as Handler<void, ExtractSignalArgs<T>, T>);

    await condition(() => signalReceived, timeout as number);
    clearHandler(signal); // This one is required in case we timed out

    return returnArgs;
}

export function clearHandler<T extends SignalDefinition>(signal: T) {
    setHandler(signal as SignalDefinition<[]>, undefined as unknown as Handler<void, [], T>);
}
```

### Describe the bug

Calling `setHandler(signal, undefined)` while there are buffered signals occurrences for that name results in heap out of memory.

The problem 

### Minimal Reproduction

```
workflow() {
    await sleep('30s');  // During this pause, send this workflow the given signal a few times
    setHandler(signal, () => {
        setHandler(signal, undefined);
    })
}
```

This results in a Node crash with the following message: `FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory`.

### Analysis

Our analysis demonstrated that the problem is due to a subtile interaction between `setHandler` and `signalWorkflow`. After changing the handler, `setHandler` iterates over buffered signals and try to process each one. To do so, it calls `signalWorkflow`, which checks if a handler for that signal is actually defined. Now, since our handler is undefined, `signalWorkflow` instead push the signal occurence to the corresponding signal buffer. Turns out that this is the very same array over which `setHandler` is iterating at that very same time.

```
// in workflow.ts
export function setHandler<Ret, Args extends any[], T extends SignalDefinition<Args> | QueryDefinition<Ret, Args>>(
  def: T,
  handler: Handler<Ret, Args, T>
): void {
  if (def.type === 'signal') {
    state.signalHandlers.set(def.name, handler as any);
    const bufferedSignals = state.bufferedSignals.get(def.name);
    if (bufferedSignals !== undefined) {
      for (const signal of bufferedSignals) {
        state.activator.signalWorkflow(signal);
      }
      state.bufferedSignals.delete(def.name);
    }

// in internals.ts
  public signalWorkflow(activation: coresdk.workflow_activation.ISignalWorkflow): void {
    ...

    const fn = state.signalHandlers.get(signalName);
    if (fn === undefined) {
      let buffer = state.bufferedSignals.get(signalName);
      if (buffer === undefined) {
        buffer = [];
        state.bufferedSignals.set(signalName, buffer);
      }
      buffer.push(activation);  // <-- PUSH
      return;
    }

    ...
  }
```

### Proposed solutions

I propose moving the `state.bufferedSignals.delete(def.name)` line before the `for` loop. As an optimization, it would also be useful not to process buffered signals if the new handler is `undefined`.

```
    if (bufferedSignals !== undefined && handler !== undefined) {
      state.bufferedSignals.delete(def.name);
      for (const signal of bufferedSignals) {
        state.activator.signalWorkflow(signal);
      }
    }
```

**Comment by bergundy** [comment]
Interesting, thanks for the report.
Do you want to fix this or should I? The proposed fix should work.

**Comment by mjameswh** [comment]
@bergundy Sure, I can submit a PR for this tomorrow.

If you don't mind, I would also modify the `setHandler` function signature to make it clears that the `handler` can be set to `undefined`. We are certainly not the only ones thats sees use cases for this.

> bergundy added this to the 1.0 milestone

So we're moving toward 1.0? Great to hear! Congrats to the team! 🎉 🎉 🎉

**Comment by bergundy** [comment]
Thanks again @mjameswh!

Feel free to update the signature for `setHandler` too.
