### ISSUE TITLE
[Bug] `ShutdownError: Core is shut down` error when running in jest 

### ISSUE THREAD

**Issue by airhorns** [temporalio/sdk-typescript#614]
### What are you really trying to do?

Integrate temporal workflows into an existing TypeScript application tested using jest

### Describe the bug

I am able to create and complete workflows in one jest test file using helpers similar to those found in `sdk-typescript`'s repo, but as soon as I start using the client / workers in multiple jest test files, I get strange `ShutdownError: Core is shut down` or `ShutdownError: Core is shut down and there are no more workflow replay tasks` errors. These errors seem to occur after the workers have successfully completed open workflows and activities, and seem to happen somewhat inconsistently.

### Minimal Reproduction

Find a repro here: https://github.com/airhorns/temporal-jest

You must run multiple test files at once to trigger the issue.

### Environment/Versions

- OS and processor: macOS 12.3.1, Intel Core i7
- Temporal Version: temporalite with `@temporalio/worker@0.21.1`
- No docker, k8s

### Additional context

jest uses some strange techniques to isolate each test suite (each *.test.js file) from each other. The tests run in the same process, but jest monkeypatches in a custom `require` function and evaluates the tests in a custom context, allowing each test file to muck with global state and not influence all the others. This is how jest supports their module mocking and a generally good practice for avoiding test flakes. That said, it can cause issues if code is not expecting to be required more than once, or somehow escapes their global state resetting approach. I am not sure it can be turned off for jest, but I do know that jest is a VERY popular test runner such that it'd be great to get support. See https://www.npmtrends.com/jest-vs-tap-vs-ava

**Comment by vkarpov15** [comment]
I took a closer look at this and confirmed that https://github.com/airhorns/sdk-typescript/commit/3955acdd638b2d0e5c2e7c736f1bbd19a8d4549e does fix this issue. The root cause looks like one file's copy of the Temporal module is getting another file's copy of `errors`. I haven't been able to find a better workaround than the one @airhorns suggested.

**Comment by Irvenae** [comment]
+1 for getting this fixed. 
I am also running in this issue. Should we make a PR for this?

**Comment by bergundy** [comment]
Let's open a PR with @airhorns' fix

**Comment by bergundy** [comment]
I think @airhorns mentioned that it didn't fully work on slack, @airhorns can you confirm?

**Comment by airhorns** [comment]
I think that might have been my mistake, just disabled the other mitigation I added beyond what we discussed and my big test suite still passed! Will open a PR
