### ISSUE TITLE
[Bug] Fix message when objects are thrown

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#635]
### Describe the bug

Currently, `throw {a : 'test'}` results in a failure with message `"[object Object]"`. It should be `{a: "test"} [A non-Error value was thrown from your code. We recommend throwing Error objects so that we can provide a stack trace.]`

**Comment by bergundy** [comment]
Are you suggesting we call `util.inspect` on the value? I wouldn't want to use `JSON.stringify` for this.
Even `util.inspect` might be overkill.

**Comment by lorensr** [comment]
Currently it's supposed to use `JSON.stringify`. Happy to switch to `util.inspect`

https://github.com/temporalio/sdk-typescript/blob/main/packages/common/src/failure.ts#L346

**Comment by bergundy** [comment]
It would work with the current workflow runtime but if we ever want to make a safer sandbox which allows running untrusted code we won't be able to use that.

**Comment by lorensr** [comment]
Yes, thanks!

**Comment by bergundy** [comment]
TBH,
