### ISSUE TITLE
[Bug] Fix non-TemporalFailure type

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#637]
### Describe the bug

We say that we set a failure's `type` [to the exception full type name when it doesn't extend TemporalFailure](https://typescript.temporal.io/api/classes/common.applicationfailure). However, `throw new MyFailure()`, where `MyFailure extends Error`, results in `type: 'Error'`:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/251288/167039331-7adb7af3-b32c-4a6e-8391-2a3661b81867.png">

It should be `type: 'MyFailure'`

**Comment by bergundy** [comment]
We could take `err.__proto__.constructor.name`

**Comment by bergundy** [comment]
Here:
https://github.com/temporalio/sdk-typescript/blob/f03d2aa595a5a6bbc5e8e46d0eb9ef1f32349ce8/packages/common/src/failure.ts#L360
