### ISSUE TITLE
[Feature Request] Disable up-to-date PRs requirement

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#639]
### Is your feature request related to a problem? Please describe.

Whenever a PR is merged, all other PRs are blocked with this message:

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/251288/167043418-0b2ad017-4f18-4258-b428-643e09351179.png">

Hitting `Update branch` restarts actions, which can take a while to complete. While I can then do `Enable auto-merge`:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/251288/167043517-c24d70f6-516a-49f0-88cf-8ca657acb748.png">

it not infrequently requires "Rerun failed checks" to be manually hit, and won't work if another PR is merged in the meantime.

### Describe the solution you'd like

We uncheck this box:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/251288/167043347-786dfb6b-50cb-40f1-9922-e5d093d7c661.png">

Pro: takes much less time to merge PRs
Con: slightly less safe: delayed knowledge of failure. In the event that the PR is green but wouldn't be if updated, and we merge without updating, we'll get notified of the failing test on `main` of the merge commit.

**Comment by bergundy** [comment]
I vote for this

**Comment by bergundy** [comment]
Let me disable it now

**Comment by bergundy** [comment]
Done
