### ISSUE TITLE
[Bug] ActivityInterface adds a string index to any interface that implements it

### ISSUE THREAD

**Issue by beaucollins** [temporalio/sdk-typescript#655]
### What are you really trying to do?

We have problems surrounding the `ActivityInterface` type adding a string index to our interfaces.

### Describe the bug

The `proxyActivities<A extends ActivityInterface>(options: AcitivityOptions): A` function takes a generic parameter `A` that _must_ implement/extend `AcivityInterface`.

In order to use our interface we must say say it `extends ActivityInterface`:

```ts
interface MyActivities extends ActivityInterface {
  customActivity(): Promise<'cool stuff'>;
}
```

When used with `proxyActivities<A extends ActivityInterface>(options: ActivityOptions): A` `tsc` now allows us to call any method whether it exists or not because of `ActivityInterface`'s string index.

```ts
const activities = proxyActivities<MyActivities>({});

// Runtime error, this isn't actually a function
activities.whateverTypeScriptDoesntCare().then(/* */);
```

If we remove `extends ActivityInterface` then `tsc` only allows calling methods defined in `MyActivities` but doesn't allow it to be used with `proxyActivities<A extends ActivityInterface>(options: ActivityOptions): A`

#### Our Workaround

```ts
/**
 * A utility type that only presents the methods that conform to `ActivityFunction<any[], any>`
 */
type ActivityInterfaceFor<T> = Pick<T, keyof {[K in keyof T as T[K] extends ActivityFunction<any[], any> ? K : never]: T[K]}>;

const ourProxyActivities = proxyActivities as (<A>(options: ActivityOptions) => ActivityInterfaceFor<A>);

const {
    customActivity,
    // tsc correctly identifies this a problem because the method doesn't exist.
    nonExistentMethod
} = ourProxyActivities<MyActivities>({});
```
### Minimal Reproduction

[This playground example is pretty similar to our environment and shows the problem and our workaround][problem-workaround].

### Environment/Versions

-  @temporalio/workflow@0.21.0
- `tsc version 4.6.3`

### Additional context

[problem-workaround]: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQQMY2AN2DAngSQDsYBTKAMwENUSAaFdLHXAMQFdDGJD60Ns8AeTAZuAZ3pgoEAB64+TDCTFwAvnHLSQcAOQABUuGiUANsAgB6AO7QA1uRMQrOgNwAoD8GJkqNOAFk2VAALAHU7BycVEhlSQgATFQUBAm8KahJENzg4MB9oEHCoWwAKLzA2GAAuOAAjCAgTEkpCAEoagAUtYDESAB4dVAhwJtIdOAAfXStgylJMMh0APjdVDzchwjF4G2LIqzEawJCi+0cDuABeLJycvIoC05qSgH1yytarpbgu4Z6SAB0UGUjQWJUGwzAoxIOlaqw8FgscBgwR6cBAJBREHicDEwQgbBM8UIOngMR6MHotUqDH4zCIpHSflmKkouJgUC8AHM4F54jFkbg8m5EXADGIALQxPLoKVQaRQOAbcTwQjcACiMgpJGI-kx+Jx112ZyiAOCJBMjncIoAVDbsja4KFMtKSOg4NwTLhkeb0frsSpuAEgmEIucVDAIHVMpRMJRgCZKLUmgC4AAhGkonoO3H4i4ouZweJsTKRn2Zbacwg8vkCoMAA2S9LSvhI9bgVkyqBaOcoYlsGmgcBeLVwLz9WJxLRxMDEqB9XlsKhwOlZhDgjcYKXYnFEhD6o4A2gBdeijpb1gEOiwipHiqUyGUwOUK5VbeAIbK3FHKOhfnKUMCtD-nApgmMBtx1JQ8SrFcuTSHITZKGIfTHKGezhksJQIKorTWps2zoiGpz7Co1xSLI8hbjgwDKKhxFhlEWE4Xht4oGqP6KjElAjJkMxkKWqIqBik65gSRJwBxcDktsbH3q6spkAqSogAxGGmualoQCUrEInaOYACpCWJ+a+rUJCzNgQ6dh2LTwJowzInOg6Kj+cDAjAbBQOueB5B65AbhRiHUch9Y5tSOxdi0pJwGwvQbgActwADC3DkAU3IkeG7bmd2cWZDgRYQMoJLwJZMbslWNYJDEOYFvAm50ngDI+Bk7bAgAjmwwDAio6WKvWfTINJsQ6oktKKKkjKtheV5wDaN5uF400ZHASWEKlhD9SAmWMRcn6QXc+RQIUdhlIQFTVHUDRNC07Q-N0vQDEMvFjJM0yzPMiwrGsCJIs6cDdqVsXxfW62bdtu3qQcOVupQ+W8vA8TFWIwMxHEOKNZNLVMm2b6EdQTW0WR8GUUhxN9ODaUZdWWVMdhuH4SqNy3KKRloi8yPKOOSlDrl8PxTZyNo6NCQTSkOOtiBoryY+brPrzUAgVmYgsPGJhiMgYiak+JAweo1yE4oxPWhY+nzXA7PLoGXkdnYgEEgkc2OjmLA9QTsUYGYeCCn59UeoQXrwb+xARr6IkGmHhabNtyJRlj24cFw+5HqeoGELgF7Xh4vmZEhU2tTQLDQH0BnfNcHTAKgtil-QtgkLgEABQgh4ANK8uu9eNwFBmgSoBlt8eI0Y0kIWsEne4HhnJ5nhn3wAPxwO3NSECQCxQMeNQD63x6qEsTPvh6Xm-MFRPKHBQVUWfrIqCUQ1YRAIjmFsNT58Ie5iJ8lzfPnksZMXUB766TNvaC22cCIfhAvcbapwIK3AgJxPUk5YLXAJFAE+V9jZ0SpltGmXI6YHGYozDwQA

**Comment by bergundy** [comment]
Thanks for reporting, we will look into it

**Comment by bergundy** [comment]
There are 2 problems I see here:
1. You must extend `ActivityInterface` in order to use it as a type param in `proxyActivities`
  - This isn't too bad but I'd be happy if it can be avoided (as in your solution)
3. The returned proxy object supports using any key as an `ActivityFunction<any[], any>`
  - You won't get any completions from the TS language server for undeclared properties but compilation still passes so that's not great

Your workaround could be used as the actual type for proxy activities.
The only downside I see to that is that if you use a type that doesn't have any methods with a valid activity signature (`ActivityFunction`) you won't get any compiler errors, you simply wouldn't see them on the proxy.

FTR, I managed to simplify the `ActivityInterfaceFor` type a bit:
```ts
type ActivityInterfaceFor<T> = {[K in keyof T as T[K] extends ActivityFunction<any[], any> ? K : never]: T[K]};
```

Overall, I like your suggestion and I think we should change the signature.

**Comment by beaucollins** [comment]
> FTR, I managed to simplify the ActivityInterfaceFor type a bit:

I originally had that but the downside to your simplified version is `tsc` no longer links the source definition's method to the returned type which has a poorer developer experience.

For example, with your simplified version, using the playground link I provided:

```ts
const {
    customActivity,
} = ourProxyActivities<MyActivities>({});
```

Command click on `customActivity` and it doesn't know where to take you because the type references are now broken.

If you leave the `Pick<T, ....>` in, command click the `customActivity` and it takes you to the interface that defined it.

**Comment by beaucollins** [comment]
A better way to communicate what's going on we can split that `ActivityInterfaceFor` into two different utility functions.

```ts
// union of keys of T that extend V
type KeysWhere<T, V> = keyof {[K in keyof T as T[K] extends V ? K : never]: T[K]};

// Only pick the keys that conform
type ActivityInterfaceFor<T> = Pick<T, KeysWhere<T, ActivityFunction<any[], any>;
```

> The only downside I see to that is that if you use a type that doesn't have any methods with a valid activity signature, you simply wouldn't see them on the proxy.

I haven't actually used the API at all, would it be expected to use `proxyActivities()` without calling a method on the returned interface? Because you'll get compilation errors on any attempts to use a method that doesn't exist.

**Comment by bergundy** [comment]
Not sure I understand the question.

Here's what I think could be a reasonable interface

```ts
import { ActivityInterface, ActivityFunction, ActivityOptions } from '@temporalio/workflow';

const NotAnActivityMethod = Symbol.for('__TEMPORAL_NOT_AN_ACTIVITY_METHOD');
type UntypedActivities = ActivityInterface;
type ActivityInterfaceFor<T> = {[K in keyof T]: T[K] extends ActivityFunction<any[], any> ? T[K] : typeof NotAnActivityMethod};
// The other option would be to map to `never` but that means that there's no signal to the user if they've misconfigured an activity function.
// Downside of the Symbol approach is that it's misleading, we can't ensure at runtime that you get a Symbol.

function proxyActivities<A = UntypedActivities>(options: ActivityOptions): ActivityInterfaceFor<A> {
    return {} as any
}

interface NonConformingWorkflows {
  performWork(input: boolean): Promise<'complete' | 'whatever'>;
  invalidDefinition(input: boolean): string;
}

const act = proxyActivities<NonConformingWorkflows>({});

act.performWork(true);
act.invalidDefinition();
// ^^ TS complains with:
// (property) invalidDefinition: typeof NotAnActivityMethod
// This expression is not callable.
// Type 'Symbol' has no call signatures.(2349)

// For JS users this still works:
const act2 = proxyActivities({});
act2.notFound();
```
