### ISSUE TITLE
[Bug] instanceof doesn't work with WorkflowInfo fields

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#659]
### What are you really trying to do?

Determine types of `WorkflowInfo` fields inside Workflow.

### Describe the bug

Things like this are `false`, since the info object is created outside the vm:

```
// searchAttributes: { CustomIntField: [1,2] }
workflowInfo().searchAttributes.CustomIntField instanceof Array
workflowInfo().executionExpirationTime instanceof Date
```

**Comment by bergundy** [comment]
I’d just dump to json and back
