### ISSUE TITLE
[Bug] Cannot create a new workflow with same workflowId of a completed one

### ISSUE THREAD

**Issue by ThePinger** [temporalio/sdk-typescript#661]
### What are you really trying to do?

Well I'm trying to create a new workflow with the same `workflowId` of a Completed one. 

### Describe the bug

I keep on receiving `WorkflowNotFoundError: workflow execution already completed` despite specifying the `workflowIdReusePolicy` as `ALLOW_DUPLICATE`

Here's the code: 

```ts
export async function runWorkflow(
  id: string,
  startDate: Date
) {
  try {
    const handle = await client.start(workflowExample, {
      args: [id, startDate],
      taskQueue: 'examples',
      workflowId: `workflow-${id}`,
      workflowIdReusePolicy:
        WorkflowIdReusePolicy.WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE,
    })
    console.log(`Started workflow ${handle.workflowId}`)
  } catch (e: any) {
    console.error(e)
  }
}
```

and here's the error:

```shell
WorkflowNotFoundError: workflow execution already completed
    at WorkflowClient.rethrowGrpcError (/PATH_TO_NODE_MODULES/node_modules/@temporalio/client/src/workflow-client.ts:521:15)
    at WorkflowClient._signalWorkflowHandler (/PATH_TO_NODE_MODULES/node_modules/@temporalio/client/src/workflow-client.ts:584:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.signal (/PATH_TO_NODE_MODULES/node_modules/@temporalio/client/src/workflow-client.ts:811:9) {
  workflowId: 'workflow-cl3gea8x40340ukooxl1jyrkl',
  runId: undefined
}
```

### Minimal Reproduction

Tried using the hello-world template with the same id and it surprisingly worked so not sure what's the problem here

- TypeScript: https://github.com/temporalio/samples-typescript/tree/main/hello-world

### Environment/Versions

- OS and processor: Intel macOS Monterey 12.1
- Temporal Version: 1.16.2 
- Temporal TypeScript SDK Version: 0.22.0
- Using Docker to run Temporal

**Comment by lorensr** [comment]
I was also unable to reproduce:

https://github.com/temporalio/samples-typescript/blob/repro-allow-duplicate/hello-world/src/client.ts#L22-L23

From `at Object.signal` in the trace, it looks like the error is actually coming from calling `handle.signal()`?

**Comment by ThePinger** [comment]
Hey @lorensr thanks for the fast reply. My bad really sorry for this issue as u said it was a result from `handle.signal()` but for some reason I thought that was not the issue. Again thanks for your help.

**Comment by lorensr** [comment]
No problem, welcome! ☺️
