### ISSUE TITLE
[Feature Request] Cache Rust deps in CI

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#691]
Use https://github.com/Swatinem/rust-cache to improve build times. 

> Seems it caches dependencies (PRs can't share cache w/ each other, but can from the main build which is plenty helpful for our use case since we also run on main push). It only caches deps not local crates of course. I predict it might save 2.5 mins on dev builds and 4 mins on release builds on slower targets. GH projects/actions are given cache space to use, so this uses it. Ref https://www.reillywood.com/blog/rust-faster-ci/

**Comment by cretz** [comment]
I have added this to the Python SDK, and it is currently broken. Ref issue 52 on https://github.com/Swatinem/rust-cache.

**Comment by cretz** [comment]
I fixed this by setting `working-directory` in the options. See https://github.com/temporalio/sdk-python/pull/50.

**Comment by bergundy** [comment]
I just merged a PR (#864) that uses the action, save a few minutes.
Wish we'd done this a while ago..
