### ISSUE TITLE
[Bug] @temporalio/interceptors-opentelemetry package.json refers to non-existent file

### ISSUE THREAD

**Issue by esuh-descript** [temporalio/sdk-typescript#717]
### What are you really trying to do?

We were trying to import and use types and functions from `@opentelemetry/interceptors-opentelemetry`, specifically `OpenTelemetryActivityInboundInterceptor` and `makeWorkflowExporter`.

### Describe the bug

Errors were thrown because the `package.json` in `@temporalio/interceptors-opentelemetry` refers to `lib/index.js` and `lib/index.d.ts`, neither of which exist in the published package (nor do they seem to exist in the source code):

```
source/InstrumentedWorkerClient.ts(5,8): error TS2307: Cannot find module '@temporalio/interceptors-opentelemetry' or its corresponding type declarations.
```

### Minimal Reproduction

`package.json`:
```json
{
  "name": "testpkg",
  "version": "1.0.0",
  "description": "Testing",
  "main": "index.js",
  "types": "index.d.ts",
  "scripts": {
    "build": "tsc"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@temporalio/interceptors-opentelemetry": "^1.0.0-rc.0",
    "typescript": "^4.7.4"
  }
}
```

`index.ts`:
```typescript
import {
    OpenTelemetryActivityInboundInterceptor,
    makeWorkflowExporter,
} from '@temporalio/interceptors-opentelemetry';
```

Run: `npm run build`

**Comment by bergundy** [comment]
Thanks for reporting this.
I'll fix `package.json`.

There's nothing to import at the root of this package, you should import from `lib/client`, `lib/worker` and `lib/workflow` for each part of your application.

For example:
```ts
import {
  OpenTelemetryActivityInboundInterceptor,
  makeWorkflowExporter,
} from '@temporalio/interceptors-opentelemetry/lib/worker';
```

See our sample on how to use this package: https://github.com/temporalio/samples-typescript/tree/main/interceptors-opentelemetry
