### ISSUE TITLE
[Bug] Update SDK README to match 1.0.0 capabilities

### ISSUE THREAD

**Issue by yoDon** [temporalio/sdk-typescript#724]
### Describe the bug

The SDK README is out of date with the current capabilities of the SDK

### Minimal Reproduction

SDK indicates, for example, that Upsert on search attributes is not implemented.

### Environment/Versions

N/A

### Additional context

Congrats on getting the TypeScript SDK ready for release!

**Comment by bergundy** [comment]
I’ve been meaning to update the readme for a while and haven’t gotten around to it.
Thanks for reporting.
