### ISSUE TITLE
[Bug] Nondeterminism error: Local activity machine can't handle TimerStarted

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#731]
Repro: https://github.com/temporalio/samples-typescript/compare/repro-local

Note that `refreshAccessToken` adds to `tasks` array, which makes the condition true.

```
git clone https://github.com/temporalio/samples-typescript.git
cd samples-typescript/hello-world
git checkout repro-local
npm start
```

`npm run workflow`

After 5 seconds, worker logs:

```
ERROR temporal_sdk_core::worker::workflow::managed_run: Error in run machines, error: RunUpdateErr { source: Nondeterminism("Local activity machine cannot handle this event: HistoryEvent(id: 5, Some(TimerStarted))"), complete_resp_chan: None }
```

event history: https://www.dropbox.com/s/n37xushdt9jstq3/08edc8df-2e2e-4b6a-9cf8-af20e777ae2c_events.json?dl=0

**Comment by lorensr** [comment]
Repro code, for posterity: 

```ts

import { condition, defineSignal, setHandler, proxyLocalActivities } from '@temporalio/workflow';

const { refreshAccessTokenLocalActivity } = proxyLocalActivities<typeof activities>({
  startToCloseTimeout: '1 minute',
});

export async function weirdWorkflowLoop() {
  const tasks: any = [];
  let token: any = {};
  let refreshAccessTokenPromise: any;

  function refreshAccessToken() {
    if (refreshAccessTokenPromise === undefined) {
      refreshAccessTokenPromise = (async () => {
        token = await refreshAccessTokenLocalActivity(); //NOTE: In the real Workflow this function is called with proxyLocalActivity

        tasks.push(() => {
          //this is just so the condition at the end of the main forloop unlocks
        });
      })();
    }
  }

  for (;;) {
    while (tasks.length) {
      const task = tasks.pop();
      await handleTask(task);
    }
    refreshAccessToken(); // intentionally not awaited
    // if (!token) refreshAccessToken();
    await condition(() => tasks.length > 0, '30s');
  }
}

async function handleTask(task: string) {
  console.log('performing task:', task);
  return new Promise((r) => setTimeout(r, 100));
}
```

```ts
export async function refreshAccessTokenLocalActivity(): Promise<any> {
  console.log('refreshAccessTokenLocalActivity');
  //This activity makes an http request so it can fetch an access token using the refreshToken
  return new Promise((resolve) => setTimeout(() => resolve({ token: 'token-foo', status: 'configured' }), 5000));
}
```

**Comment by JoshVee** [comment]
This is still happening in 1.2.0:
```
2022-09-19T11:26:32.518958Z ERROR temporal_sdk_core::worker::workflow::managed_run: Error in run machines, error: RunUpdateErr { source: Nondeterminism("Continue as new workflow machine does not handle this event: HistoryEvent(id: 30, Some(TimerStarted))"), complete_resp_chan: Some(Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: true, is_tx_task_set: false } }) }) }
```

**Comment by Sushisource** [comment]
> This is still happening in 1.2.0:
> 
> ```
> 2022-09-19T11:26:32.518958Z ERROR temporal_sdk_core::worker::workflow::managed_run: Error in run machines, error: RunUpdateErr { source: Nondeterminism("Continue as new workflow machine does not handle this event: HistoryEvent(id: 30, Some(TimerStarted))"), complete_resp_chan: Some(Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: true, is_tx_task_set: false } }) }) }
> ```

@JoshVee This would be a different problem, and is very likely a result of nondeterminism in your workflow code (possibly due to deploying new, incompatible code), where it's choosing to continue as new but the existing history was starting some timer at that point. If you believe your code is deterministic & you did not deploy new incompatible code, feel free to open a different issue - ideally with some example workflow code & history. Thanks!

**Comment by JoshVee** [comment]
Thanks for the response @Sushisource. Seems like the issue was caused by workflows that had been originally started on the older SDK worker, but then `ContinuedAsNew` onto the v1.2.0 worker.
