### ISSUE TITLE
[Feature Request] Allow ability to track workflow/activity input with open telemetry spans

### ISSUE THREAD

**Issue by meg2208** [temporalio/sdk-typescript#732]
### Is your feature request related to a problem? Please describe.

Was trying out the interceptors-opentelemetry sample and got it successfully pushing to datadog, which is great. The issue is that it doesn't send the activity input/outputs and I would like that to be send up to datadog for easier searching and analysis.

### Describe the solution you'd like

Looking at the opentelemetry sdk, `tracer.startActiveSpan` has an [another available signature](https://github.com/open-telemetry/opentelemetry-js-api/blob/6dd34e234eaa984f00a4c9339b16fddad7d7ea46/src/trace/tracer.ts#L91) where you can pass in a `SpanOptions` object and this has a field called `attributes` which lets you attach an arbitrary mapping of metadata to the span.

I think the best thing to do is to update `InstrumentOptions` to have an additional optional field called `attributes` whose type can be `SpanAttributes` (matching the type in `SpanOptions.attributes`) and then pass that to `SpanOptions` as `{ attributes }`. When calling `instrument` you can build the attributes object from the input args plus other important identifying fields.

I'm thinking this can be a global configuration (something like boolean `includeAttributes`) that come as an input to the interceptors.

Looking forward to hearing your thoughts!

**Comment by bergundy** [comment]
Instead you can add another interceptor to the chain after the otel interceptor and add the attributes you want to the current span:
```ts
const span = otel.trace.getSpan(otel.context.active())
span?.setAttributes(attributes)
```

**Comment by bergundy** [comment]
I'm closing this issue, you can reopen if you think that there's a better solution

**Comment by meg2208** [comment]
Thanks for the reply. I was able to get that to work. Thanks!

**Comment by meg2208** [comment]
@bergundy Do you know which interceptor I can use to pull the activity and workflow outputs?

**Comment by lorensr** [comment]
The output is the return value of `next()`. 

https://typescript.temporal.io/api/interfaces/workflow.workflowinboundcallsinterceptor/

So maybe something like this:

```ts
export class MyInterceptor implements WorkflowInboundCallsInterceptor {
  public async execute(
    input: WorkflowExecuteInput,
    next: Next<WorkflowInboundCallsInterceptor, 'execute'>
  ): Promise<unknown> {
    const span = otel.trace.getSpan(otel.context.active())
    span?.setAttributes({ args: input.args })
    
    const result = await next(input)
    span?.setAttributes({ result })
    
    return result
  }
}
```

If you can post what you get working, that would help others! And I can make it into a sample.

**Comment by meg2208** [comment]
Sounds good. I can post it. Do you prefer it as a branch, fork, or just post the full diff here? I made changes to 4 or so files.

**Comment by lorensr** [comment]
@meg2208 sorry for the delay—if you're still up for it, a PR to the [otel sample](https://github.com/temporalio/samples-typescript/tree/main/interceptors-opentelemetry) would be most helpful ☺️ Otherwise post just the relevant code, or the commit link if it's a public repo.
