### ISSUE TITLE
[Feature Request] Add `ApplicationFailure.create`

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#752]
### Is your feature request related to a problem? Please describe.

#562 

### Describe the solution you'd like

Add `create` static method to [ApplicationFailure](https://typescript.temporal.io/api/classes/common.applicationfailure/):

```ts
throw ApplicationFailure.create({
  message: 'my message',
  type: 'old-cookie', 
  nonRetryable: true, 
  cause: e
})
```

**Comment by bergundy** [comment]
I'd be fine with this
