### ISSUE TITLE
[Bug] with yarn pnp, there are issues running workflow tests

### ISSUE THREAD

**Issue by albertyfwu** [temporalio/sdk-typescript#755]
### What are you really trying to do?

I'm trying to write workflow tests as described at https://docs.temporal.io/typescript/testing/#testing-workflows

### Describe the bug

I actually ran into a similar issue while writing temporal tests:

The script in my package.json looks like this:
```
"scripts": {
    "test": "NODE_ENV=test jest"
  },
```
I am running `yarn workspace <workspace> test`.
At first, I get this error: `You need to run with a version of node that supports ES Modules in the VM API. See https://jestjs.io/docs/ecmascript-modules`

Then, if I run `NODE_OPTIONS=--experimental-vm-modules yarn workspace <workspace> test` I get this error:
```
Cannot find module 'pnpapi' from '/Users/albertwu/workspace/project/.yarn/cache/enhanced-resolve-npm-5.10.0-7941304306-0bb9830704.zip/node_modules/enhanced-resolve/lib'

    Require stack:
      /Users/albertwu/workspace/project/.yarn/cache/enhanced-resolve-npm-5.10.0-7941304306-0bb9830704.zip/node_modules/enhanced-resolve/lib/index.js
      /Users/albertwu/workspace/project/.yarn/__virtual__/webpack-virtual-4d546bab61/0/cache/webpack-npm-5.73.0-fc8c985a74-aa434a241b.zip/node_modules/webpack/lib/CacheFacade.js
      /Users/albertwu/workspace/project/.yarn/__virtual__/webpack-virtual-4d546bab61/0/cache/webpack-npm-5.73.0-fc8c985a74-aa434a241b.zip/node_modules/webpack/lib/Compiler.js
      /Users/albertwu/workspace/project/.yarn/__virtual__/webpack-virtual-4d546bab61/0/cache/webpack-npm-5.73.0-fc8c985a74-aa434a241b.zip/node_modules/webpack/lib/webpack.js
      /Users/albertwu/workspace/project/.yarn/__virtual__/webpack-virtual-4d546bab61/0/cache/webpack-npm-5.73.0-fc8c985a74-aa434a241b.zip/node_modules/webpack/lib/index.js
      /Users/albertwu/workspace/project/.yarn/cache/@temporalio-worker-npm-1.0.0-rc.1-2998f0d7a7-147819cf17.zip/node_modules/@temporalio/worker/lib/workflow/bundler.js
      /Users/albertwu/workspace/project/.yarn/cache/@temporalio-worker-npm-1.0.0-rc.1-2998f0d7a7-147819cf17.zip/node_modules/@temporalio/worker/lib/worker.js
      /Users/albertwu/workspace/project/.yarn/cache/@temporalio-worker-npm-1.0.0-rc.1-2998f0d7a7-147819cf17.zip/node_modules/@temporalio/worker/lib/index.js
      /Users/albertwu/workspace/project/.yarn/unplugged/@temporalio-testing-npm-1.0.0-rc.1-8641517f72/node_modules/@temporalio/testing/lib/index.js
```

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by bergundy** [comment]
Thanks for reporting.
I don't know much about yarn pnp, we'd have to look into this.

**Comment by albertyfwu** [comment]
maybe related to this? https://github.com/webpack/enhanced-resolve/pull/349

**Comment by bergundy** [comment]
Might be, jest is a pretty complicated JS runtime.

Can you verify that this doesn't happen when using a simpler test runner?

**Comment by lorensr** [comment]
> maybe related to this? https://github.com/webpack/enhanced-resolve/pull/349

Seems like it, in which case it'd be fixed when this is merged: https://github.com/webpack/enhanced-resolve/pull/301

In the meantime, some workarounds are using mocha or not using pnp. Here's a mocha sample: https://github.com/temporalio/samples-typescript/blob/bd2e6d73dcc5de5ff41215a74745ab363ee7e52a/activities-examples/package.json#L11

**Comment by albertyfwu** [comment]
Thanks.

Can't I also just write unit tests directly by mocking activities? Is the main benefit of the test runner the ability to do time skipping?

**Comment by bergundy** [comment]
I think you mean the test framework `@temporalio/testing` the main benefit of it is auto time skipping, yes.
We've also wrapped up starting the server and all of the utilities in the test environment which provides pure convenience.
The issue you're experiencing isn't related to that though.

**Comment by albertyfwu** [comment]
If I didn't use `@temporalio/testing` and just directly executed the workflow function (without going through worker), wouldn't that bypass the webpack issues?

**Comment by bergundy** [comment]
This isn't currently possible, workflows can only be run in the isolated runtime at the moment since they rely on global state.
I have some plans to loosen the runtime requirement eventually for unit testing purposes but so far it hasn't been high priority for us and you're the first one to request this "feature".

**Comment by esuh-descript** [comment]
We are running into this issue without `yarn pnp` also (using just `yarn` and `jest`). The only fixes we've found are to apply the patches:

```diff
diff --git a/node_modules/@temporalio/testing/lib/index.js b/node_modules/@temporalio/testing/lib/index.js
index 863bf4f..24b4831 100644
--- a/node_modules/@temporalio/testing/lib/index.js
+++ b/node_modules/@temporalio/testing/lib/index.js
@@ -96,7 +96,7 @@ function addDefaults({ testServer, logger, }) {
 }
 // TS transforms `import` statements into `require`s, this is a workaround until
 // tsconfig module nodenext is stable.
-const _importDynamic = new Function('modulePath', 'return import(modulePath)');
+const _importDynamic = require;
 /**
  * An execution environment for running Workflow integration tests.
  *

diff --git a/node_modules/get-port/index.js b/node_modules/get-port/index.js
index 06e993a..07bab92 100644
--- a/node_modules/get-port/index.js
+++ b/node_modules/get-port/index.js
@@ -1,5 +1,5 @@
-import net from 'node:net';
-import os from 'node:os';
+const net = require('net');
+const os = require('os');
 
 class Locked extends Error {
 	constructor(port) {
@@ -79,7 +79,7 @@ const portCheckSequence = function * (ports) {
 	yield 0; // Fall back to 0 if anything else failed
 };
 
-export default async function getPorts(options) {
+module.exports.default = async function getPorts(options) {
 	let ports;
 	let exclude = new Set();
 
@@ -151,7 +151,7 @@ export default async function getPorts(options) {
 	throw new Error('No available ports found');
 }
 
-export function portNumbers(from, to) {
+module.exports.portNumbers = function portNumbers(from, to) {
 	if (!Number.isInteger(from) || !Number.isInteger(to)) {
 		throw new TypeError('`from` and `to` must be integer numbers');
 	}
```

For now, we are unblocked by using `patch-package` to fix the issue, but it would be great to not have to patch the code ourselves. Perhaps given the small amount of code in `get-port`, it might be worthwhile to vendor and patch the upstream code in the `@temporalio/testing` package itself?

**Comment by lorensr** [comment]
@esuh-descript Did you try `NODE_OPTIONS=--experimental-vm-modules yarn test`? 

Other notes on using Jest are:

- Needs to be `>= 27.0.0`
- Use [`testEnvironment: 'node'`](https://jestjs.io/docs/configuration#testenvironment-string). `testEnvironment: 'jsdom'` is not supported.

**Comment by bergundy** [comment]
Closing, we don't depend on `get-port` anymore.
