### ISSUE TITLE
[Bug] Support patched API inside condition.

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-typescript#756]
### What are you really trying to do?

A workflow is blocked on a condition.
```
await wf.condition(() => <some expression>)
```
A workflow has to be updated to block on a different condition expression. The naive way of

```
await wf.condition(() => patched("patchId") ? <new expression> : <old expression>) 
```
is not going to work. The problem is that condition is potentially called many times. And if the first time it is called the patch returns false then it will keep returning false even for the code that wasn't executed yet. A possible workaround is to use different patchId on every condition evaluation:

```
var i = 0;
await wf.condition(() => patched("patchId"+(i++)) ? <new expression> : <old expression>) 
```
### Proposal 

Do not require setting different patchId on every condition evaluation. The SDK should internally generate a different patch id on every call or do something else to avoid the wrong behavior.

**Comment by mfateev** [comment]
>  Why is returning false all the time after the first time a bad thing?

This is the same problem as using patched in a loop:
```
for (...) {
   if (patched("foo")) {
       activity2(...);
   } else {
      activity1(...);
  }
}
```
If the new code is deployed after a few iterations of the loop, the `activity2` will never be invoked even if loop makes a lot of new iterations. Users expect that each new iteration is going to use the new branch.

The issue is to allow using patched inside the condition to support the ability to update a condition expression _after_ the workflow is already blocked on the condition.

**Comment by bergundy** [comment]
> Users expect that each new iteration is going to use the new branch.

This is what happens though, I’m not following

**Comment by bergundy** [comment]
> The issue is to allow using patched inside the condition to support the ability to update a condition expression after the workflow is already blocked on the condition.

patched already works this way today.
It evaluates to false during replay and once the marker is seen or workflow is no longer replaying it starts returning true.

**Comment by bergundy** [comment]
@mfateev can we close this?

**Comment by mjameswh** [comment]
That's already how TS SDK's `patch()` works.
