### ISSUE TITLE
[Bug] workflowBundle with code/sourceMap breaks with obscure error, while using codePath/sourceMapPath works

### ISSUE THREAD

**Issue by davidtheclark** [temporalio/sdk-typescript#758]
### What are you really trying to do?

Upgrade to 1.0.0-rc.1 and run a worker.

### Describe the bug

If I build a bundle and then start the worker with a `workflowBundle` object with `code` and `sourceMap` properties, the worker crashes with this error (which unhelpfully has no stack trace):

```
ERROR : Invalid regular expression flags {}
```

If I just change my `workflowBundle` bundle to use the `codePath` and `sourceMapPath` properties, the worker does not crash.

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: 1.0.0-rc.1
- Are you using Docker or Kubernetes or building Temporal from source? The server is on Ducker.

**Comment by bergundy** [comment]
Sounds like you’re passing a path instead of the actual code, can you verify?

**Comment by davidtheclark** [comment]
Ah yes, thank you. I misunderstood some of the documentation.
