### ISSUE TITLE
[Bug] worker client OOM when running as a container in a k8s cluster.

### ISSUE THREAD

**Issue by Vincechen611** [temporalio/sdk-typescript#762]
### What are you really trying to do?
Consider calculate default maxCachedWorkflows by v8.getHeapStatistics().total_available_size instead of os.totalmem()

### Describe the bug

Recently, We have implement our temporal worker client with sdk-typescript and run as a container in a k8s cluster.
We have set `NODE_OPTIONS=--max-old-space-size=XXX` when starting up worker, but we found the worker pod always get OOM killed by k8s when processing task.
After checking the detail, we found that the default `maxCachedWorkflows` is calculated by `os.totalmem()` if we didn't set.
When running in container, the `os.totalmem()` will get the host machine memory not container resource setting (which is in [cgroup](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/))
Could we calculate default [maxCachedWorkflows](https://github.com/temporalio/sdk-typescript/blob/a261054130708744c692a50b07d3f189a43b9934/packages/worker/src/worker-options.ts#L414) with v8.getHeapStatistics().total_available_size which might reduce the chance of OOM if user didn't assign maxCachedWorkflows.

### Environment/Versions

- OS and processor: [Linux], [container](https://github.com/nodejs/docker-node) based on `node:16.14.0`
- Temporal Version: 1.17.1 , SDK version : v1.0.0-rc.1
- Are you using Docker or Kubernetes? Yes

### Additional context
Our worker k8s manifest.
![image](https://user-images.githubusercontent.com/6711819/179886299-eb43b2c7-da47-4ca6-9d3b-272183531000.png)

![image](https://user-images.githubusercontent.com/6711819/179885599-62a9d068-87bc-4cda-8d57-2343f888ee69.png)

**Comment by bergundy** [comment]
Thanks for reporting, we'll use `total_available_size` as the default instead.
