### ISSUE TITLE
[Bug] Timeout on last runReplayHistory

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#770]
Report from user:

### What are you really trying to do?

I’m creating a workflowBundle of all the workflows i’m replaying, passing the workflowBundle in to runReplayHistory, and adding the promise from runReplayHistory to an array of promises on which I use Promise.all() at the end.

### Describe the bug

I’m seeing mostly successful replays, with all executing correctly except for the last one, where I get the error:

```
Unhandled rejection { runId: undefined } Error: Replay failed. Details: Workflow activation completion failed: Failure { failure: Some(Failure { message: "Timed out waiting for task result", source: "TypeScriptSDK", stack_trace: "Error: Timed out waiting for task result\n    at Object.waitForTaskComplete (webpack-internal:///./src/work_session_manager/atlas_work_task_complete_signal.ts:36:27)", cause: None, failure_info: None }) }
```

If I skip replaying the last workflow, everything succeeds and the function actually finishes/returns.

**Comment by rupalivohra** [comment]
Hey @lorensr - any thoughts on when y'all will get to this? 
We want to put workflow replays in our CI pipeline, but without bundling and without a bulk endpoint, it's very slow to start up a new worker for each workflow replay.

**Comment by lorensr** [comment]
Not sure, but adding the `next` label!

**Comment by alex766** [comment]
Hi! Roey mentioned that you've seen this issue but haven't been able to reliably reproduce it, and I wanted to add that I have seen the error every time with bundling, but it often occurs in different places - I'm bundling about 10 workflows together and sometimes it fails on the 5th or last workflow's replay while sometimes it fails on the 2nd. I'm not sure if this is what you noticed, but thought I would add this information.

**Comment by bergundy** [comment]
Thanks everyone for jumping in on this conversation.

@alex766 this doesn't look like the same issue we're seeing in the SDK CI.

I _think_ this issue is not related to the SDK, it might just be some failure in a sink or some other source.

@rupalivohra can you please provide a reproduction?
The exception is thrown from your code, so we don't have a way to examine this further.

**Comment by alex766** [comment]
Hi, thanks for the quick response! The error I'm getting from the SDK is first 
`WARN temporal_sdk_core::worker: Failing workflow activation, run_id: "e676ec84-1b0b-4ff3-9ddd-8ca235d5f403", failure: Failure { failure: Some(Failure { message: "WorkflowUpdateError { source: Fatal(\"Child workflow machine does not handle this event\"), run_id: \"e676ec84-1b0b-4ff3-9ddd-8ca235d5f403\" }", source: "", stack_trace: "", cause: None, failure_info: Some(ApplicationFailureInfo(ApplicationFailureInfo { r#type: "", non_retryable: false, details: None })) }) }` 
and the following error that I mentioned earlier is (I think) the result from the sink. Does that match what you were seeing?

As for the code, the relevant snippets are below. I first create the bundle then use `listWorkflowExecutions` to get the 3 oldest running workflows for each workflow type, grab their history, and kick off the replay using the workflowBundle. I then await for the results of the replay. 
`const workflowBundle = await bundleWorkflowCode({
    workflowsPath: require.resolve('../scheduling/workflows/all_workflows'),
  });`
`const resultIDs = await conn.service.listWorkflowExecutions({
    namespace: replayNamespace,
    // fetching the 3 oldest, non-terminated workflow executions for the given
    // workflow type
    // will experiment with the number of workflows to query
    pageSize: 3,
    //  and ExecutionStatus = 'Running'
    query: `WorkflowType = '${workflowName}'
       ORDER BY StartTime ASC`,
  });

  const queriedIDs = resultIDs.executions.map(({ execution }) => execution!.workflowId!);

  for (const ID of queriedIDs) {
    const { history } = await conn.service.getWorkflowExecutionHistory({
      namespace: replayNamespace,
      execution: {
        workflowId: ID,
      },
    });

    if (!history) {
      throw new ReplayExecutionHistoryError(ID);
    }

    workflowReplays.push(
      Worker.runReplayHistory(
        {
          // workflowsPath: require.resolve(workerPath),
          workflowBundle,
          replayName: `replayed-${ID}`,
          interceptors,
          sinks,
        },
        history,
      ),
    );
}

try {
  await Promise.all(workflowReplays);
} catch (error) {
  isDeterministic = false;
}`

**Comment by alex766** [comment]
@bergundy Hm, I recognize that the error is similar to a non-determinism error thrown, but I know for a fact that it is not coming from non-determinism because (1) I didn't change any of the workflow code when running the replay, and (2) when I run the replay serially without any bundling, no workflow non-determinism errors are raised and the replays all run to completion. 

Do you have any other ideas for what it could be?

**Comment by bergundy** [comment]
@alex766 it'd be hard for me to guess without seeing sample workflow code and corresponding history.

**Comment by bergundy** [comment]
I'm not sure how to reproduce this myself, I would need assistance from your to recreate the scenario.

**Comment by bergundy** [comment]
@alex766 @rupalivohra can we resolve this issue based on our slack conversation?

We figured out that the cause was that the bundle wasn't created with the same interceptors that were passed in to the worker.

**Comment by alex766** [comment]
Yep, thank you for all the help!
