### ISSUE TITLE
[Feature Request] Include string enums in failure objects

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#777]
### Is your feature request related to a problem? Please describe.

User is developing and logging an error, and see numerical values for enums. For example `retryState`:

![image](https://user-images.githubusercontent.com/251288/180895218-a0f6cdf2-b01a-467c-b919-dec68fae4fa0.png)

- user A: i want to understand what’s happening, so i’m going to read my error object and figure out what each thing means
- user B: `retryState: 4`? oh, my activity is in a retry state. does that mean it’s retrying? but the workflow is Failed. i don’t understand. what does 4 mean?
- user C, with string version: “wait why is my workflow failing on activity timeout? i thought it’s supposed to retry activities forever” “oh `MAXIMUM_ATTEMPTS_REACHED`? looks like someone must have set `maximumAttempts`”

### Describe the solution you'd like

I like `retryState: 'MAXIMUM_ATTEMPTS_REACHED'`, but that's back-incompat. So maybe adding: `retryStateString: 'MAXIMUM_ATTEMPTS_REACHED'`.

### Additional context

Internal slack discussion

**Comment by cretz** [comment]
I personally am not a big fan of adding fields just for people using generic object dumping. For example, how can I see the `scheduledEventId`? Are you going to make a `scheduledEventIdNumber` field?

Is there another way to customize output without altering fields for everyone even those that never dump this object? Is there an accepted way to ask users to use a separate call to get a dump-friendly form of the object?

(obviously don't let my opinion here hold this up)

**Comment by bergundy** [comment]
I don’t think we’re going to do this. Users can easily look up the enum names and implement this function. Let’s close for now and revisit if there’s demand.
