### ISSUE TITLE
[Bug] Span ended twice in TypeScript SDK

### ISSUE THREAD

**Issue by thegedge** [temporalio/sdk-typescript#781]
We're seeing a lot of these messages in our logs:

```
Can not execute the operation on ended Span {traceId: …, spanId: …}
You can only call end() on a span once.
```

Ignoring the double error message for a single error source (that's an issue in the otel SDK), this is the source of the error message:

https://github.com/temporalio/sdk-typescript/blob/ea100209b1f62561d69ab230258dbc4f07565c34/packages/worker/src/tracing.ts#L54

It's clear it can be double ended in the worker:

https://github.com/temporalio/sdk-typescript/blob/ea100209b1f62561d69ab230258dbc4f07565c34/packages/worker/src/worker.ts#L1129

Easy fix, should just require dropping the `.end()` on ☝️ since `instrument` takes care of it 🙌 

### Environment/Versions

- OS and processor: macOS (intel)
- Temporal Version: TypeScript SDK 1.0.0 (and 0.22.0).

**Comment by bergundy** [comment]
Thanks for reporting, would you mind submitting a pr with the fix?

**Comment by thegedge** [comment]
Yep, not a problem. I'll try to get to it later today or tomorrow. Was busy and wanted to make sure it got logged :)
