### ISSUE TITLE
[Feature Request] Upgrade to protobufjs@7

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#785]
### Is your feature request related to a problem? Please describe.

Latest `proto3-json-serializer` depends on `protobufjs@7`, and we curently depend on 6, which means users get both versions.

### Additional context

v7 release notes include moving CLIs to a new package named `protobufjs-cli`

https://github.com/protobufjs/protobuf.js/releases/tag/protobufjs-v7.0.0

**Comment by bergundy** [comment]
Oh nice, I'd recently heard that they released 7.0.0, maybe they'll switch from long to bigint too soon because that's been a pain to use so far.

**Comment by citrix-eg** [comment]
Especially since 1.0.0 of the ts SDK uses a vulnerable version of protobufjs: https://github.com/temporalio/sdk-typescript/blob/main/packages/client/package.json#L22
https://snyk.io/vuln/npm:protobufjs@6.11.2

This is flagging the Temporal client SDK.
