### ISSUE TITLE
Better Documentation for bundleWorkflowCode in Typescript SDK

### ISSUE THREAD

**Issue by alex766** [temporalio/sdk-typescript#792]
**Describe the solution you'd like**
Better documentation around `bundleWorkflowCode` here: https://typescript.temporal.io/api/namespaces/worker/#bundleworkflowcode or somewhere else in the Temporal to indicate that interceptors should be passed in through bundleWorkflowCode and is necessary if used with replaying, or non-determinism errors will be thrown.

**Comment by gajus** [comment]
The documentation is lacking.

How do I pass `code` to `Worker.create`?

```ts
const { code } = await bundleWorkflowCode({
  webpackConfigHook: createWebpackConfigHook(),
  workflowsPath: require.resolve('../temporal-workflows/workflows/index.js'),
});
```
