### ISSUE TITLE
Add WorkflowInfo.unsafe.now()

### ISSUE THREAD

**Issue by albertyfwu** [temporalio/sdk-typescript#796]
### What are you really trying to do?

I'm trying to write a query that will return the time left on a timer.

### Describe the bug

If a query depends on `Date.now()`, it will calculate `Date.now()` once and not update it it again on successive queries.

For example:
```
setHandler(timeLeftMsQuery, () => timer.getDeadline() - Date.now());
```

If I query this, I keep getting the same number back even though I would expect to keep getting smaller numbers.

### Minimal Reproduction

```
async function wf() {
  setHandler(timeLeftMsQuery, () => Date.now());
  await sleep('5 hours');
}

const timeLeftMsQuery = defineQuery<number>('timeLeftMs');
```

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by albertyfwu** [comment]
I believe I discussed this with @bergundy a while back on Slack, but I could not relocate the issue on github.

**Comment by bergundy** [comment]
https://github.com/temporalio/sdk-features/issues/31#issuecomment-1138616879

This is trivial to add.
I’ll make sure we include in the next release
