### ISSUE TITLE
[Bug] Nightly tests are broken

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#804]
According to the logs no workflow tasks are returned to the worker, the log is full of these messages:

```
[DEBUG] [temporal_sdk_core::worker::workflow::wft_poller] Poll wft timeout
```

AFAICT Nothing of note changed in the repo in the last couple of days, wondering if it's docker-compose environment related.

**Comment by lorensr** [comment]
They've been green since this post

https://github.com/temporalio/sdk-typescript/actions/workflows/nightly.yml

**Comment by bergundy** [comment]
Hmmm.. bot sure what changed
