### ISSUE TITLE
[Bug] Stress test exits

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#806]
`Error: Process completed with exit code 124.`

[stress-tests / stress-test](https://github.com/temporalio/sdk-typescript/runs/7696694375?check_suite_focus=true#logs)

**Comment by bergundy** [comment]
Did you inspect the logs @lorensr?

**Comment by bergundy** [comment]
124 looks due to timeout.
I think this is related to #804 where for some reason the worker isn't picking up new tasks.
I'm pretty sure this has to do with the docker compose setup and not with the SDK but haven't had time to look into it.

**Comment by lorensr** [comment]
No. Looks like we lose artifacts when we rerun

**Comment by bergundy** [comment]
Looks like this was fixed somehow
