### ISSUE TITLE
[Bug] nodeModulesPath is still used in the docs, it seems to have been removed

### ISSUE THREAD

**Issue by ErlanBelekov** [temporalio/sdk-typescript#822]
### What are you really trying to do?

It would be great if the SDK docs highlighted most up to date info.
Currently, the SDK throws an error

`Object literal may only specify known properties, and 'nodeModulesPaths' does not exist in type 'WorkerOptions'`

```
  const worker = await Worker.create({
    workflowsPath: require.resolve('./workflows'),
    connection,
    namespace: process.env.TEMPORAL_NAMESPACE ?? 'default',

    // use Dependency Injection
    activities: createActivities({
      prisma,
    }), // directly imported in Node.js
    taskQueue,
    nodeModulesPaths: [`${__dirname}/../node_modules/`],
  })
```

### Describe the bug

Here it is used and shown
https://docs.temporal.io/typescript/troubleshooting/
https://docs.temporal.io/typescript/workers/#how-to-develop-a-worker

- OS and processor: Mac intel
- Are you using Docker or Kubernetes or building Temporal from source? Docker, also K8s in prod

**Comment by lorensr** [comment]
Thanks for reporting! We removed it, as we should now always detect it correctly. If you remove the option, does it work?

**Comment by lorensr** [comment]
Updated the docs in: https://github.com/temporalio/documentation/pull/1425

**Comment by ErlanBelekov** [comment]
great, thanks!
