### ISSUE TITLE
[Bug] CI flake: ERR_SCRIPT_EXECUTION_TIMEOUT

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#824]
```
@temporalio/test:   ✔ workflows › signalHandlersCanBeCleared (880ms)
@temporalio/test:   ─
@temporalio/test:   workflows › partialShield
@temporalio/test:   Rejected promise returned by test. Reason:
lerna ERR! npm run test exited 1 in '@temporalio/test'
@temporalio/test:   Error {
@temporalio/test:     code: 'ERR_SCRIPT_EXECUTION_TIMEOUT',
@temporalio/test:     message: 'Script execution timed out after 100ms',
@temporalio/test:   }
@temporalio/test:   ─
@temporalio/test:   1 test failed
Error: Process completed with exit code 1.
```

**Comment by bergundy** [comment]
There’s only so much we can do, the script has 5 seconds to run which is already too much imo. Only way to fix this is reduce test concurrency or get stronger machines.

**Comment by mjameswh** [comment]
This was partially resolved by increasing `isolateExecutionTimeout` in our test suite to 400ms (it was 100ms when this issue was opened). We still observe some rare flake of this issue (got one in the last two months), there's very likely nothing we can really do to avoid this completely. Closing.
