### ISSUE TITLE
[Bug] test-npm-init rate limited in CI 

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#834]
This PR did not fix the rate limit failure:

https://github.com/temporalio/sdk-typescript/pull/721

I can't tell why. If we put a Cloudflare domain in front of `api.github.com`, we can switch both create and test packages to that domain (related: #782).

**Comment by bergundy** [comment]
Why does this access the GH API?

**Comment by lorensr** [comment]
fetches things from https://api.github.com/repos/

https://github.com/temporalio/sdk-typescript/search?q=api.github.com

**Comment by bergundy** [comment]
Got it, so it’s just for downloading a folder from  the repo, yeah we can fix this with a cdn too

**Comment by bergundy** [comment]
If this happens rarely let’s punt on it for now and save the complication

**Comment by lorensr** [comment]
Not rare IME

**Comment by bergundy** [comment]
Looks like we weren't sending the auth header in one of the requests, I'm fixing this.

**Comment by bergundy** [comment]
https://github.com/temporalio/sdk-typescript/pull/865/commits/3aea4dee7ae298ea2b4c57aed3946bf3d35fbae4

I'm marking that PR as closing this issue, we can reopen if we see it again.
