### ISSUE TITLE
[Bug] @temporalio/nyc-test-coverage npm module doesn't contain lib

### ISSUE THREAD

**Issue by vkarpov15** [temporalio/sdk-typescript#839]
### What are you really trying to do?

Run `npm install @temporalio/nyc-test-coverage@1.1.0 && ls node_modules/@temporalio/nyc-test-coverage`. You'll see that there's only an `src` directory, no `lib`. Here's a screenshot:

![image](https://user-images.githubusercontent.com/1620265/186012176-9151317b-a090-46d1-b59f-ad6f5d6f20dc.png)

### Describe the bug

See above

### Minimal Reproduction

See above

### Environment/Versions

- OS and processor: Linux
- Temporal Version: TypeScript SDK 1.1.0
- Are you using Docker or Kubernetes or building Temporal from source? No

**Comment by bergundy** [comment]
@vkarpov15 you probably know this but all it takes is to add `lib` to `package.json`.

**Comment by vkarpov15** [comment]
Where? It looks like `lib` is already in the `files` field: https://github.com/temporalio/sdk-typescript/blob/8f27f7c1e065b8effea84bcea93dfc496efc1dbc/packages/nyc-test-coverage/package.json#L28
