### ISSUE TITLE
[Bug] Remove `@types/long` stub types definition from `@temporalio/client`

### ISSUE THREAD

**Issue by mcmxcdev** [temporalio/sdk-typescript#844]
## Describe the bug

Deprecated `@types/long` is listed in https://github.com/temporalio/sdk-typescript/blob/main/packages/client/package.json#L21

Apart from the fact that `@types/*` packages generally should be moved to `devDependencies` to not end up being installed for the consumer, it can be removed since v5 of `long`.

This issue started popping up when upgrading `@temporalio/client` from 1.0.1 to 1.1.0

### Environment/Versions

- OS and processor: Manjaro Linux
- Temporal Version: 1.1.0

**Comment by bergundy** [comment]
We plan to remove this soon.
Because Long is in one of the exported types, if we didn’t include the types in the package dependencies TS would complain that it can’t get the type definition for it.

**Comment by bergundy** [comment]
I generally agree about type packages being devDependencies as we’ve done for all other type packages in the sdk
