### ISSUE TITLE
[Bug] Error running Temporal SDK inside linux docker container (might need musl target?)

### ISSUE THREAD

**Issue by noxasaxon** [temporalio/sdk-typescript#850]
### What are you really trying to do?

build & run a Docker container that runs `Worker.create()` using the Temporal Typescript SDK.

### Describe the bug

Failure when running javascript that uses the Temporal SDK from a linux based docker container without `gcc` installed.

I looked at other rust-based node libraries such as SWC and it looks like their node_modules package in my container includes both `linux-gnu` & `linux-musl` binaries while the temporal core-bridge only shows a `-gnu` binary, if that helps at all.

Error output :
```
/app/node_modules/@temporalio/core-bridge/index.js:10
    throw err;
    ^

Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/@temporalio/core-bridge/releases/x86_64-unknown-linux-gnu/index.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/@temporalio/core-bridge/index.js:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.5.0
```

### Environment/Versions

- intel mac pro 16 2020
- SDK version 1.1.0 (issue also appears in previous version)
- MacOS compiling linux docker container (container does not have gcc installed)

**Comment by mjameswh** [comment]
Using `musl` based images (such as Alpine) [is not supported](https://docs.temporal.io/typescript/production-deploy#do-not-use-alpine).

Can you try with a glibc based image, such as `node`? In any case, you _don't_ need to have gcc installed.

If you want a lightweight image, you can consider using the `node-slim` base image, with the `ca-certificates` package added.

**Comment by bergundy** [comment]
Closing this, it’s a documented limitation https://docs.temporal.io/typescript/production-deploy#do-not-use-alpine.
We might support this in the future though.

**Comment by noxasaxon** [comment]
Hey sorry for the delayed response, I had read those docs before and completely forgot about them while debugging other docker issues 🤦 .

Sorry for the pings, musl support would be cool but its not a huge blocker for me.
