### ISSUE TITLE
[Bug] `instanceof WorkflowNotFoundError` not working

### ISSUE THREAD

**Issue by omar-amal** [temporalio/sdk-typescript#863]
### What are you really trying to do?

Trying to use `if (err instanceof WorkflowNotFoundError)` to detect whether a workflow doesn't exist.

I'm running the following function to detect whether a workflow is scheduled to run:

```typescript
import { WorkflowNotFoundError } from '@temporalio/workflow'

export const getRecurringInvestment = async (wfId: string): Promise<GetRecurringInvestmentDTO | undefined> => {
  const getTemporalClient = initTemporalClient()
  const temporalClient = await getTemporalClient()

  const wfHandle = await temporalClient.getHandle(wfId)

  try {
    const [state, { status }] = await Promise.all([wfHandle.query(wfQuery), wfHandle.describe()])
    return status.name === 'CANCELLED' ? undefined : GetRecurringInvestmentDTO.parse(state)
  } catch (err: any) {
    // TODO most likely a bug in temporalio SDK.
    if (err instanceof WorkflowNotFoundError) {
      return undefined
    }
    throw err
  }
}
```

The ways a workflow wouldn't be scheduled to run, in our case, is if it's cancelled, or just wasn't created. If the workflow doesn't exist I would expect, per the documentation, for `wfHandle.describe()` or `wfHandle.query()` to throw with `WorkflowNotFoundError`

### Describe the bug

I would expect the following above block in the `catch` block to be reached:

```typescript
    // when the workflow doesn't exist, this `if` block should be entered, and the function should return `undefined`
    // however, the block is being skipped, and we're reaching the `throw err` instead.
    if (err instanceof WorkflowNotFoundError) {
      return undefined
    }
```

but it wasn't.  When I replaced the `if` block with the following, the block was successfully reached
```typescript
  } catch (err: any) {
    // Works: enters the `if` block
    if (err.name === 'WorkflowNotFoundError') {
      return undefined
    }
    throw err
  }
}
```

### Package versions
Using version 1.1.0 of `@temporalio/workflow` and the other packages.

**Comment by bergundy** [comment]
This is likely due to multiple versions of `@temporalio/common` installed.
Try changing the import to: `import { WorkflowNotFoundError } from '@temporalio/client'`
