### ISSUE TITLE
[Bug] `test-npm-init` hangs sometimes on Mac

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#874]
[test-npm-init (macos-latest, x86_64-apple-darwin, 16, cloud, hello-world-mtls)](https://github.com/temporalio/sdk-typescript/actions/runs/3086473404/jobs/4992010285#logs)

Sometimes the step `Test run a workflow` gets to here and stays running for > 2 hours. Here I manually cancelled:

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/251288/191156913-0ddb1203-6daf-4ea5-81b1-60f1332a76cd.png">

Sometimes the Action succeeds in 9 seconds.

**Comment by josh-berry** [comment]
Have we seen this recently or should this just be closed?

**Comment by bergundy** [comment]
I haven't been following closely, @mjameswh?

**Comment by josh-berry** [comment]
d'oh, was able to answer my own question. I do still see intermittent failures in GHA so we should keep this open.

**Comment by mjameswh** [comment]
>d'oh, was able to answer my own question. I do still see intermittent failures in GHA so we should keep this open.

We are still observing flakes in GHA, but I'm pretty sure we haven't seen this specific one in a very long time. We recently started tracking CI flakes in a private document, to help identify and triage recurring CI issues, and there's no trace of anything similar to this one.

I'm closing it.
