### ISSUE TITLE
[Feature Request] Retry sticky worker unavailable

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#880]
### Is your feature request related to a problem? Please describe.

I don't think our Client currently retries this error: 

```
Error: 14 UNAVAILABLE: sticky worker unavailable, please use original task queue
```

### Describe the solution you'd like

Retry it, as well as all other possible retryable server errors. (Do we have a list somewhere?)

### Additional context

https://temporalio.slack.com/archives/C01DKSMU94L/p1663739982172349?thread_ts=1663657363.309989&cid=C01DKSMU94L

**Comment by bergundy** [comment]
Looks like this should be retried by the server in recent server versions.
We already retry what we consider a list of retryable server errors https://github.com/temporalio/sdk-typescript/blob/dc63e490a22655fbdfa9e7fce4fa6f6fe57f2c92/packages/client/src/grpc-retry.ts#L100.
