### ISSUE TITLE
[Bug] workflowClient 

### ISSUE THREAD

**Issue by rachfop** [temporalio/sdk-typescript#886]
### What are you really trying to do?

Look up `workflowClient` or similar function.

### Describe the bug

I can see `workflowClient` in the search results.

<img width="565" alt="Screen Shot 2022-09-23 at 11 22 01 AM" src="https://user-images.githubusercontent.com/64233065/192032480-21c40e85-82cd-4726-9b33-c3f710e6d123.png">

However the page is not found:
https://typescript.temporal.io/api/interfaces/testing.workflowclientoptions/

If this is deprecated, perhaps it shouldn't continue to be indexed or a redirect could take place.

### Minimal Reproduction

Click here: https://typescript.temporal.io/api/interfaces/testing.workflowclientoptions/

Is this what was replaced with: https://typescript.temporal.io/api/classes/testing.testworkflowenvironment/#workflowclient

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by bergundy** [comment]
Might just be indexing delay

**Comment by lorensr** [comment]
Thanks Patrick, I was getting annoyed by that too 😄 Indexing is once/week or manual. Last one was 3h ago, and this issue was fixed.
