### ISSUE TITLE
[Bug] `stress-tests` may time out

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#913]
[stress-tests / stress-test](https://github.com/temporalio/sdk-typescript/actions/runs/3222639386/jobs/5271917118#logs)

seemed stuck on 

```
WFs complete (9940/10000)
```

**Comment by lorensr** [comment]
second run seemed stuck on:

```
WFs complete (63/100)
```

[stress-tests / stress-test](https://github.com/temporalio/sdk-typescript/actions/runs/3222639386/jobs/5272202180#logs)

**Comment by bergundy** [comment]
It's a known issue, we need to fix the stress test to recycle the instance every once in a while.

**Comment by mjameswh** [comment]
Duplicate of #853
