### ISSUE TITLE
[Bug] Docs Search Result Link 404

### ISSUE THREAD

**Issue by ricmatsui** [temporalio/sdk-typescript#917]
### What are you really trying to do?

Using the docs, we want to search for classes and then share the link to the search result. The shared link should always work.

### Describe the bug

Clicking on a search result from the docs search navigates to a URL that may contain uppercase characters. Opening this URL in a new tab goes to a 404 if it contains uppercase characters.

### Minimal Reproduction

- Go to https://typescript.temporal.io/
- Click the Search button on the top right (Cmd+K)
- Search for `ApplicationFailure` and click the Class result
- The search result links to this URL: https://typescript.temporal.io/api/classes/common.applicationfailure/
- Open the URL in a new tab, or refresh the page
- The page is a 404

The correct URL for the search result should be https://typescript.temporal.io/api/classes/common.ApplicationFailure

### Environment/Versions

- OS and processor: Intel Mac
- Temporal Version: N/A
- Are you using Docker or Kubernetes or building Temporal from source? N/A

### Additional context

This could be an issue with https://docusaurus.io/docs/search#using-algolia-docsearch or `docusaurus-plugin-typedoc`

**Comment by lorensr** [comment]
The 2 solutions I've found are:

- Changing typedoc plugin: https://github.com/tgreyuk/typedoc-plugin-markdown/issues/358
- Adding [custom normalization rules](https://www.algolia.com/doc/api-reference/api-parameters/customNormalization/?client=javascript) like `{A: 'A', B: 'B', etc}` to algolia. The [index UI](https://www.algolia.com/apps/FL5BOEA5LF/explorer/configuration/typescript-temporal/special-characters#customNormalization-section) only allows one at a time, and I balked at filling out 26 forms, and wanted to write a script, but I should probably just do that. Okay self, I'll do that now.

**Comment by lorensr** [comment]
Okay nevermind, while it wasn't that hard to submit 26 forms, when I hit save I got this:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/251288/195756166-94d0cd36-cef6-49d9-ae69-6ca860c60c07.png">

On the Vercel side, all I found was this:

https://vercel.com/docs/build-output-api/v3#build-output-configuration/supported-properties/routes/handler-route

but don't think you can use regex src and groups in dest to say "whatever comes in, if you don't find a file for it, try camelcase-ing part of it"

**Comment by lorensr** [comment]
Submitted a Vercel support ticket in case they have a setting I couldn't find

**Comment by lorensr** [comment]
> Due to the nature of our infrastructure, these will always be case sensitive and isn't something we have the ability to change. 
>
> As a workaround, you could consider catching these requests or standardizing them in middleware and redirecting them to the correct locations.

The [Edge Middleware](https://vercel.com/docs/concepts/functions/edge-middleware) would need to determine what a word is (converting `common.applicationfailure` to `common.ApplicationFailure`), so I'm leaning toward the typedoc plugin change.

**Comment by lorensr** [comment]
I'm not sure how lowercase URLs got in the index, but after an update to the Crawler config and updating the index, there are no more lowercase URLs! Thanks for reporting @ricmatsui 😊
