### ISSUE TITLE
[Bug] Error is blank in `Failed to activate workflow` messages

### ISSUE THREAD

**Issue by yolken-airplane** [temporalio/sdk-typescript#948]
### What are you really trying to do?

We're trying to detect when workflows fail to activate and return a reason back to our users.

### Describe the bug

We have some workflows that fail to activate due to timeouts and other issues. The worker outputs a `Failed to activate` message with an error, but it seems like this error is always empty, i.e. `"error":{}`. The "real error" is visible in a `TRACE` message later on, but that message doesn't have as much context and also sometimes doesn't appear (not sure why). 

It would be nice if the original `Failed to activate` message had more information on what happened.

Here's an example of the logs when the activation failure is due to a timeout:

```
[TRACE] Creating workflow {"namespace":"default","taskQueue":"hello-world","workflowId":"workflow-rB1OaMvJNTlJ0Qb6aZGp2","runId":"44fdc3ad-1e89-4676-8f37-1b73595031a5","workflowType":"example"}
[DEBUG] Workflow started {"namespace":"default","taskQueue":"hello-world","workflowId":"workflow-rB1OaMvJNTlJ0Qb6aZGp2","runId":"44fdc3ad-1e89-4676-8f37-1b73595031a5","workflowType":"example"}
[ERROR] Failed to activate workflow {"namespace":"default","taskQueue":"hello-world","workflowId":"workflow-rB1OaMvJNTlJ0Qb6aZGp2","runId":"44fdc3ad-1e89-4676-8f37-1b73595031a5","workflowType":"example","error":{},"workflowExists":true}
[TRACE] Got workflow activation {"jobs":[{"removeFromCache":{"message":"Workflow activation completion failed: Failure { failure: Some(Failure { message: \"Script execution timed out after 5000ms\", source: \"TypeScriptSDK\", stack_trace: \"Error: Script execution timed out after 5000ms\", encoded_attributes: None, cause: None, failure_info: None }) }","reason":"LANG_FAIL"}}],"runId":"44fdc3ad-1e89-4676-8f37-1b73595031a5","timestamp":{"seconds":"1667442437","nanos":223436135},"historyLength":6}
[TRACE] Disposing workflow {"runId":"44fdc3ad-1e89-4676-8f37-1b73595031a5"}
```

### Minimal Reproduction

Make the following changes to the ["hello-world" example](https://github.com/temporalio/samples-typescript/tree/main/hello-world):

1. Add a `while(true) {}` in the workflow `example` function
2. (Optional) Turn on trace logging in the worker via something like:

```
  const logger = new DefaultLogger("TRACE", ({ level, message, meta }) => {
    if (meta) {
      console.log(`[${level}] ${message} ${JSON.stringify(meta)}`);
    } else {
      console.log(`[${level}] ${message}`);
    }
  });
  Runtime.install({ logger });
```

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: v1.18.1 (server), 1.4.3 (SDK)
- Are you using Docker or Kubernetes or building Temporal from source? Using temporalite

### Additional context

N/A

**Comment by mjameswh** [comment]
Now, regarding the TS SDK itself, I can't find any problematic case as of 1.7.3. The repro code above works correctly if not using the custom logger, or with the custom logger modified to use `util.format` instead of `JSON.stringify`.

**Comment by yolken-airplane** [comment]
@mjameswh thanks for this explanation!
