### ISSUE TITLE
Go through all deprecated imports

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#966]
To see if we can or need to import something different. Turning on this rule will highlight them:

https://github.com/temporalio/sdk-typescript/blob/508034457ad5cd574d0f9948fd58380f5743c8ec/.eslintrc#L40-L41

**Comment by mjameswh** [comment]
Pruned all dependencies as part of #1330.

Also tried enabling `import/no-deprecated`, but it caused a lot of false-positives, with nothing pertinent over what `deprecation/deprecation` already provides.
