### ISSUE TITLE
Run `cargo fmt/clippy` from `npm run format/lint`

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-typescript#970]
Rust code contained in package `core-bridge` but outside the `core-sdk` submodule can benefit from `cargo fmt` and `cargo clippy`, but it is easy to forget running them after modifying `core-bridge`'s code.

Running these commands from that NPM package's `format` and `lint` scripts would help ensure that they are regularly run.

**Comment by bergundy** [comment]
Yes please
