### ISSUE TITLE
[Bug] Activity schedule to start metric incorrect during retries 

### ISSUE THREAD

**Issue by ksapchuk** [temporalio/sdk-typescript#972]
### What are you really trying to do?
We are trying to use the `temporal_activity_schedule_to_start_latency` metric to measure how behind our workers are in picking up activities.

### Describe the bug
If the activities are failing with retries the `temporal_activity_schedule_to_start_latency` metric reports high schedule to start latency despite there being no scheduling delays. Is the SDK using the activity's first run start time for calculating the activity retries' schedule to start latency? 

### Minimal Reproduction
A failing workflow with activity retries
```
const { fail } = proxyActivities<typeof activities>({
  startToCloseTimeout: '5 minutes',
  retry:{
    maximumAttempts: 5,
    initialInterval: '10 seconds',
    backoffCoefficient: 1,
  }
});

export async function logSampleWorkflow(): Promise<void> {
  await fail();
}
```

An activity that always fails 
```
export async function greet(): Promise<void> {
  throw Error('failing');
}
```

The worker runtime is setup with prometheus telemetry.
```
  Runtime.install({
    telemetryOptions: {
      metrics: {
        prometheus: { bindAddress: '0.0.0.0:9464' },
      },
    },
  });
```

After running the workflow `curl localhost:9464/metrics` to see the metric values. A bunch of retries land in the last activity bucket and the total activity latency is 60 seconds despite the activities starting immediately after their retry window. 
```# TYPE temporal_activity_schedule_to_start_latency histogram
temporal_activity_schedule_to_start_latency_bucket{namespace="default",service_name="temporal-core-sdk",task_queue="instrumentation",le="100"} 1
temporal_activity_schedule_to_start_latency_bucket{namespace="default",service_name="temporal-core-sdk",task_queue="instrumentation",le="500"} 1
temporal_activity_schedule_to_start_latency_bucket{namespace="default",service_name="temporal-core-sdk",task_queue="instrumentation",le="1000"} 1
temporal_activity_schedule_to_start_latency_bucket{namespace="default",service_name="temporal-core-sdk",task_queue="instrumentation",le="5000"} 1
temporal_activity_schedule_to_start_latency_bucket{namespace="default",service_name="temporal-core-sdk",task_queue="instrumentation",le="10000"} 1
temporal_activity_schedule_to_start_latency_bucket{namespace="default",service_name="temporal-core-sdk",task_queue="instrumentation",le="+Inf"} 4
temporal_activity_schedule_to_start_latency_sum{namespace="default",service_name="temporal-core-sdk",task_queue="instrumentation"} 60251
temporal_activity_schedule_to_start_latency_count{namespace="default",service_name="temporal-core-sdk",task_queue="instrumentation"} 4
```

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: 1.18.1 
- Typescript SDK 1.4.4

**Comment by bergundy** [comment]
The SDK is using the time the activity was first scheduled:

https://github.com/temporalio/api/blob/9645a99d585b426ebb7555b8f61f5b1ed1aa42af/temporal/api/workflowservice/v1/request_response.proto#L365-L366

There's also this which might be more useful to you.

```
    // When was this task attempt scheduled
    google.protobuf.Timestamp current_attempt_scheduled_time = 11 [(gogoproto.stdtime) = true];
```

I don't think this is a bug, it should be by design, I'll double check what we do in other SDKs.

**Comment by bergundy** [comment]
Update: after checking other SDKs, looks like they're using the `current_attempt_scheduled_time`.
See linked Core PR which corrects this behavior.
