### ISSUE TITLE
[Bug] `WorkflowNotFoundError` used when namespace not found

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#976]
### Describe the bug

<img width="968" alt="image" src="https://user-images.githubusercontent.com/251288/203870125-6d67f713-d81b-45e7-a084-f63151843f06.png">

### Options

In order of not breaking to most breaking:

1. Add "namespace does not exist" to the list of reasons:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/251288/203870152-1dacb8f5-d71f-44aa-80a5-fbb0b5bb02af.png">

https://typescript.temporal.io/api/classes/workflow.WorkflowNotFoundError

2. Add `NamespaceNotFoundError`
3. Remove `WorkflowNotFoundError` and just throw `ServiceError`

### Meta

1. Are there other possible reasons for `grpcStatus.NOT_FOUND`?
2. For all the other gRPC status codes we check for throwing a specific error, are there cases for those codes we haven't considered? Can search for `grpcStatus.*` and `status.*`

**Comment by bergundy** [comment]
I saw this coming, it came up in a team discussion. We need to extract the error details from headers like go does, possibly using this library: https://github.com/stackpath/node-grpc-error-details
