### ISSUE TITLE
[Doc] Document how to bundle with esbuild

### ISSUE THREAD

**Issue by wenerme** [temporalio/sdk-typescript#978]
### What are you really trying to do?

<details>

<summary>First try</summary>

> ReferenceError: __TEMPORAL__ is not defined

```bash
pnpm esbuild --external:./dist/* --external:__* --bundle --outdir=dist/ --keep-names --format=cjs --sourcemap=inline --charset=utf8 --target=node16 --platform=node \
  --banner:js="module = typeof module === 'undefined'? {exports:{}}:module" \
  ./src/entrypoint.ts
```

</details>

**Second try**

> Error: Dynamic require of "__temporal_custom_payload_converter" is not supported

```bash
pnpm esbuild --external:__* --bundle --outdir=dist/ --keep-names --format=iife --sourcemap=inline --charset=utf8 -- 
 target=chrome100 \
  --global-name=__TEMPORAL__ \
  ./src/server/workflows/entrypoint.ts
```

esbuild to not support the alias

https://github.com/temporalio/sdk-typescript/blob/a5eedca5d4cfb5a7b04f9bd65df5dc8547b2f27f/packages/worker/src/workflow/bundler.ts#L193-L241

**Final HACK**

```bash
sed -i -r 's#__importStar[(]__require[(]"__temporal_custom.*?"[)][)]#({})#g' ./dist/entrypoint.js
```

> **Note**
> webpack load+bundled in 0m2.032s (ignore tsc)
> esbuild bundled in 40ms, worker started by tsx (without tsc), a lot faster

**entrypoint.ts**

```ts
import * as api from '@temporalio/workflow/lib/worker-interface.js';

// Bundle all Workflows and interceptor modules for lazy evaluation
api.overrideGlobals();
api.setImportFuncs({
  importWorkflows: () => {
    return import('./workflows');
  },
  importInterceptors: () => {
    return Promise.all([]);
  },
});

export { api };
```

**workflows.ts**

```ts
import { proxyActivities } from '@temporalio/workflow';
import type * as activities from './activities';

const { greet } = proxyActivities<typeof activities>({
  startToCloseTimeout: '1 minute',
});

/** A workflow that simply calls an activity */
export async function example(name: string): Promise<string> {
  return await greet(name);
}
```

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by mjameswh** [comment]
Thanks for sharing the learning you acquired on this subject. It might help others trying to do similar things.

The time required to bundle workflows is indeed a frequently expressed concern of our developers. Using esbuild is often proposed as a solution to this, and we might consider supporting it officially, as an alternative to Webpack, at some point in the future.

We can't however recommend using a custom workflow bundler at this point in time. The bundling process is an integral part of the workflow sandboxing mechanisms provided by the TypeScript SDK. Bug fixes and development of new features regularly require us to modify various aspect of the bundler. That includes notably the content of the entrypoint.js file, usage of __temporal_, the way source maps are encoded, the way modules are stored, and other details.

Custom bundling processes are therefore very fragile and might require maintenance effort on each SDK release (possibly even some patch level releases). Possible, but definitely not something that we want to encourage broadly.

For this reason, I don't think we should include this subject in our official documentation at this point. You are however welcome to keep this ticket updated with any further learning you may acquire on this subject.

**Comment by wenerme** [comment]
I tried using webpack bundle in the nextjs project, but the build process failed with `Module parse failed: 'import' and 'export' may appear only with 'sourceType: module'`, the embedded bundling process depends on the env, that's harder to control.

I hope the sdk can use global inject to replace the `__temporal_*` hack, I will keep using external esbuild bundling, until I need the function that provided by `__temporal_*`, then may add more hacks.

About the `__temporal_*`, I think sdk can use a stub module like `export const {x: 'MAGIC_NUMBER'}`, the just replace the code before running will be better than the `require('__temporal_*')`.
