### ISSUE TITLE
[Bug] Intermediate certificates sample does not work on MacOS

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#98]
**Describe the bug**
When trying to connect the Worker to a server using the `tls-full` [sample](https://github.com/temporalio/customization-samples/tree/master/tls/tls-full), connection fails with `[TransportError: transport error: error trying to connect: invalid certificate: UnknownIssuer]`

**To Reproduce**
1. Follow the [mTLS tutorial](https://docs.temporal.io/docs/node/tls/#mtls-tutorial) but use `tls-full` instead of simple
1. Run the Worker
```shell
TEMPORAL_ADDRESS=localhost \
TEMPORAL_NAMESPACE=accounting \
TEMPORAL_CLIENT_CERT_PATH=certs/client/accounting/client-accounting-namespace-chain.pem \
TEMPORAL_CLIENT_KEY_PATH=certs/client/accounting/client-accounting-namespace.key \
TEMPORAL_SERVER_NAME_OVERRIDE=accounting.cluster-x.contoso.com \
TEMPORAL_SERVER_ROOT_CA_CERT_PATH=certs/cluster/ca/server-intermediate-ca.pem \
npm start
```

**Expected behavior**
Worker should connect to server

**Versions (please complete the following information where relevant):**
 - OS: Mac
 - Temporal Version: `temporalio/auto-setup@sha256:004f4440664f13c3b049eaad5c019c9f780082d8752655d01ef91e322b482097`

**Additional context**
Tried using different certificates without success, seems like this is a MacOS issue, @Sushisource got it working on Linux.

**Comment by liammurray** [comment]
I believe I am running into this. I can connect with tctl but not from my typescript SDK worker using the same certificates and client ky. I also get the same error when I run the worker in a docker container (local and on a Linux node).

**Comment by liammurray** [comment]
I got it to work by adding `-sha256` to the openssl commands generating the certs (it was defaulting to sha1).
